<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(DotNetAndroidTargetFramework)</TargetFramework>
    <SupportedOSPlatformVersion>24</SupportedOSPlatformVersion>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseMaui>true</UseMaui>
    <SingleProject>true</SingleProject>
    <ApplicationId>net.dot.hybridruntime</ApplicationId>
    <ApplicationVersion>1</ApplicationVersion>
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
    <AndroidPackageFormat>apk</AndroidPackageFormat>
    <RuntimeIdentifier>android-arm64</RuntimeIdentifier>
    <UseMonoRuntime>false</UseMonoRuntime>
    <PublishAot>false</PublishAot>
    <PublishReadyToRun>false</PublishReadyToRun>
    <AndroidLinkMode>None</AndroidLinkMode>
    <AndroidTypeMapImplementation>trimmable</AndroidTypeMapImplementation>
  </PropertyGroup>

  <ItemGroup>
    <AndroidJavaSource Include="..\Shell\java\**\*.java" />
    <PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
    <ProguardConfiguration Include="..\Shell\proguard.cfg" />
    <ProjectReference Include="..\HybridTodoApp\HybridTodoApp.csproj" />
  </ItemGroup>
</Project>
