using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Xamarin.Installer.AndroidSDK.Properties;
using Xamarin.Installer.Common;

namespace Xamarin.Installer.AndroidSDK.Common
{
	/// <summary>
	/// AndroidLicensesStorage class has all the protocol to check if a License was accepted
	/// </summary>
	public class AndroidLicensesStorage : ILicensesStorage
	{
		/// <summary>
		/// Returns the path where licenses acceptance are stored
		/// </summary>
		/// <param name="androidSdkPath">Android Sdk path</param>
		/// <returns>Directory path where the licenses acceptance are stored</returns>
		protected virtual string GetLicensesPath(string androidSdkPath)
		{
			return string.IsNullOrWhiteSpace(androidSdkPath) || !Directory.Exists(androidSdkPath) ? null : Path.Combine(androidSdkPath, "licenses");
		}

		/// <summary>
		/// Returns if the license was accepted in this Android SDK
		/// </summary>
		/// <param name="androidSdkPath">Android Sdk path</param>
		/// <param name="license">license to check</param>
		/// <returns>true if the license is accepted, false otherwise</returns>
		public bool IsLicenseAccepted(string androidSdkPath, License license)
		{
			if (license == null || string.IsNullOrEmpty(license.ID))
				return false;

			var localLicensesPath = GetLicensesPath(androidSdkPath);
			if(string.IsNullOrEmpty(localLicensesPath))
				return false;

			var licensePath = Path.Combine(localLicensesPath, license.ID);
			if (!File.Exists(licensePath))
				return false;

			var storedLicenseHash = GetLicenseHash(licensePath);
			return !string.IsNullOrEmpty(storedLicenseHash);
		}

		protected virtual string GetLicenseHash(License license)
		{
			if (string.IsNullOrEmpty(license?.Text))
			{
				return null;
			}

			var licenseText = license.Text;
#pragma warning disable CA5350
			using (var hashAlgorithm = SHA1.Create()) // CodeQL [SM02196] Used to verify checksums provided by an external party.
			{
				var bytes = Encoding.UTF8.GetBytes(licenseText);
				var hash = string.Concat(hashAlgorithm.ComputeHash(bytes).Select(x => x.ToString("x2")));
				return hash;
			}
#pragma warning restore CA5350
		}

		protected virtual string GetLicenseHash(string licensePath)
		{
			return string.IsNullOrWhiteSpace(licensePath) || !File.Exists(licensePath) ? null : File.ReadAllText(licensePath);
		}

		/// <summary>
		/// Accept licenses using local storage
		/// </summary>
		/// <param name="androidSdkPath">Android Sdk path</param>
		/// <param name="javaSdkPath">Java Sdk path</param>
		/// <param name="cmdLineToolsPath">specific cmdLine-tools path to use</param>
		/// <param name="licenses">list of licenses to accept</param>
		/// <param name="token">cancellation token</param>
		/// <param name="logPath">log file path</param>
		/// <param name="throwsErrorIfValidationFailed">if true, throws an exception if license validation fails</param>
		public Task AcceptLicensesAsync(
			string androidSdkPath,
			string javaSdkPath,
			string cmdLineToolsPath,
			IEnumerable<License> licenses,
			CancellationToken token,
			string logPath = null,
			bool throwsErrorIfValidationFailed = false)
		{
			return Task.Run(async () =>
			{
				var progress = new AggregateProgressSink(logPath);

				try
				{
					var error = ValidateAcceptLicensesArguments(androidSdkPath, javaSdkPath, cmdLineToolsPath, licenses, progress);
					if (!string.IsNullOrEmpty(error))
					{
						if (throwsErrorIfValidationFailed)
						{
							throw new NotSupportedException(error);
						}
						else
						{
							return;
						}
					}

					var licenseIDs = licenses.Select(x => x.ID).Distinct();
					progress.Report($"Licenses to be accepted: {string.Join("|", licenseIDs)}");

					// run sdkmanager from cmdline-tools to accept the licenses
					await WriteGoogleLicensesAsync(androidSdkPath, javaSdkPath, cmdLineToolsPath, licenses, token, progress);

					// it is required because the hash can be different than the generated by google
					// Xamarin feed licenses text can be not in sync with latest google feed licenses text
					// Xamarin feed is generated/updated on each VS release,
					// and VS releases are not in sync with the cadence of updates of Google feed
					WriteVSLicenses(androidSdkPath, licenses, token, progress);
				}
				finally
				{
					progress.Dispose();
				}
			}, token);
		}

		string ValidateAcceptLicensesArguments(
			string androidSdkPath,
			string javaSdkPath,
			string cmdLineToolsPath,
			IEnumerable<License> licenses, 
			AggregateProgressSink progress)
		{
			if (!licenses.Any())
			{
				progress?.Report("Android licenses acceptance discarded, no licenses to accept");
				return string.Empty;
			}

			if (string.IsNullOrEmpty(androidSdkPath) || !Directory.Exists(androidSdkPath))
			{
				progress?.Report(Resources.AccepLicensesFailedAndroidSDKNotFound);
				return Resources.AccepLicensesFailedAndroidSDKNotFound;
			}

			if (string.IsNullOrEmpty(javaSdkPath) || !Directory.Exists(javaSdkPath))
			{
				progress?.Report(Resources.AccepLicensesFailedJavaSDKNotFound);
				return Resources.AccepLicensesFailedJavaSDKNotFound;
			}

			if (string.IsNullOrEmpty(cmdLineToolsPath))
			{
				progress?.Report(Resources.AccepLicensesFailedCMDLineToolsNotFound);
				return Resources.AccepLicensesFailedCMDLineToolsNotFound;
			}

			var cmdLineToolsPropertiesFilePath = Path.Combine(cmdLineToolsPath, "source.properties");
			if (!File.Exists(cmdLineToolsPropertiesFilePath))
			{
				progress?.Report(Resources.AccepLicensesFailedCMDLineToolsNotFound);
				return Resources.AccepLicensesFailedCMDLineToolsNotFound;
			}

			return string.Empty;            
		}

		protected void WriteVSLicenses(
			string androidSdkPath,
			IEnumerable<License> licenses,
			CancellationToken token,
			AggregateProgressSink progress)
		{
			if (!licenses.Any())
				return;

			// creates local licenses storage folder
			if (token.IsCancellationRequested)
				return;

			progress.Report("Running local accept licenses process");

			try
			{
				var licensesPath = GetLicensesPath(androidSdkPath);
				if (!Directory.Exists(licensesPath))
					Directory.CreateDirectory(licensesPath);

				// save licenses
				var licensesToAccept = licenses.Where(license => !string.IsNullOrEmpty(license.ID)).GroupBy(license => license);
				foreach (var l in licensesToAccept)
				{
					if (token.IsCancellationRequested)
						return;

					var androidLicense = l.Key;

					var licensePath = Path.Combine(licensesPath, androidLicense.ID);
					var licenseHash = GetLicenseHash(androidLicense);

					WriteLicenseHash(licensePath, licenseHash);
				}

				progress.Report("Running local accept licenses process completed");
			}
			catch (Exception ex)
			{
				progress.Report($"Running local accept licenses process failed: {ex.Message}");
			}
		}

		protected virtual void WriteLicenseHash(string licensePath, string licenseHash)
		{
			// same format as generated by google sdkmanager licenses command
			var sb = new StringWriter();

			if (File.Exists(licensePath))
			{
				sb.WriteLine(""); // enter for previous line
			}

			sb.WriteLine(""); // force empty line
			sb.WriteLine(licenseHash); // hash

			File.AppendAllText(licensePath, sb.ToString());
		}

		protected async Task WriteGoogleLicensesAsync(
			string androidSdkPath,
			string javaSdkPath,
			string cmdLineToolsPath,
			IEnumerable<License> licenses,
			CancellationToken token,
			AggregateProgressSink progress)
		{
			progress.Report("Running sdkmanager --licenses --verbose");

			var standardOutput = progress.ForOutputs;
			var standardError = progress.ForErrors;

			var sdkManagerApp = string.Empty;
			switch (AndroidSDKContext.Instance.Platform)
			{
				case AndroidSDKPlatform.Linux:
				case AndroidSDKPlatform.Mac:
					sdkManagerApp = "sdkmanager";
					break;
				case AndroidSDKPlatform.Windows:
					sdkManagerApp = "sdkmanager.bat";
					break;

				default:
					throw new InvalidOperationException("Unsupported platform");
			}

			var processStartInfo = new ProcessStartInfo(fileName: Path.Combine(cmdLineToolsPath, "bin", sdkManagerApp), "--licenses --verbose");
			processStartInfo.WorkingDirectory = Path.Combine(cmdLineToolsPath, "bin");
			processStartInfo.WindowStyle = ProcessWindowStyle.Hidden;
			processStartInfo.UseShellExecute = false;
			processStartInfo.RedirectStandardError = true;
			processStartInfo.RedirectStandardInput = true;
			processStartInfo.RedirectStandardOutput = true;
			processStartInfo.CreateNoWindow = true;

			if (!string.IsNullOrEmpty(javaSdkPath))
				{
					// Use short path (8.3 format) for JAVA_HOME on Windows to avoid batch script parsing issues
					// when paths contain parentheses like "Program Files (x86)" which break CMD.exe IF/FOR blocks.
					// See: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/2632833
					var javaHomePath = AndroidSDKContext.Instance.Platform == AndroidSDKPlatform.Windows
						? CommonUtilities.GetShortPath(javaSdkPath)
						: javaSdkPath;
					processStartInfo.EnvironmentVariables["JAVA_HOME"] = javaHomePath;
				}

			var process = new Process();
			process.StartInfo = processStartInfo;

			bool matchLicenseId = false;
			var loadingLocalRepository = true;

			var inputAnswers = new ConcurrentQueue<string>();
			inputAnswers.Enqueue("Y"); // to accept the review "Review licenses that have not been accepted (y/N)?"

			if (processStartInfo.RedirectStandardOutput)
			{
				process.OutputDataReceived += (sender, e) =>
				{
					if (e.Data != null)
					{
						standardOutput?.Report(e.Data);

						if (e.Data.Contains("(y/N)?"))
						{
							// when the message "Review licenses that have not been accepted (y/N)?" is reported the loading phase and display all licenses text ends
							loadingLocalRepository = false;
						}

						// try to match the license id from message: "License {id}:"
						if (loadingLocalRepository && licenses.Any(x => e.Data.Contains($"{x.ID}:")))
						{
							matchLicenseId = true;
						}

						if (loadingLocalRepository && e.Data.Trim().Equals("Accepted"))
						{
							// reset the match when an accepted license is detected
							matchLicenseId = false;
						}

						if (loadingLocalRepository && e.Data.Trim().Contains("Not yet accepted"))
						{
							// enqueue a Y/N answer
							if (matchLicenseId)
							{
								matchLicenseId = false;
								inputAnswers.Enqueue("Y");
							} 
							else
							{
								inputAnswers.Enqueue("N");
							}
						}
					}
				};
			}

			if (processStartInfo.RedirectStandardError)
			{
				process.ErrorDataReceived += (sender, e) =>
				{
					standardError?.Report(e.Data);
				};
			}

			process.Start();

			if (processStartInfo.RedirectStandardOutput)
				process.BeginOutputReadLine();

			if (processStartInfo.RedirectStandardError)
				process.BeginErrorReadLine();

			process.StandardInput.AutoFlush = true;

			while (!process.HasExited)
			{
				if (token.IsCancellationRequested)
				{
					process.Kill();
				}
				else
				{
					try
					{
						if (inputAnswers.Any() && inputAnswers.TryDequeue(out var inputAnswer))
						{
							await process.StandardInput.WriteLineAsync(inputAnswer);
						}
					}
					catch (Exception e)
					{
						progress.Report(e.Message);
					}
				}
			}

			if (!token.IsCancellationRequested && process.ExitCode > 0)
			{
				var errorMessage = $"""
					{Resources.GoogleAccepLicensesFailed}.
					Exit code: {process.ExitCode}.
					Android SDK: '{androidSdkPath}'.
					Java SDK: '{javaSdkPath}'.
					Command-line tools: '{cmdLineToolsPath}'.
					""";

				if (!string.IsNullOrEmpty(standardError.Errors))
				{
					errorMessage += $" Errors: {standardError.Errors}";
				}

				progress.Report(errorMessage);
				throw new Exception(errorMessage);
			}
		}

		protected class AggregateProgressSink : IProgress<string>, IDisposable
		{
			private StreamWriter writer;

			public AggregateProgressSink(string logPath)
			{
				this.ForOutputs = new OutputProgressSink(this);
				this.ForErrors = new ErrorProgressSink(this);
				this.writer = string.IsNullOrEmpty(logPath) ? null : new StreamWriter(logPath);
			}

			public OutputProgressSink ForOutputs { get; private set; }

			public ErrorProgressSink ForErrors { get; private set; }

			public void Report(string value)
			{
				this.writer?.WriteLine(value);
			}

			public void Dispose()
			{
				this.writer?.Close();
				this.writer = null;
			}
		}

		protected class OutputProgressSink : IProgress<string>
		{
			private IProgress<string> fileSink;

			public OutputProgressSink(IProgress<string> fileSink)
			{
				this.fileSink = fileSink;
			}

			public void Report(string value)
			{
				this.fileSink.Report(value);
			}
		}

		protected class ErrorProgressSink : IProgress<string>
		{
			private readonly StringBuilder allErrors = new StringBuilder();
			private readonly IProgress<string> fileSink;

			public ErrorProgressSink(IProgress<string> fileSink)
			{
				this.fileSink = fileSink;
			}

			public string Errors => this.allErrors.ToString();

			public void Report(string value)
			{
				this.fileSink.Report(value);
				this.allErrors.AppendLine(value);
			}
		}
	}
}
