//  Authors:
//    Marek Habersack <grendel@twistedcode.net>
//
//  Copyright (c) 2017, Microsoft, Inc
//
//  All rights reserved.
//
using System;

namespace Xamarin.Installer.AndroidSDK.Common
{
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
	public static partial class Constants
	{
		public static class ComponentPaths
		{
			public const string BuildTools = "build-tools;";
			public const string CMake = "cmake;";
			public const string Emulator = "emulator";
			public const string LLDB = "lldb;";
			public const string NDK = "ndk-bundle";
			public const string PlatformTools = "platform-tools";
			public const string ToolsObsolete = "tools";
			public const string Tools = "cmdline-tools";
			public const string ToolsLatest = "cmdline-tools;latest";

			public const string Platforms = "platforms";

			public const string HypervisorDriver = "extras;google;Android_Emulator_Hypervisor_Driver";
        }

		public static partial class RequiredComponentVersions
		{
			// This class has properties which are auto generated by the GenerateRequiredComponentVersions MSBuild Target

			// this defaults are used by the IDEs to complete the required components on the auto-sdk process
			// values are in sync with the GetAndroidDependencies target result
			public static readonly string[] RequiredComponents = {
				$"build-tools/{RequiredBuildToolsVersion}@{RequiredBuildToolsVersion}",
 				$"platform-tools@{RequiredPlatformToolsVersion}",
				$"cmdline-tools/{RequiredCommandLineToolsVersion}@{RequiredCommandLineToolsVersion}",
 			};
		}
	}
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
}
