// See: eng/gradle/plugin-repositories.gradle, eng/gradle/dependency-repositories.gradle
pluginManagement {
    apply from: "${rootDir}/../../eng/gradle/plugin-repositories.gradle", to: pluginManagement
    if (System.getenv('DEPENDABOT_JOB_ID') != null) {
        repositories {
            google()
        }
    }
}
dependencyResolutionManagement {
    apply from: "${rootDir}/../../eng/gradle/dependency-repositories.gradle", to: dependencyResolutionManagement
    if (System.getenv('DEPENDABOT_JOB_ID') != null) {
        repositories {
            google()
        }
    }
}

rootProject.name = 'r8'