// <auto-generated>
// This file is generated from JniMarshalTyped.tt.  Do not edit it directly;
// edit the template and re-run `t4 JniMarshalTyped.tt -o JniMarshalTyped.cs`.
// </auto-generated>
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

using Android.Runtime;

namespace Java.Interop {

	/// <summary>
	/// Typed marshaling helpers shared by the experimental direct-<c>[UnmanagedCallersOnly]</c>
	/// binding callback shape.
	/// </summary>
	/// <remarks>
	/// <para>
	/// These helpers own everything that would otherwise be duplicated into every generated
	/// <c>n_*</c> callback: the JNI transition (<c>BeginMarshalMethod</c>/<c>EndMarshalMethod</c>),
	/// GC bridge synchronization, unhandled exception reporting, the managed peer lookup for
	/// <c>self</c>, the peer lookup for supported object arguments, and the JNI conversion of a
	/// peer return value.
	/// </para>
	/// <para>
	/// Method names encode the shape being marshaled: <c>Invoke_</c> followed by one
	/// character per argument (<c>O</c> = object reference, <c>S</c> = scalar) followed by one
	/// character for the return value (<c>X</c> = void, <c>S</c> = scalar, <c>O</c> = object
	/// reference).  Shapes which are not safely centralizable — strings, arrays and other
	/// copy-back parameters, generic and by-ref parameters — are intentionally absent: the
	/// generator falls back to <see cref="JniMarshal.SafeInvokeAction(IntPtr, IntPtr, delegate* managed&lt;IntPtr, IntPtr, void&gt;)" />
	/// and friends for those.
	/// </para>
	/// </remarks>
	[SuppressMessage (
		"Design",
		"CA1031:Do not catch general exception types",
		Justification = "Exceptions cannot cross a JNI boundary.")]
	public static class JniMarshalTyped {

		const DynamicallyAccessedMemberTypes Constructors =
			DynamicallyAccessedMemberTypes.PublicConstructors | DynamicallyAccessedMemberTypes.NonPublicConstructors;

		const string PeerLookupFailed = "Unable to marshal the JNI `this` reference to its managed peer.";

		[DebuggerDisableUserUnhandledExceptions]
		public static unsafe void Invoke_X<[DynamicallyAccessedMembers (Constructors)] TPeer> (IntPtr jnienv, IntPtr self, delegate* managed<TPeer, void> body)
			where TPeer : class, IJavaObject
		{
			AndroidRuntimeInternal.WaitForBridgeProcessing ();

			if (!JniEnvironment.BeginMarshalMethod (jnienv, out var __envp, out var __r))
				return;

			try {
				var __this = global::Java.Lang.Object.GetObject<TPeer> (self, JniHandleOwnership.DoNotTransfer);
				if (__this is null)
					throw new NullReferenceException (PeerLookupFailed);
				body (__this);
			} catch (Exception __e) {
				__r.OnUserUnhandledException (ref __envp, __e);
				return;
			} finally {
				JniEnvironment.EndMarshalMethod (ref __envp);
			}
		}

		[DebuggerDisableUserUnhandledExceptions]
		public static unsafe TResult Invoke_S<[DynamicallyAccessedMembers (Constructors)] TPeer, TResult> (IntPtr jnienv, IntPtr self, delegate* managed<TPeer, TResult> body)
			where TPeer : class, IJavaObject
			where TResult : unmanaged
		{
			AndroidRuntimeInternal.WaitForBridgeProcessing ();

			if (!JniEnvironment.BeginMarshalMethod (jnienv, out var __envp, out var __r))
				return default;

			try {
				var __this = global::Java.Lang.Object.GetObject<TPeer> (self, JniHandleOwnership.DoNotTransfer);
				if (__this is null)
					throw new NullReferenceException (PeerLookupFailed);
				return body (__this);
			} catch (Exception __e) {
				__r.OnUserUnhandledException (ref __envp, __e);
				return default;
			} finally {
				JniEnvironment.EndMarshalMethod (ref __envp);
			}
		}

		[DebuggerDisableUserUnhandledExceptions]
		public static unsafe IntPtr Invoke_O<[DynamicallyAccessedMembers (Constructors)] TPeer> (IntPtr jnienv, IntPtr self, delegate* managed<TPeer, IJavaObject?> body)
			where TPeer : class, IJavaObject
		{
			AndroidRuntimeInternal.WaitForBridgeProcessing ();

			if (!JniEnvironment.BeginMarshalMethod (jnienv, out var __envp, out var __r))
				return default;

			try {
				var __this = global::Java.Lang.Object.GetObject<TPeer> (self, JniHandleOwnership.DoNotTransfer);
				if (__this is null)
					throw new NullReferenceException (PeerLookupFailed);
				return JNIEnv.ToLocalJniHandle (body (__this));
			} catch (Exception __e) {
				__r.OnUserUnhandledException (ref __envp, __e);
				return default;
			} finally {
				JniEnvironment.EndMarshalMethod (ref __envp);
			}
		}

		[DebuggerDisableUserUnhandledExceptions]
		public static unsafe void Invoke_SX<[DynamicallyAccessedMembers (Constructors)] TPeer, T0> (IntPtr jnienv, IntPtr self, T0 p0, delegate* managed<TPeer, T0, void> body)
			where TPeer : class, IJavaObject
			where T0 : unmanaged
		{
			AndroidRuntimeInternal.WaitForBridgeProcessing ();

			if (!JniEnvironment.BeginMarshalMethod (jnienv, out var __envp, out var __r))
				return;

			try {
				var __this = global::Java.Lang.Object.GetObject<TPeer> (self, JniHandleOwnership.DoNotTransfer);
				if (__this is null)
					throw new NullReferenceException (PeerLookupFailed);
				body (__this, p0);
			} catch (Exception __e) {
				__r.OnUserUnhandledException (ref __envp, __e);
				return;
			} finally {
				JniEnvironment.EndMarshalMethod (ref __envp);
			}
		}

		[DebuggerDisableUserUnhandledExceptions]
		public static unsafe TResult Invoke_SS<[DynamicallyAccessedMembers (Constructors)] TPeer, T0, TResult> (IntPtr jnienv, IntPtr self, T0 p0, delegate* managed<TPeer, T0, TResult> body)
			where TPeer : class, IJavaObject
			where T0 : unmanaged
			where TResult : unmanaged
		{
			AndroidRuntimeInternal.WaitForBridgeProcessing ();

			if (!JniEnvironment.BeginMarshalMethod (jnienv, out var __envp, out var __r))
				return default;

			try {
				var __this = global::Java.Lang.Object.GetObject<TPeer> (self, JniHandleOwnership.DoNotTransfer);
				if (__this is null)
					throw new NullReferenceException (PeerLookupFailed);
				return body (__this, p0);
			} catch (Exception __e) {
				__r.OnUserUnhandledException (ref __envp, __e);
				return default;
			} finally {
				JniEnvironment.EndMarshalMethod (ref __envp);
			}
		}

		[DebuggerDisableUserUnhandledExceptions]
		public static unsafe IntPtr Invoke_SO<[DynamicallyAccessedMembers (Constructors)] TPeer, T0> (IntPtr jnienv, IntPtr self, T0 p0, delegate* managed<TPeer, T0, IJavaObject?> body)
			where TPeer : class, IJavaObject
			where T0 : unmanaged
		{
			AndroidRuntimeInternal.WaitForBridgeProcessing ();

			if (!JniEnvironment.BeginMarshalMethod (jnienv, out var __envp, out var __r))
				return default;

			try {
				var __this = global::Java.Lang.Object.GetObject<TPeer> (self, JniHandleOwnership.DoNotTransfer);
				if (__this is null)
					throw new NullReferenceException (PeerLookupFailed);
				return JNIEnv.ToLocalJniHandle (body (__this, p0));
			} catch (Exception __e) {
				__r.OnUserUnhandledException (ref __envp, __e);
				return default;
			} finally {
				JniEnvironment.EndMarshalMethod (ref __envp);
			}
		}

		[DebuggerDisableUserUnhandledExceptions]
		public static unsafe void Invoke_OX<[DynamicallyAccessedMembers (Constructors)] TPeer, [DynamicallyAccessedMembers (Constructors)] T0> (IntPtr jnienv, IntPtr self, IntPtr native_p0, delegate* managed<TPeer, T0?, void> body)
			where TPeer : class, IJavaObject
			where T0 : class, IJavaObject
		{
			AndroidRuntimeInternal.WaitForBridgeProcessing ();

			if (!JniEnvironment.BeginMarshalMethod (jnienv, out var __envp, out var __r))
				return;

			try {
				var __this = global::Java.Lang.Object.GetObject<TPeer> (self, JniHandleOwnership.DoNotTransfer);
				if (__this is null)
					throw new NullReferenceException (PeerLookupFailed);
				var p0 = global::Java.Lang.Object.GetObject<T0> (native_p0, JniHandleOwnership.DoNotTransfer);
				body (__this, p0);
			} catch (Exception __e) {
				__r.OnUserUnhandledException (ref __envp, __e);
				return;
			} finally {
				JniEnvironment.EndMarshalMethod (ref __envp);
			}
		}

		[DebuggerDisableUserUnhandledExceptions]
		public static unsafe TResult Invoke_OS<[DynamicallyAccessedMembers (Constructors)] TPeer, [DynamicallyAccessedMembers (Constructors)] T0, TResult> (IntPtr jnienv, IntPtr self, IntPtr native_p0, delegate* managed<TPeer, T0?, TResult> body)
			where TPeer : class, IJavaObject
			where T0 : class, IJavaObject
			where TResult : unmanaged
		{
			AndroidRuntimeInternal.WaitForBridgeProcessing ();

			if (!JniEnvironment.BeginMarshalMethod (jnienv, out var __envp, out var __r))
				return default;

			try {
				var __this = global::Java.Lang.Object.GetObject<TPeer> (self, JniHandleOwnership.DoNotTransfer);
				if (__this is null)
					throw new NullReferenceException (PeerLookupFailed);
				var p0 = global::Java.Lang.Object.GetObject<T0> (native_p0, JniHandleOwnership.DoNotTransfer);
				return body (__this, p0);
			} catch (Exception __e) {
				__r.OnUserUnhandledException (ref __envp, __e);
				return default;
			} finally {
				JniEnvironment.EndMarshalMethod (ref __envp);
			}
		}

		[DebuggerDisableUserUnhandledExceptions]
		public static unsafe IntPtr Invoke_OO<[DynamicallyAccessedMembers (Constructors)] TPeer, [DynamicallyAccessedMembers (Constructors)] T0> (IntPtr jnienv, IntPtr self, IntPtr native_p0, delegate* managed<TPeer, T0?, IJavaObject?> body)
			where TPeer : class, IJavaObject
			where T0 : class, IJavaObject
		{
			AndroidRuntimeInternal.WaitForBridgeProcessing ();

			if (!JniEnvironment.BeginMarshalMethod (jnienv, out var __envp, out var __r))
				return default;

			try {
				var __this = global::Java.Lang.Object.GetObject<TPeer> (self, JniHandleOwnership.DoNotTransfer);
				if (__this is null)
					throw new NullReferenceException (PeerLookupFailed);
				var p0 = global::Java.Lang.Object.GetObject<T0> (native_p0, JniHandleOwnership.DoNotTransfer);
				return JNIEnv.ToLocalJniHandle (body (__this, p0));
			} catch (Exception __e) {
				__r.OnUserUnhandledException (ref __envp, __e);
				return default;
			} finally {
				JniEnvironment.EndMarshalMethod (ref __envp);
			}
		}

		[DebuggerDisableUserUnhandledExceptions]
		public static unsafe void Invoke_SSX<[DynamicallyAccessedMembers (Constructors)] TPeer, T0, T1> (IntPtr jnienv, IntPtr self, T0 p0, T1 p1, delegate* managed<TPeer, T0, T1, void> body)
			where TPeer : class, IJavaObject
			where T0 : unmanaged
			where T1 : unmanaged
		{
			AndroidRuntimeInternal.WaitForBridgeProcessing ();

			if (!JniEnvironment.BeginMarshalMethod (jnienv, out var __envp, out var __r))
				return;

			try {
				var __this = global::Java.Lang.Object.GetObject<TPeer> (self, JniHandleOwnership.DoNotTransfer);
				if (__this is null)
					throw new NullReferenceException (PeerLookupFailed);
				body (__this, p0, p1);
			} catch (Exception __e) {
				__r.OnUserUnhandledException (ref __envp, __e);
				return;
			} finally {
				JniEnvironment.EndMarshalMethod (ref __envp);
			}
		}

		[DebuggerDisableUserUnhandledExceptions]
		public static unsafe TResult Invoke_SSS<[DynamicallyAccessedMembers (Constructors)] TPeer, T0, T1, TResult> (IntPtr jnienv, IntPtr self, T0 p0, T1 p1, delegate* managed<TPeer, T0, T1, TResult> body)
			where TPeer : class, IJavaObject
			where T0 : unmanaged
			where T1 : unmanaged
			where TResult : unmanaged
		{
			AndroidRuntimeInternal.WaitForBridgeProcessing ();

			if (!JniEnvironment.BeginMarshalMethod (jnienv, out var __envp, out var __r))
				return default;

			try {
				var __this = global::Java.Lang.Object.GetObject<TPeer> (self, JniHandleOwnership.DoNotTransfer);
				if (__this is null)
					throw new NullReferenceException (PeerLookupFailed);
				return body (__this, p0, p1);
			} catch (Exception __e) {
				__r.OnUserUnhandledException (ref __envp, __e);
				return default;
			} finally {
				JniEnvironment.EndMarshalMethod (ref __envp);
			}
		}

		[DebuggerDisableUserUnhandledExceptions]
		public static unsafe IntPtr Invoke_SSO<[DynamicallyAccessedMembers (Constructors)] TPeer, T0, T1> (IntPtr jnienv, IntPtr self, T0 p0, T1 p1, delegate* managed<TPeer, T0, T1, IJavaObject?> body)
			where TPeer : class, IJavaObject
			where T0 : unmanaged
			where T1 : unmanaged
		{
			AndroidRuntimeInternal.WaitForBridgeProcessing ();

			if (!JniEnvironment.BeginMarshalMethod (jnienv, out var __envp, out var __r))
				return default;

			try {
				var __this = global::Java.Lang.Object.GetObject<TPeer> (self, JniHandleOwnership.DoNotTransfer);
				if (__this is null)
					throw new NullReferenceException (PeerLookupFailed);
				return JNIEnv.ToLocalJniHandle (body (__this, p0, p1));
			} catch (Exception __e) {
				__r.OnUserUnhandledException (ref __envp, __e);
				return default;
			} finally {
				JniEnvironment.EndMarshalMethod (ref __envp);
			}
		}

		[DebuggerDisableUserUnhandledExceptions]
		public static unsafe void Invoke_OSX<[DynamicallyAccessedMembers (Constructors)] TPeer, [DynamicallyAccessedMembers (Constructors)] T0, T1> (IntPtr jnienv, IntPtr self, IntPtr native_p0, T1 p1, delegate* managed<TPeer, T0?, T1, void> body)
			where TPeer : class, IJavaObject
			where T0 : class, IJavaObject
			where T1 : unmanaged
		{
			AndroidRuntimeInternal.WaitForBridgeProcessing ();

			if (!JniEnvironment.BeginMarshalMethod (jnienv, out var __envp, out var __r))
				return;

			try {
				var __this = global::Java.Lang.Object.GetObject<TPeer> (self, JniHandleOwnership.DoNotTransfer);
				if (__this is null)
					throw new NullReferenceException (PeerLookupFailed);
				var p0 = global::Java.Lang.Object.GetObject<T0> (native_p0, JniHandleOwnership.DoNotTransfer);
				body (__this, p0, p1);
			} catch (Exception __e) {
				__r.OnUserUnhandledException (ref __envp, __e);
				return;
			} finally {
				JniEnvironment.EndMarshalMethod (ref __envp);
			}
		}

		[DebuggerDisableUserUnhandledExceptions]
		public static unsafe TResult Invoke_OSS<[DynamicallyAccessedMembers (Constructors)] TPeer, [DynamicallyAccessedMembers (Constructors)] T0, T1, TResult> (IntPtr jnienv, IntPtr self, IntPtr native_p0, T1 p1, delegate* managed<TPeer, T0?, T1, TResult> body)
			where TPeer : class, IJavaObject
			where T0 : class, IJavaObject
			where T1 : unmanaged
			where TResult : unmanaged
		{
			AndroidRuntimeInternal.WaitForBridgeProcessing ();

			if (!JniEnvironment.BeginMarshalMethod (jnienv, out var __envp, out var __r))
				return default;

			try {
				var __this = global::Java.Lang.Object.GetObject<TPeer> (self, JniHandleOwnership.DoNotTransfer);
				if (__this is null)
					throw new NullReferenceException (PeerLookupFailed);
				var p0 = global::Java.Lang.Object.GetObject<T0> (native_p0, JniHandleOwnership.DoNotTransfer);
				return body (__this, p0, p1);
			} catch (Exception __e) {
				__r.OnUserUnhandledException (ref __envp, __e);
				return default;
			} finally {
				JniEnvironment.EndMarshalMethod (ref __envp);
			}
		}

		[DebuggerDisableUserUnhandledExceptions]
		public static unsafe IntPtr Invoke_OSO<[DynamicallyAccessedMembers (Constructors)] TPeer, [DynamicallyAccessedMembers (Constructors)] T0, T1> (IntPtr jnienv, IntPtr self, IntPtr native_p0, T1 p1, delegate* managed<TPeer, T0?, T1, IJavaObject?> body)
			where TPeer : class, IJavaObject
			where T0 : class, IJavaObject
			where T1 : unmanaged
		{
			AndroidRuntimeInternal.WaitForBridgeProcessing ();

			if (!JniEnvironment.BeginMarshalMethod (jnienv, out var __envp, out var __r))
				return default;

			try {
				var __this = global::Java.Lang.Object.GetObject<TPeer> (self, JniHandleOwnership.DoNotTransfer);
				if (__this is null)
					throw new NullReferenceException (PeerLookupFailed);
				var p0 = global::Java.Lang.Object.GetObject<T0> (native_p0, JniHandleOwnership.DoNotTransfer);
				return JNIEnv.ToLocalJniHandle (body (__this, p0, p1));
			} catch (Exception __e) {
				__r.OnUserUnhandledException (ref __envp, __e);
				return default;
			} finally {
				JniEnvironment.EndMarshalMethod (ref __envp);
			}
		}

		[DebuggerDisableUserUnhandledExceptions]
		public static unsafe void Invoke_SOX<[DynamicallyAccessedMembers (Constructors)] TPeer, T0, [DynamicallyAccessedMembers (Constructors)] T1> (IntPtr jnienv, IntPtr self, T0 p0, IntPtr native_p1, delegate* managed<TPeer, T0, T1?, void> body)
			where TPeer : class, IJavaObject
			where T0 : unmanaged
			where T1 : class, IJavaObject
		{
			AndroidRuntimeInternal.WaitForBridgeProcessing ();

			if (!JniEnvironment.BeginMarshalMethod (jnienv, out var __envp, out var __r))
				return;

			try {
				var __this = global::Java.Lang.Object.GetObject<TPeer> (self, JniHandleOwnership.DoNotTransfer);
				if (__this is null)
					throw new NullReferenceException (PeerLookupFailed);
				var p1 = global::Java.Lang.Object.GetObject<T1> (native_p1, JniHandleOwnership.DoNotTransfer);
				body (__this, p0, p1);
			} catch (Exception __e) {
				__r.OnUserUnhandledException (ref __envp, __e);
				return;
			} finally {
				JniEnvironment.EndMarshalMethod (ref __envp);
			}
		}

		[DebuggerDisableUserUnhandledExceptions]
		public static unsafe TResult Invoke_SOS<[DynamicallyAccessedMembers (Constructors)] TPeer, T0, [DynamicallyAccessedMembers (Constructors)] T1, TResult> (IntPtr jnienv, IntPtr self, T0 p0, IntPtr native_p1, delegate* managed<TPeer, T0, T1?, TResult> body)
			where TPeer : class, IJavaObject
			where T0 : unmanaged
			where T1 : class, IJavaObject
			where TResult : unmanaged
		{
			AndroidRuntimeInternal.WaitForBridgeProcessing ();

			if (!JniEnvironment.BeginMarshalMethod (jnienv, out var __envp, out var __r))
				return default;

			try {
				var __this = global::Java.Lang.Object.GetObject<TPeer> (self, JniHandleOwnership.DoNotTransfer);
				if (__this is null)
					throw new NullReferenceException (PeerLookupFailed);
				var p1 = global::Java.Lang.Object.GetObject<T1> (native_p1, JniHandleOwnership.DoNotTransfer);
				return body (__this, p0, p1);
			} catch (Exception __e) {
				__r.OnUserUnhandledException (ref __envp, __e);
				return default;
			} finally {
				JniEnvironment.EndMarshalMethod (ref __envp);
			}
		}

		[DebuggerDisableUserUnhandledExceptions]
		public static unsafe IntPtr Invoke_SOO<[DynamicallyAccessedMembers (Constructors)] TPeer, T0, [DynamicallyAccessedMembers (Constructors)] T1> (IntPtr jnienv, IntPtr self, T0 p0, IntPtr native_p1, delegate* managed<TPeer, T0, T1?, IJavaObject?> body)
			where TPeer : class, IJavaObject
			where T0 : unmanaged
			where T1 : class, IJavaObject
		{
			AndroidRuntimeInternal.WaitForBridgeProcessing ();

			if (!JniEnvironment.BeginMarshalMethod (jnienv, out var __envp, out var __r))
				return default;

			try {
				var __this = global::Java.Lang.Object.GetObject<TPeer> (self, JniHandleOwnership.DoNotTransfer);
				if (__this is null)
					throw new NullReferenceException (PeerLookupFailed);
				var p1 = global::Java.Lang.Object.GetObject<T1> (native_p1, JniHandleOwnership.DoNotTransfer);
				return JNIEnv.ToLocalJniHandle (body (__this, p0, p1));
			} catch (Exception __e) {
				__r.OnUserUnhandledException (ref __envp, __e);
				return default;
			} finally {
				JniEnvironment.EndMarshalMethod (ref __envp);
			}
		}

		[DebuggerDisableUserUnhandledExceptions]
		public static unsafe void Invoke_OOX<[DynamicallyAccessedMembers (Constructors)] TPeer, [DynamicallyAccessedMembers (Constructors)] T0, [DynamicallyAccessedMembers (Constructors)] T1> (IntPtr jnienv, IntPtr self, IntPtr native_p0, IntPtr native_p1, delegate* managed<TPeer, T0?, T1?, void> body)
			where TPeer : class, IJavaObject
			where T0 : class, IJavaObject
			where T1 : class, IJavaObject
		{
			AndroidRuntimeInternal.WaitForBridgeProcessing ();

			if (!JniEnvironment.BeginMarshalMethod (jnienv, out var __envp, out var __r))
				return;

			try {
				var __this = global::Java.Lang.Object.GetObject<TPeer> (self, JniHandleOwnership.DoNotTransfer);
				if (__this is null)
					throw new NullReferenceException (PeerLookupFailed);
				var p0 = global::Java.Lang.Object.GetObject<T0> (native_p0, JniHandleOwnership.DoNotTransfer);
				var p1 = global::Java.Lang.Object.GetObject<T1> (native_p1, JniHandleOwnership.DoNotTransfer);
				body (__this, p0, p1);
			} catch (Exception __e) {
				__r.OnUserUnhandledException (ref __envp, __e);
				return;
			} finally {
				JniEnvironment.EndMarshalMethod (ref __envp);
			}
		}

		[DebuggerDisableUserUnhandledExceptions]
		public static unsafe TResult Invoke_OOS<[DynamicallyAccessedMembers (Constructors)] TPeer, [DynamicallyAccessedMembers (Constructors)] T0, [DynamicallyAccessedMembers (Constructors)] T1, TResult> (IntPtr jnienv, IntPtr self, IntPtr native_p0, IntPtr native_p1, delegate* managed<TPeer, T0?, T1?, TResult> body)
			where TPeer : class, IJavaObject
			where T0 : class, IJavaObject
			where T1 : class, IJavaObject
			where TResult : unmanaged
		{
			AndroidRuntimeInternal.WaitForBridgeProcessing ();

			if (!JniEnvironment.BeginMarshalMethod (jnienv, out var __envp, out var __r))
				return default;

			try {
				var __this = global::Java.Lang.Object.GetObject<TPeer> (self, JniHandleOwnership.DoNotTransfer);
				if (__this is null)
					throw new NullReferenceException (PeerLookupFailed);
				var p0 = global::Java.Lang.Object.GetObject<T0> (native_p0, JniHandleOwnership.DoNotTransfer);
				var p1 = global::Java.Lang.Object.GetObject<T1> (native_p1, JniHandleOwnership.DoNotTransfer);
				return body (__this, p0, p1);
			} catch (Exception __e) {
				__r.OnUserUnhandledException (ref __envp, __e);
				return default;
			} finally {
				JniEnvironment.EndMarshalMethod (ref __envp);
			}
		}

		[DebuggerDisableUserUnhandledExceptions]
		public static unsafe IntPtr Invoke_OOO<[DynamicallyAccessedMembers (Constructors)] TPeer, [DynamicallyAccessedMembers (Constructors)] T0, [DynamicallyAccessedMembers (Constructors)] T1> (IntPtr jnienv, IntPtr self, IntPtr native_p0, IntPtr native_p1, delegate* managed<TPeer, T0?, T1?, IJavaObject?> body)
			where TPeer : class, IJavaObject
			where T0 : class, IJavaObject
			where T1 : class, IJavaObject
		{
			AndroidRuntimeInternal.WaitForBridgeProcessing ();

			if (!JniEnvironment.BeginMarshalMethod (jnienv, out var __envp, out var __r))
				return default;

			try {
				var __this = global::Java.Lang.Object.GetObject<TPeer> (self, JniHandleOwnership.DoNotTransfer);
				if (__this is null)
					throw new NullReferenceException (PeerLookupFailed);
				var p0 = global::Java.Lang.Object.GetObject<T0> (native_p0, JniHandleOwnership.DoNotTransfer);
				var p1 = global::Java.Lang.Object.GetObject<T1> (native_p1, JniHandleOwnership.DoNotTransfer);
				return JNIEnv.ToLocalJniHandle (body (__this, p0, p1));
			} catch (Exception __e) {
				__r.OnUserUnhandledException (ref __envp, __e);
				return default;
			} finally {
				JniEnvironment.EndMarshalMethod (ref __envp);
			}
		}

		[DebuggerDisableUserUnhandledExceptions]
		public static unsafe void Invoke_SSSX<[DynamicallyAccessedMembers (Constructors)] TPeer, T0, T1, T2> (IntPtr jnienv, IntPtr self, T0 p0, T1 p1, T2 p2, delegate* managed<TPeer, T0, T1, T2, void> body)
			where TPeer : class, IJavaObject
			where T0 : unmanaged
			where T1 : unmanaged
			where T2 : unmanaged
		{
			AndroidRuntimeInternal.WaitForBridgeProcessing ();

			if (!JniEnvironment.BeginMarshalMethod (jnienv, out var __envp, out var __r))
				return;

			try {
				var __this = global::Java.Lang.Object.GetObject<TPeer> (self, JniHandleOwnership.DoNotTransfer);
				if (__this is null)
					throw new NullReferenceException (PeerLookupFailed);
				body (__this, p0, p1, p2);
			} catch (Exception __e) {
				__r.OnUserUnhandledException (ref __envp, __e);
				return;
			} finally {
				JniEnvironment.EndMarshalMethod (ref __envp);
			}
		}

		[DebuggerDisableUserUnhandledExceptions]
		public static unsafe TResult Invoke_SSSS<[DynamicallyAccessedMembers (Constructors)] TPeer, T0, T1, T2, TResult> (IntPtr jnienv, IntPtr self, T0 p0, T1 p1, T2 p2, delegate* managed<TPeer, T0, T1, T2, TResult> body)
			where TPeer : class, IJavaObject
			where T0 : unmanaged
			where T1 : unmanaged
			where T2 : unmanaged
			where TResult : unmanaged
		{
			AndroidRuntimeInternal.WaitForBridgeProcessing ();

			if (!JniEnvironment.BeginMarshalMethod (jnienv, out var __envp, out var __r))
				return default;

			try {
				var __this = global::Java.Lang.Object.GetObject<TPeer> (self, JniHandleOwnership.DoNotTransfer);
				if (__this is null)
					throw new NullReferenceException (PeerLookupFailed);
				return body (__this, p0, p1, p2);
			} catch (Exception __e) {
				__r.OnUserUnhandledException (ref __envp, __e);
				return default;
			} finally {
				JniEnvironment.EndMarshalMethod (ref __envp);
			}
		}

		[DebuggerDisableUserUnhandledExceptions]
		public static unsafe IntPtr Invoke_SSSO<[DynamicallyAccessedMembers (Constructors)] TPeer, T0, T1, T2> (IntPtr jnienv, IntPtr self, T0 p0, T1 p1, T2 p2, delegate* managed<TPeer, T0, T1, T2, IJavaObject?> body)
			where TPeer : class, IJavaObject
			where T0 : unmanaged
			where T1 : unmanaged
			where T2 : unmanaged
		{
			AndroidRuntimeInternal.WaitForBridgeProcessing ();

			if (!JniEnvironment.BeginMarshalMethod (jnienv, out var __envp, out var __r))
				return default;

			try {
				var __this = global::Java.Lang.Object.GetObject<TPeer> (self, JniHandleOwnership.DoNotTransfer);
				if (__this is null)
					throw new NullReferenceException (PeerLookupFailed);
				return JNIEnv.ToLocalJniHandle (body (__this, p0, p1, p2));
			} catch (Exception __e) {
				__r.OnUserUnhandledException (ref __envp, __e);
				return default;
			} finally {
				JniEnvironment.EndMarshalMethod (ref __envp);
			}
		}

		[DebuggerDisableUserUnhandledExceptions]
		public static unsafe void Invoke_OSSX<[DynamicallyAccessedMembers (Constructors)] TPeer, [DynamicallyAccessedMembers (Constructors)] T0, T1, T2> (IntPtr jnienv, IntPtr self, IntPtr native_p0, T1 p1, T2 p2, delegate* managed<TPeer, T0?, T1, T2, void> body)
			where TPeer : class, IJavaObject
			where T0 : class, IJavaObject
			where T1 : unmanaged
			where T2 : unmanaged
		{
			AndroidRuntimeInternal.WaitForBridgeProcessing ();

			if (!JniEnvironment.BeginMarshalMethod (jnienv, out var __envp, out var __r))
				return;

			try {
				var __this = global::Java.Lang.Object.GetObject<TPeer> (self, JniHandleOwnership.DoNotTransfer);
				if (__this is null)
					throw new NullReferenceException (PeerLookupFailed);
				var p0 = global::Java.Lang.Object.GetObject<T0> (native_p0, JniHandleOwnership.DoNotTransfer);
				body (__this, p0, p1, p2);
			} catch (Exception __e) {
				__r.OnUserUnhandledException (ref __envp, __e);
				return;
			} finally {
				JniEnvironment.EndMarshalMethod (ref __envp);
			}
		}

		[DebuggerDisableUserUnhandledExceptions]
		public static unsafe TResult Invoke_OSSS<[DynamicallyAccessedMembers (Constructors)] TPeer, [DynamicallyAccessedMembers (Constructors)] T0, T1, T2, TResult> (IntPtr jnienv, IntPtr self, IntPtr native_p0, T1 p1, T2 p2, delegate* managed<TPeer, T0?, T1, T2, TResult> body)
			where TPeer : class, IJavaObject
			where T0 : class, IJavaObject
			where T1 : unmanaged
			where T2 : unmanaged
			where TResult : unmanaged
		{
			AndroidRuntimeInternal.WaitForBridgeProcessing ();

			if (!JniEnvironment.BeginMarshalMethod (jnienv, out var __envp, out var __r))
				return default;

			try {
				var __this = global::Java.Lang.Object.GetObject<TPeer> (self, JniHandleOwnership.DoNotTransfer);
				if (__this is null)
					throw new NullReferenceException (PeerLookupFailed);
				var p0 = global::Java.Lang.Object.GetObject<T0> (native_p0, JniHandleOwnership.DoNotTransfer);
				return body (__this, p0, p1, p2);
			} catch (Exception __e) {
				__r.OnUserUnhandledException (ref __envp, __e);
				return default;
			} finally {
				JniEnvironment.EndMarshalMethod (ref __envp);
			}
		}

		[DebuggerDisableUserUnhandledExceptions]
		public static unsafe IntPtr Invoke_OSSO<[DynamicallyAccessedMembers (Constructors)] TPeer, [DynamicallyAccessedMembers (Constructors)] T0, T1, T2> (IntPtr jnienv, IntPtr self, IntPtr native_p0, T1 p1, T2 p2, delegate* managed<TPeer, T0?, T1, T2, IJavaObject?> body)
			where TPeer : class, IJavaObject
			where T0 : class, IJavaObject
			where T1 : unmanaged
			where T2 : unmanaged
		{
			AndroidRuntimeInternal.WaitForBridgeProcessing ();

			if (!JniEnvironment.BeginMarshalMethod (jnienv, out var __envp, out var __r))
				return default;

			try {
				var __this = global::Java.Lang.Object.GetObject<TPeer> (self, JniHandleOwnership.DoNotTransfer);
				if (__this is null)
					throw new NullReferenceException (PeerLookupFailed);
				var p0 = global::Java.Lang.Object.GetObject<T0> (native_p0, JniHandleOwnership.DoNotTransfer);
				return JNIEnv.ToLocalJniHandle (body (__this, p0, p1, p2));
			} catch (Exception __e) {
				__r.OnUserUnhandledException (ref __envp, __e);
				return default;
			} finally {
				JniEnvironment.EndMarshalMethod (ref __envp);
			}
		}

		[DebuggerDisableUserUnhandledExceptions]
		public static unsafe void Invoke_SOSX<[DynamicallyAccessedMembers (Constructors)] TPeer, T0, [DynamicallyAccessedMembers (Constructors)] T1, T2> (IntPtr jnienv, IntPtr self, T0 p0, IntPtr native_p1, T2 p2, delegate* managed<TPeer, T0, T1?, T2, void> body)
			where TPeer : class, IJavaObject
			where T0 : unmanaged
			where T1 : class, IJavaObject
			where T2 : unmanaged
		{
			AndroidRuntimeInternal.WaitForBridgeProcessing ();

			if (!JniEnvironment.BeginMarshalMethod (jnienv, out var __envp, out var __r))
				return;

			try {
				var __this = global::Java.Lang.Object.GetObject<TPeer> (self, JniHandleOwnership.DoNotTransfer);
				if (__this is null)
					throw new NullReferenceException (PeerLookupFailed);
				var p1 = global::Java.Lang.Object.GetObject<T1> (native_p1, JniHandleOwnership.DoNotTransfer);
				body (__this, p0, p1, p2);
			} catch (Exception __e) {
				__r.OnUserUnhandledException (ref __envp, __e);
				return;
			} finally {
				JniEnvironment.EndMarshalMethod (ref __envp);
			}
		}

		[DebuggerDisableUserUnhandledExceptions]
		public static unsafe TResult Invoke_SOSS<[DynamicallyAccessedMembers (Constructors)] TPeer, T0, [DynamicallyAccessedMembers (Constructors)] T1, T2, TResult> (IntPtr jnienv, IntPtr self, T0 p0, IntPtr native_p1, T2 p2, delegate* managed<TPeer, T0, T1?, T2, TResult> body)
			where TPeer : class, IJavaObject
			where T0 : unmanaged
			where T1 : class, IJavaObject
			where T2 : unmanaged
			where TResult : unmanaged
		{
			AndroidRuntimeInternal.WaitForBridgeProcessing ();

			if (!JniEnvironment.BeginMarshalMethod (jnienv, out var __envp, out var __r))
				return default;

			try {
				var __this = global::Java.Lang.Object.GetObject<TPeer> (self, JniHandleOwnership.DoNotTransfer);
				if (__this is null)
					throw new NullReferenceException (PeerLookupFailed);
				var p1 = global::Java.Lang.Object.GetObject<T1> (native_p1, JniHandleOwnership.DoNotTransfer);
				return body (__this, p0, p1, p2);
			} catch (Exception __e) {
				__r.OnUserUnhandledException (ref __envp, __e);
				return default;
			} finally {
				JniEnvironment.EndMarshalMethod (ref __envp);
			}
		}

		[DebuggerDisableUserUnhandledExceptions]
		public static unsafe IntPtr Invoke_SOSO<[DynamicallyAccessedMembers (Constructors)] TPeer, T0, [DynamicallyAccessedMembers (Constructors)] T1, T2> (IntPtr jnienv, IntPtr self, T0 p0, IntPtr native_p1, T2 p2, delegate* managed<TPeer, T0, T1?, T2, IJavaObject?> body)
			where TPeer : class, IJavaObject
			where T0 : unmanaged
			where T1 : class, IJavaObject
			where T2 : unmanaged
		{
			AndroidRuntimeInternal.WaitForBridgeProcessing ();

			if (!JniEnvironment.BeginMarshalMethod (jnienv, out var __envp, out var __r))
				return default;

			try {
				var __this = global::Java.Lang.Object.GetObject<TPeer> (self, JniHandleOwnership.DoNotTransfer);
				if (__this is null)
					throw new NullReferenceException (PeerLookupFailed);
				var p1 = global::Java.Lang.Object.GetObject<T1> (native_p1, JniHandleOwnership.DoNotTransfer);
				return JNIEnv.ToLocalJniHandle (body (__this, p0, p1, p2));
			} catch (Exception __e) {
				__r.OnUserUnhandledException (ref __envp, __e);
				return default;
			} finally {
				JniEnvironment.EndMarshalMethod (ref __envp);
			}
		}

		[DebuggerDisableUserUnhandledExceptions]
		public static unsafe void Invoke_OOSX<[DynamicallyAccessedMembers (Constructors)] TPeer, [DynamicallyAccessedMembers (Constructors)] T0, [DynamicallyAccessedMembers (Constructors)] T1, T2> (IntPtr jnienv, IntPtr self, IntPtr native_p0, IntPtr native_p1, T2 p2, delegate* managed<TPeer, T0?, T1?, T2, void> body)
			where TPeer : class, IJavaObject
			where T0 : class, IJavaObject
			where T1 : class, IJavaObject
			where T2 : unmanaged
		{
			AndroidRuntimeInternal.WaitForBridgeProcessing ();

			if (!JniEnvironment.BeginMarshalMethod (jnienv, out var __envp, out var __r))
				return;

			try {
				var __this = global::Java.Lang.Object.GetObject<TPeer> (self, JniHandleOwnership.DoNotTransfer);
				if (__this is null)
					throw new NullReferenceException (PeerLookupFailed);
				var p0 = global::Java.Lang.Object.GetObject<T0> (native_p0, JniHandleOwnership.DoNotTransfer);
				var p1 = global::Java.Lang.Object.GetObject<T1> (native_p1, JniHandleOwnership.DoNotTransfer);
				body (__this, p0, p1, p2);
			} catch (Exception __e) {
				__r.OnUserUnhandledException (ref __envp, __e);
				return;
			} finally {
				JniEnvironment.EndMarshalMethod (ref __envp);
			}
		}

		[DebuggerDisableUserUnhandledExceptions]
		public static unsafe TResult Invoke_OOSS<[DynamicallyAccessedMembers (Constructors)] TPeer, [DynamicallyAccessedMembers (Constructors)] T0, [DynamicallyAccessedMembers (Constructors)] T1, T2, TResult> (IntPtr jnienv, IntPtr self, IntPtr native_p0, IntPtr native_p1, T2 p2, delegate* managed<TPeer, T0?, T1?, T2, TResult> body)
			where TPeer : class, IJavaObject
			where T0 : class, IJavaObject
			where T1 : class, IJavaObject
			where T2 : unmanaged
			where TResult : unmanaged
		{
			AndroidRuntimeInternal.WaitForBridgeProcessing ();

			if (!JniEnvironment.BeginMarshalMethod (jnienv, out var __envp, out var __r))
				return default;

			try {
				var __this = global::Java.Lang.Object.GetObject<TPeer> (self, JniHandleOwnership.DoNotTransfer);
				if (__this is null)
					throw new NullReferenceException (PeerLookupFailed);
				var p0 = global::Java.Lang.Object.GetObject<T0> (native_p0, JniHandleOwnership.DoNotTransfer);
				var p1 = global::Java.Lang.Object.GetObject<T1> (native_p1, JniHandleOwnership.DoNotTransfer);
				return body (__this, p0, p1, p2);
			} catch (Exception __e) {
				__r.OnUserUnhandledException (ref __envp, __e);
				return default;
			} finally {
				JniEnvironment.EndMarshalMethod (ref __envp);
			}
		}

		[DebuggerDisableUserUnhandledExceptions]
		public static unsafe IntPtr Invoke_OOSO<[DynamicallyAccessedMembers (Constructors)] TPeer, [DynamicallyAccessedMembers (Constructors)] T0, [DynamicallyAccessedMembers (Constructors)] T1, T2> (IntPtr jnienv, IntPtr self, IntPtr native_p0, IntPtr native_p1, T2 p2, delegate* managed<TPeer, T0?, T1?, T2, IJavaObject?> body)
			where TPeer : class, IJavaObject
			where T0 : class, IJavaObject
			where T1 : class, IJavaObject
			where T2 : unmanaged
		{
			AndroidRuntimeInternal.WaitForBridgeProcessing ();

			if (!JniEnvironment.BeginMarshalMethod (jnienv, out var __envp, out var __r))
				return default;

			try {
				var __this = global::Java.Lang.Object.GetObject<TPeer> (self, JniHandleOwnership.DoNotTransfer);
				if (__this is null)
					throw new NullReferenceException (PeerLookupFailed);
				var p0 = global::Java.Lang.Object.GetObject<T0> (native_p0, JniHandleOwnership.DoNotTransfer);
				var p1 = global::Java.Lang.Object.GetObject<T1> (native_p1, JniHandleOwnership.DoNotTransfer);
				return JNIEnv.ToLocalJniHandle (body (__this, p0, p1, p2));
			} catch (Exception __e) {
				__r.OnUserUnhandledException (ref __envp, __e);
				return default;
			} finally {
				JniEnvironment.EndMarshalMethod (ref __envp);
			}
		}

		[DebuggerDisableUserUnhandledExceptions]
		public static unsafe void Invoke_SSOX<[DynamicallyAccessedMembers (Constructors)] TPeer, T0, T1, [DynamicallyAccessedMembers (Constructors)] T2> (IntPtr jnienv, IntPtr self, T0 p0, T1 p1, IntPtr native_p2, delegate* managed<TPeer, T0, T1, T2?, void> body)
			where TPeer : class, IJavaObject
			where T0 : unmanaged
			where T1 : unmanaged
			where T2 : class, IJavaObject
		{
			AndroidRuntimeInternal.WaitForBridgeProcessing ();

			if (!JniEnvironment.BeginMarshalMethod (jnienv, out var __envp, out var __r))
				return;

			try {
				var __this = global::Java.Lang.Object.GetObject<TPeer> (self, JniHandleOwnership.DoNotTransfer);
				if (__this is null)
					throw new NullReferenceException (PeerLookupFailed);
				var p2 = global::Java.Lang.Object.GetObject<T2> (native_p2, JniHandleOwnership.DoNotTransfer);
				body (__this, p0, p1, p2);
			} catch (Exception __e) {
				__r.OnUserUnhandledException (ref __envp, __e);
				return;
			} finally {
				JniEnvironment.EndMarshalMethod (ref __envp);
			}
		}

		[DebuggerDisableUserUnhandledExceptions]
		public static unsafe TResult Invoke_SSOS<[DynamicallyAccessedMembers (Constructors)] TPeer, T0, T1, [DynamicallyAccessedMembers (Constructors)] T2, TResult> (IntPtr jnienv, IntPtr self, T0 p0, T1 p1, IntPtr native_p2, delegate* managed<TPeer, T0, T1, T2?, TResult> body)
			where TPeer : class, IJavaObject
			where T0 : unmanaged
			where T1 : unmanaged
			where T2 : class, IJavaObject
			where TResult : unmanaged
		{
			AndroidRuntimeInternal.WaitForBridgeProcessing ();

			if (!JniEnvironment.BeginMarshalMethod (jnienv, out var __envp, out var __r))
				return default;

			try {
				var __this = global::Java.Lang.Object.GetObject<TPeer> (self, JniHandleOwnership.DoNotTransfer);
				if (__this is null)
					throw new NullReferenceException (PeerLookupFailed);
				var p2 = global::Java.Lang.Object.GetObject<T2> (native_p2, JniHandleOwnership.DoNotTransfer);
				return body (__this, p0, p1, p2);
			} catch (Exception __e) {
				__r.OnUserUnhandledException (ref __envp, __e);
				return default;
			} finally {
				JniEnvironment.EndMarshalMethod (ref __envp);
			}
		}

		[DebuggerDisableUserUnhandledExceptions]
		public static unsafe IntPtr Invoke_SSOO<[DynamicallyAccessedMembers (Constructors)] TPeer, T0, T1, [DynamicallyAccessedMembers (Constructors)] T2> (IntPtr jnienv, IntPtr self, T0 p0, T1 p1, IntPtr native_p2, delegate* managed<TPeer, T0, T1, T2?, IJavaObject?> body)
			where TPeer : class, IJavaObject
			where T0 : unmanaged
			where T1 : unmanaged
			where T2 : class, IJavaObject
		{
			AndroidRuntimeInternal.WaitForBridgeProcessing ();

			if (!JniEnvironment.BeginMarshalMethod (jnienv, out var __envp, out var __r))
				return default;

			try {
				var __this = global::Java.Lang.Object.GetObject<TPeer> (self, JniHandleOwnership.DoNotTransfer);
				if (__this is null)
					throw new NullReferenceException (PeerLookupFailed);
				var p2 = global::Java.Lang.Object.GetObject<T2> (native_p2, JniHandleOwnership.DoNotTransfer);
				return JNIEnv.ToLocalJniHandle (body (__this, p0, p1, p2));
			} catch (Exception __e) {
				__r.OnUserUnhandledException (ref __envp, __e);
				return default;
			} finally {
				JniEnvironment.EndMarshalMethod (ref __envp);
			}
		}

		[DebuggerDisableUserUnhandledExceptions]
		public static unsafe void Invoke_OSOX<[DynamicallyAccessedMembers (Constructors)] TPeer, [DynamicallyAccessedMembers (Constructors)] T0, T1, [DynamicallyAccessedMembers (Constructors)] T2> (IntPtr jnienv, IntPtr self, IntPtr native_p0, T1 p1, IntPtr native_p2, delegate* managed<TPeer, T0?, T1, T2?, void> body)
			where TPeer : class, IJavaObject
			where T0 : class, IJavaObject
			where T1 : unmanaged
			where T2 : class, IJavaObject
		{
			AndroidRuntimeInternal.WaitForBridgeProcessing ();

			if (!JniEnvironment.BeginMarshalMethod (jnienv, out var __envp, out var __r))
				return;

			try {
				var __this = global::Java.Lang.Object.GetObject<TPeer> (self, JniHandleOwnership.DoNotTransfer);
				if (__this is null)
					throw new NullReferenceException (PeerLookupFailed);
				var p0 = global::Java.Lang.Object.GetObject<T0> (native_p0, JniHandleOwnership.DoNotTransfer);
				var p2 = global::Java.Lang.Object.GetObject<T2> (native_p2, JniHandleOwnership.DoNotTransfer);
				body (__this, p0, p1, p2);
			} catch (Exception __e) {
				__r.OnUserUnhandledException (ref __envp, __e);
				return;
			} finally {
				JniEnvironment.EndMarshalMethod (ref __envp);
			}
		}

		[DebuggerDisableUserUnhandledExceptions]
		public static unsafe TResult Invoke_OSOS<[DynamicallyAccessedMembers (Constructors)] TPeer, [DynamicallyAccessedMembers (Constructors)] T0, T1, [DynamicallyAccessedMembers (Constructors)] T2, TResult> (IntPtr jnienv, IntPtr self, IntPtr native_p0, T1 p1, IntPtr native_p2, delegate* managed<TPeer, T0?, T1, T2?, TResult> body)
			where TPeer : class, IJavaObject
			where T0 : class, IJavaObject
			where T1 : unmanaged
			where T2 : class, IJavaObject
			where TResult : unmanaged
		{
			AndroidRuntimeInternal.WaitForBridgeProcessing ();

			if (!JniEnvironment.BeginMarshalMethod (jnienv, out var __envp, out var __r))
				return default;

			try {
				var __this = global::Java.Lang.Object.GetObject<TPeer> (self, JniHandleOwnership.DoNotTransfer);
				if (__this is null)
					throw new NullReferenceException (PeerLookupFailed);
				var p0 = global::Java.Lang.Object.GetObject<T0> (native_p0, JniHandleOwnership.DoNotTransfer);
				var p2 = global::Java.Lang.Object.GetObject<T2> (native_p2, JniHandleOwnership.DoNotTransfer);
				return body (__this, p0, p1, p2);
			} catch (Exception __e) {
				__r.OnUserUnhandledException (ref __envp, __e);
				return default;
			} finally {
				JniEnvironment.EndMarshalMethod (ref __envp);
			}
		}

		[DebuggerDisableUserUnhandledExceptions]
		public static unsafe IntPtr Invoke_OSOO<[DynamicallyAccessedMembers (Constructors)] TPeer, [DynamicallyAccessedMembers (Constructors)] T0, T1, [DynamicallyAccessedMembers (Constructors)] T2> (IntPtr jnienv, IntPtr self, IntPtr native_p0, T1 p1, IntPtr native_p2, delegate* managed<TPeer, T0?, T1, T2?, IJavaObject?> body)
			where TPeer : class, IJavaObject
			where T0 : class, IJavaObject
			where T1 : unmanaged
			where T2 : class, IJavaObject
		{
			AndroidRuntimeInternal.WaitForBridgeProcessing ();

			if (!JniEnvironment.BeginMarshalMethod (jnienv, out var __envp, out var __r))
				return default;

			try {
				var __this = global::Java.Lang.Object.GetObject<TPeer> (self, JniHandleOwnership.DoNotTransfer);
				if (__this is null)
					throw new NullReferenceException (PeerLookupFailed);
				var p0 = global::Java.Lang.Object.GetObject<T0> (native_p0, JniHandleOwnership.DoNotTransfer);
				var p2 = global::Java.Lang.Object.GetObject<T2> (native_p2, JniHandleOwnership.DoNotTransfer);
				return JNIEnv.ToLocalJniHandle (body (__this, p0, p1, p2));
			} catch (Exception __e) {
				__r.OnUserUnhandledException (ref __envp, __e);
				return default;
			} finally {
				JniEnvironment.EndMarshalMethod (ref __envp);
			}
		}

		[DebuggerDisableUserUnhandledExceptions]
		public static unsafe void Invoke_SOOX<[DynamicallyAccessedMembers (Constructors)] TPeer, T0, [DynamicallyAccessedMembers (Constructors)] T1, [DynamicallyAccessedMembers (Constructors)] T2> (IntPtr jnienv, IntPtr self, T0 p0, IntPtr native_p1, IntPtr native_p2, delegate* managed<TPeer, T0, T1?, T2?, void> body)
			where TPeer : class, IJavaObject
			where T0 : unmanaged
			where T1 : class, IJavaObject
			where T2 : class, IJavaObject
		{
			AndroidRuntimeInternal.WaitForBridgeProcessing ();

			if (!JniEnvironment.BeginMarshalMethod (jnienv, out var __envp, out var __r))
				return;

			try {
				var __this = global::Java.Lang.Object.GetObject<TPeer> (self, JniHandleOwnership.DoNotTransfer);
				if (__this is null)
					throw new NullReferenceException (PeerLookupFailed);
				var p1 = global::Java.Lang.Object.GetObject<T1> (native_p1, JniHandleOwnership.DoNotTransfer);
				var p2 = global::Java.Lang.Object.GetObject<T2> (native_p2, JniHandleOwnership.DoNotTransfer);
				body (__this, p0, p1, p2);
			} catch (Exception __e) {
				__r.OnUserUnhandledException (ref __envp, __e);
				return;
			} finally {
				JniEnvironment.EndMarshalMethod (ref __envp);
			}
		}

		[DebuggerDisableUserUnhandledExceptions]
		public static unsafe TResult Invoke_SOOS<[DynamicallyAccessedMembers (Constructors)] TPeer, T0, [DynamicallyAccessedMembers (Constructors)] T1, [DynamicallyAccessedMembers (Constructors)] T2, TResult> (IntPtr jnienv, IntPtr self, T0 p0, IntPtr native_p1, IntPtr native_p2, delegate* managed<TPeer, T0, T1?, T2?, TResult> body)
			where TPeer : class, IJavaObject
			where T0 : unmanaged
			where T1 : class, IJavaObject
			where T2 : class, IJavaObject
			where TResult : unmanaged
		{
			AndroidRuntimeInternal.WaitForBridgeProcessing ();

			if (!JniEnvironment.BeginMarshalMethod (jnienv, out var __envp, out var __r))
				return default;

			try {
				var __this = global::Java.Lang.Object.GetObject<TPeer> (self, JniHandleOwnership.DoNotTransfer);
				if (__this is null)
					throw new NullReferenceException (PeerLookupFailed);
				var p1 = global::Java.Lang.Object.GetObject<T1> (native_p1, JniHandleOwnership.DoNotTransfer);
				var p2 = global::Java.Lang.Object.GetObject<T2> (native_p2, JniHandleOwnership.DoNotTransfer);
				return body (__this, p0, p1, p2);
			} catch (Exception __e) {
				__r.OnUserUnhandledException (ref __envp, __e);
				return default;
			} finally {
				JniEnvironment.EndMarshalMethod (ref __envp);
			}
		}

		[DebuggerDisableUserUnhandledExceptions]
		public static unsafe IntPtr Invoke_SOOO<[DynamicallyAccessedMembers (Constructors)] TPeer, T0, [DynamicallyAccessedMembers (Constructors)] T1, [DynamicallyAccessedMembers (Constructors)] T2> (IntPtr jnienv, IntPtr self, T0 p0, IntPtr native_p1, IntPtr native_p2, delegate* managed<TPeer, T0, T1?, T2?, IJavaObject?> body)
			where TPeer : class, IJavaObject
			where T0 : unmanaged
			where T1 : class, IJavaObject
			where T2 : class, IJavaObject
		{
			AndroidRuntimeInternal.WaitForBridgeProcessing ();

			if (!JniEnvironment.BeginMarshalMethod (jnienv, out var __envp, out var __r))
				return default;

			try {
				var __this = global::Java.Lang.Object.GetObject<TPeer> (self, JniHandleOwnership.DoNotTransfer);
				if (__this is null)
					throw new NullReferenceException (PeerLookupFailed);
				var p1 = global::Java.Lang.Object.GetObject<T1> (native_p1, JniHandleOwnership.DoNotTransfer);
				var p2 = global::Java.Lang.Object.GetObject<T2> (native_p2, JniHandleOwnership.DoNotTransfer);
				return JNIEnv.ToLocalJniHandle (body (__this, p0, p1, p2));
			} catch (Exception __e) {
				__r.OnUserUnhandledException (ref __envp, __e);
				return default;
			} finally {
				JniEnvironment.EndMarshalMethod (ref __envp);
			}
		}

		[DebuggerDisableUserUnhandledExceptions]
		public static unsafe void Invoke_OOOX<[DynamicallyAccessedMembers (Constructors)] TPeer, [DynamicallyAccessedMembers (Constructors)] T0, [DynamicallyAccessedMembers (Constructors)] T1, [DynamicallyAccessedMembers (Constructors)] T2> (IntPtr jnienv, IntPtr self, IntPtr native_p0, IntPtr native_p1, IntPtr native_p2, delegate* managed<TPeer, T0?, T1?, T2?, void> body)
			where TPeer : class, IJavaObject
			where T0 : class, IJavaObject
			where T1 : class, IJavaObject
			where T2 : class, IJavaObject
		{
			AndroidRuntimeInternal.WaitForBridgeProcessing ();

			if (!JniEnvironment.BeginMarshalMethod (jnienv, out var __envp, out var __r))
				return;

			try {
				var __this = global::Java.Lang.Object.GetObject<TPeer> (self, JniHandleOwnership.DoNotTransfer);
				if (__this is null)
					throw new NullReferenceException (PeerLookupFailed);
				var p0 = global::Java.Lang.Object.GetObject<T0> (native_p0, JniHandleOwnership.DoNotTransfer);
				var p1 = global::Java.Lang.Object.GetObject<T1> (native_p1, JniHandleOwnership.DoNotTransfer);
				var p2 = global::Java.Lang.Object.GetObject<T2> (native_p2, JniHandleOwnership.DoNotTransfer);
				body (__this, p0, p1, p2);
			} catch (Exception __e) {
				__r.OnUserUnhandledException (ref __envp, __e);
				return;
			} finally {
				JniEnvironment.EndMarshalMethod (ref __envp);
			}
		}

		[DebuggerDisableUserUnhandledExceptions]
		public static unsafe TResult Invoke_OOOS<[DynamicallyAccessedMembers (Constructors)] TPeer, [DynamicallyAccessedMembers (Constructors)] T0, [DynamicallyAccessedMembers (Constructors)] T1, [DynamicallyAccessedMembers (Constructors)] T2, TResult> (IntPtr jnienv, IntPtr self, IntPtr native_p0, IntPtr native_p1, IntPtr native_p2, delegate* managed<TPeer, T0?, T1?, T2?, TResult> body)
			where TPeer : class, IJavaObject
			where T0 : class, IJavaObject
			where T1 : class, IJavaObject
			where T2 : class, IJavaObject
			where TResult : unmanaged
		{
			AndroidRuntimeInternal.WaitForBridgeProcessing ();

			if (!JniEnvironment.BeginMarshalMethod (jnienv, out var __envp, out var __r))
				return default;

			try {
				var __this = global::Java.Lang.Object.GetObject<TPeer> (self, JniHandleOwnership.DoNotTransfer);
				if (__this is null)
					throw new NullReferenceException (PeerLookupFailed);
				var p0 = global::Java.Lang.Object.GetObject<T0> (native_p0, JniHandleOwnership.DoNotTransfer);
				var p1 = global::Java.Lang.Object.GetObject<T1> (native_p1, JniHandleOwnership.DoNotTransfer);
				var p2 = global::Java.Lang.Object.GetObject<T2> (native_p2, JniHandleOwnership.DoNotTransfer);
				return body (__this, p0, p1, p2);
			} catch (Exception __e) {
				__r.OnUserUnhandledException (ref __envp, __e);
				return default;
			} finally {
				JniEnvironment.EndMarshalMethod (ref __envp);
			}
		}

		[DebuggerDisableUserUnhandledExceptions]
		public static unsafe IntPtr Invoke_OOOO<[DynamicallyAccessedMembers (Constructors)] TPeer, [DynamicallyAccessedMembers (Constructors)] T0, [DynamicallyAccessedMembers (Constructors)] T1, [DynamicallyAccessedMembers (Constructors)] T2> (IntPtr jnienv, IntPtr self, IntPtr native_p0, IntPtr native_p1, IntPtr native_p2, delegate* managed<TPeer, T0?, T1?, T2?, IJavaObject?> body)
			where TPeer : class, IJavaObject
			where T0 : class, IJavaObject
			where T1 : class, IJavaObject
			where T2 : class, IJavaObject
		{
			AndroidRuntimeInternal.WaitForBridgeProcessing ();

			if (!JniEnvironment.BeginMarshalMethod (jnienv, out var __envp, out var __r))
				return default;

			try {
				var __this = global::Java.Lang.Object.GetObject<TPeer> (self, JniHandleOwnership.DoNotTransfer);
				if (__this is null)
					throw new NullReferenceException (PeerLookupFailed);
				var p0 = global::Java.Lang.Object.GetObject<T0> (native_p0, JniHandleOwnership.DoNotTransfer);
				var p1 = global::Java.Lang.Object.GetObject<T1> (native_p1, JniHandleOwnership.DoNotTransfer);
				var p2 = global::Java.Lang.Object.GetObject<T2> (native_p2, JniHandleOwnership.DoNotTransfer);
				return JNIEnv.ToLocalJniHandle (body (__this, p0, p1, p2));
			} catch (Exception __e) {
				__r.OnUserUnhandledException (ref __envp, __e);
				return default;
			} finally {
				JniEnvironment.EndMarshalMethod (ref __envp);
			}
		}

		[DebuggerDisableUserUnhandledExceptions]
		public static unsafe void Invoke_SSSSX<[DynamicallyAccessedMembers (Constructors)] TPeer, T0, T1, T2, T3> (IntPtr jnienv, IntPtr self, T0 p0, T1 p1, T2 p2, T3 p3, delegate* managed<TPeer, T0, T1, T2, T3, void> body)
			where TPeer : class, IJavaObject
			where T0 : unmanaged
			where T1 : unmanaged
			where T2 : unmanaged
			where T3 : unmanaged
		{
			AndroidRuntimeInternal.WaitForBridgeProcessing ();

			if (!JniEnvironment.BeginMarshalMethod (jnienv, out var __envp, out var __r))
				return;

			try {
				var __this = global::Java.Lang.Object.GetObject<TPeer> (self, JniHandleOwnership.DoNotTransfer);
				if (__this is null)
					throw new NullReferenceException (PeerLookupFailed);
				body (__this, p0, p1, p2, p3);
			} catch (Exception __e) {
				__r.OnUserUnhandledException (ref __envp, __e);
				return;
			} finally {
				JniEnvironment.EndMarshalMethod (ref __envp);
			}
		}

		[DebuggerDisableUserUnhandledExceptions]
		public static unsafe TResult Invoke_SSSSS<[DynamicallyAccessedMembers (Constructors)] TPeer, T0, T1, T2, T3, TResult> (IntPtr jnienv, IntPtr self, T0 p0, T1 p1, T2 p2, T3 p3, delegate* managed<TPeer, T0, T1, T2, T3, TResult> body)
			where TPeer : class, IJavaObject
			where T0 : unmanaged
			where T1 : unmanaged
			where T2 : unmanaged
			where T3 : unmanaged
			where TResult : unmanaged
		{
			AndroidRuntimeInternal.WaitForBridgeProcessing ();

			if (!JniEnvironment.BeginMarshalMethod (jnienv, out var __envp, out var __r))
				return default;

			try {
				var __this = global::Java.Lang.Object.GetObject<TPeer> (self, JniHandleOwnership.DoNotTransfer);
				if (__this is null)
					throw new NullReferenceException (PeerLookupFailed);
				return body (__this, p0, p1, p2, p3);
			} catch (Exception __e) {
				__r.OnUserUnhandledException (ref __envp, __e);
				return default;
			} finally {
				JniEnvironment.EndMarshalMethod (ref __envp);
			}
		}

		[DebuggerDisableUserUnhandledExceptions]
		public static unsafe IntPtr Invoke_SSSSO<[DynamicallyAccessedMembers (Constructors)] TPeer, T0, T1, T2, T3> (IntPtr jnienv, IntPtr self, T0 p0, T1 p1, T2 p2, T3 p3, delegate* managed<TPeer, T0, T1, T2, T3, IJavaObject?> body)
			where TPeer : class, IJavaObject
			where T0 : unmanaged
			where T1 : unmanaged
			where T2 : unmanaged
			where T3 : unmanaged
		{
			AndroidRuntimeInternal.WaitForBridgeProcessing ();

			if (!JniEnvironment.BeginMarshalMethod (jnienv, out var __envp, out var __r))
				return default;

			try {
				var __this = global::Java.Lang.Object.GetObject<TPeer> (self, JniHandleOwnership.DoNotTransfer);
				if (__this is null)
					throw new NullReferenceException (PeerLookupFailed);
				return JNIEnv.ToLocalJniHandle (body (__this, p0, p1, p2, p3));
			} catch (Exception __e) {
				__r.OnUserUnhandledException (ref __envp, __e);
				return default;
			} finally {
				JniEnvironment.EndMarshalMethod (ref __envp);
			}
		}

		[DebuggerDisableUserUnhandledExceptions]
		public static unsafe void Invoke_SSSSSX<[DynamicallyAccessedMembers (Constructors)] TPeer, T0, T1, T2, T3, T4> (IntPtr jnienv, IntPtr self, T0 p0, T1 p1, T2 p2, T3 p3, T4 p4, delegate* managed<TPeer, T0, T1, T2, T3, T4, void> body)
			where TPeer : class, IJavaObject
			where T0 : unmanaged
			where T1 : unmanaged
			where T2 : unmanaged
			where T3 : unmanaged
			where T4 : unmanaged
		{
			AndroidRuntimeInternal.WaitForBridgeProcessing ();

			if (!JniEnvironment.BeginMarshalMethod (jnienv, out var __envp, out var __r))
				return;

			try {
				var __this = global::Java.Lang.Object.GetObject<TPeer> (self, JniHandleOwnership.DoNotTransfer);
				if (__this is null)
					throw new NullReferenceException (PeerLookupFailed);
				body (__this, p0, p1, p2, p3, p4);
			} catch (Exception __e) {
				__r.OnUserUnhandledException (ref __envp, __e);
				return;
			} finally {
				JniEnvironment.EndMarshalMethod (ref __envp);
			}
		}

		[DebuggerDisableUserUnhandledExceptions]
		public static unsafe TResult Invoke_SSSSSS<[DynamicallyAccessedMembers (Constructors)] TPeer, T0, T1, T2, T3, T4, TResult> (IntPtr jnienv, IntPtr self, T0 p0, T1 p1, T2 p2, T3 p3, T4 p4, delegate* managed<TPeer, T0, T1, T2, T3, T4, TResult> body)
			where TPeer : class, IJavaObject
			where T0 : unmanaged
			where T1 : unmanaged
			where T2 : unmanaged
			where T3 : unmanaged
			where T4 : unmanaged
			where TResult : unmanaged
		{
			AndroidRuntimeInternal.WaitForBridgeProcessing ();

			if (!JniEnvironment.BeginMarshalMethod (jnienv, out var __envp, out var __r))
				return default;

			try {
				var __this = global::Java.Lang.Object.GetObject<TPeer> (self, JniHandleOwnership.DoNotTransfer);
				if (__this is null)
					throw new NullReferenceException (PeerLookupFailed);
				return body (__this, p0, p1, p2, p3, p4);
			} catch (Exception __e) {
				__r.OnUserUnhandledException (ref __envp, __e);
				return default;
			} finally {
				JniEnvironment.EndMarshalMethod (ref __envp);
			}
		}

		[DebuggerDisableUserUnhandledExceptions]
		public static unsafe IntPtr Invoke_SSSSSO<[DynamicallyAccessedMembers (Constructors)] TPeer, T0, T1, T2, T3, T4> (IntPtr jnienv, IntPtr self, T0 p0, T1 p1, T2 p2, T3 p3, T4 p4, delegate* managed<TPeer, T0, T1, T2, T3, T4, IJavaObject?> body)
			where TPeer : class, IJavaObject
			where T0 : unmanaged
			where T1 : unmanaged
			where T2 : unmanaged
			where T3 : unmanaged
			where T4 : unmanaged
		{
			AndroidRuntimeInternal.WaitForBridgeProcessing ();

			if (!JniEnvironment.BeginMarshalMethod (jnienv, out var __envp, out var __r))
				return default;

			try {
				var __this = global::Java.Lang.Object.GetObject<TPeer> (self, JniHandleOwnership.DoNotTransfer);
				if (__this is null)
					throw new NullReferenceException (PeerLookupFailed);
				return JNIEnv.ToLocalJniHandle (body (__this, p0, p1, p2, p3, p4));
			} catch (Exception __e) {
				__r.OnUserUnhandledException (ref __envp, __e);
				return default;
			} finally {
				JniEnvironment.EndMarshalMethod (ref __envp);
			}
		}

		[DebuggerDisableUserUnhandledExceptions]
		public static unsafe void Invoke_SSSSSSX<[DynamicallyAccessedMembers (Constructors)] TPeer, T0, T1, T2, T3, T4, T5> (IntPtr jnienv, IntPtr self, T0 p0, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, delegate* managed<TPeer, T0, T1, T2, T3, T4, T5, void> body)
			where TPeer : class, IJavaObject
			where T0 : unmanaged
			where T1 : unmanaged
			where T2 : unmanaged
			where T3 : unmanaged
			where T4 : unmanaged
			where T5 : unmanaged
		{
			AndroidRuntimeInternal.WaitForBridgeProcessing ();

			if (!JniEnvironment.BeginMarshalMethod (jnienv, out var __envp, out var __r))
				return;

			try {
				var __this = global::Java.Lang.Object.GetObject<TPeer> (self, JniHandleOwnership.DoNotTransfer);
				if (__this is null)
					throw new NullReferenceException (PeerLookupFailed);
				body (__this, p0, p1, p2, p3, p4, p5);
			} catch (Exception __e) {
				__r.OnUserUnhandledException (ref __envp, __e);
				return;
			} finally {
				JniEnvironment.EndMarshalMethod (ref __envp);
			}
		}

		[DebuggerDisableUserUnhandledExceptions]
		public static unsafe TResult Invoke_SSSSSSS<[DynamicallyAccessedMembers (Constructors)] TPeer, T0, T1, T2, T3, T4, T5, TResult> (IntPtr jnienv, IntPtr self, T0 p0, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, delegate* managed<TPeer, T0, T1, T2, T3, T4, T5, TResult> body)
			where TPeer : class, IJavaObject
			where T0 : unmanaged
			where T1 : unmanaged
			where T2 : unmanaged
			where T3 : unmanaged
			where T4 : unmanaged
			where T5 : unmanaged
			where TResult : unmanaged
		{
			AndroidRuntimeInternal.WaitForBridgeProcessing ();

			if (!JniEnvironment.BeginMarshalMethod (jnienv, out var __envp, out var __r))
				return default;

			try {
				var __this = global::Java.Lang.Object.GetObject<TPeer> (self, JniHandleOwnership.DoNotTransfer);
				if (__this is null)
					throw new NullReferenceException (PeerLookupFailed);
				return body (__this, p0, p1, p2, p3, p4, p5);
			} catch (Exception __e) {
				__r.OnUserUnhandledException (ref __envp, __e);
				return default;
			} finally {
				JniEnvironment.EndMarshalMethod (ref __envp);
			}
		}

		[DebuggerDisableUserUnhandledExceptions]
		public static unsafe IntPtr Invoke_SSSSSSO<[DynamicallyAccessedMembers (Constructors)] TPeer, T0, T1, T2, T3, T4, T5> (IntPtr jnienv, IntPtr self, T0 p0, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, delegate* managed<TPeer, T0, T1, T2, T3, T4, T5, IJavaObject?> body)
			where TPeer : class, IJavaObject
			where T0 : unmanaged
			where T1 : unmanaged
			where T2 : unmanaged
			where T3 : unmanaged
			where T4 : unmanaged
			where T5 : unmanaged
		{
			AndroidRuntimeInternal.WaitForBridgeProcessing ();

			if (!JniEnvironment.BeginMarshalMethod (jnienv, out var __envp, out var __r))
				return default;

			try {
				var __this = global::Java.Lang.Object.GetObject<TPeer> (self, JniHandleOwnership.DoNotTransfer);
				if (__this is null)
					throw new NullReferenceException (PeerLookupFailed);
				return JNIEnv.ToLocalJniHandle (body (__this, p0, p1, p2, p3, p4, p5));
			} catch (Exception __e) {
				__r.OnUserUnhandledException (ref __envp, __e);
				return default;
			} finally {
				JniEnvironment.EndMarshalMethod (ref __envp);
			}
		}

		[DebuggerDisableUserUnhandledExceptions]
		public static unsafe void Invoke_SSSSSSSX<[DynamicallyAccessedMembers (Constructors)] TPeer, T0, T1, T2, T3, T4, T5, T6> (IntPtr jnienv, IntPtr self, T0 p0, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, delegate* managed<TPeer, T0, T1, T2, T3, T4, T5, T6, void> body)
			where TPeer : class, IJavaObject
			where T0 : unmanaged
			where T1 : unmanaged
			where T2 : unmanaged
			where T3 : unmanaged
			where T4 : unmanaged
			where T5 : unmanaged
			where T6 : unmanaged
		{
			AndroidRuntimeInternal.WaitForBridgeProcessing ();

			if (!JniEnvironment.BeginMarshalMethod (jnienv, out var __envp, out var __r))
				return;

			try {
				var __this = global::Java.Lang.Object.GetObject<TPeer> (self, JniHandleOwnership.DoNotTransfer);
				if (__this is null)
					throw new NullReferenceException (PeerLookupFailed);
				body (__this, p0, p1, p2, p3, p4, p5, p6);
			} catch (Exception __e) {
				__r.OnUserUnhandledException (ref __envp, __e);
				return;
			} finally {
				JniEnvironment.EndMarshalMethod (ref __envp);
			}
		}

		[DebuggerDisableUserUnhandledExceptions]
		public static unsafe TResult Invoke_SSSSSSSS<[DynamicallyAccessedMembers (Constructors)] TPeer, T0, T1, T2, T3, T4, T5, T6, TResult> (IntPtr jnienv, IntPtr self, T0 p0, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, delegate* managed<TPeer, T0, T1, T2, T3, T4, T5, T6, TResult> body)
			where TPeer : class, IJavaObject
			where T0 : unmanaged
			where T1 : unmanaged
			where T2 : unmanaged
			where T3 : unmanaged
			where T4 : unmanaged
			where T5 : unmanaged
			where T6 : unmanaged
			where TResult : unmanaged
		{
			AndroidRuntimeInternal.WaitForBridgeProcessing ();

			if (!JniEnvironment.BeginMarshalMethod (jnienv, out var __envp, out var __r))
				return default;

			try {
				var __this = global::Java.Lang.Object.GetObject<TPeer> (self, JniHandleOwnership.DoNotTransfer);
				if (__this is null)
					throw new NullReferenceException (PeerLookupFailed);
				return body (__this, p0, p1, p2, p3, p4, p5, p6);
			} catch (Exception __e) {
				__r.OnUserUnhandledException (ref __envp, __e);
				return default;
			} finally {
				JniEnvironment.EndMarshalMethod (ref __envp);
			}
		}

		[DebuggerDisableUserUnhandledExceptions]
		public static unsafe IntPtr Invoke_SSSSSSSO<[DynamicallyAccessedMembers (Constructors)] TPeer, T0, T1, T2, T3, T4, T5, T6> (IntPtr jnienv, IntPtr self, T0 p0, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, delegate* managed<TPeer, T0, T1, T2, T3, T4, T5, T6, IJavaObject?> body)
			where TPeer : class, IJavaObject
			where T0 : unmanaged
			where T1 : unmanaged
			where T2 : unmanaged
			where T3 : unmanaged
			where T4 : unmanaged
			where T5 : unmanaged
			where T6 : unmanaged
		{
			AndroidRuntimeInternal.WaitForBridgeProcessing ();

			if (!JniEnvironment.BeginMarshalMethod (jnienv, out var __envp, out var __r))
				return default;

			try {
				var __this = global::Java.Lang.Object.GetObject<TPeer> (self, JniHandleOwnership.DoNotTransfer);
				if (__this is null)
					throw new NullReferenceException (PeerLookupFailed);
				return JNIEnv.ToLocalJniHandle (body (__this, p0, p1, p2, p3, p4, p5, p6));
			} catch (Exception __e) {
				__r.OnUserUnhandledException (ref __envp, __e);
				return default;
			} finally {
				JniEnvironment.EndMarshalMethod (ref __envp);
			}
		}

		[DebuggerDisableUserUnhandledExceptions]
		public static unsafe void Invoke_SSSSSSSSX<[DynamicallyAccessedMembers (Constructors)] TPeer, T0, T1, T2, T3, T4, T5, T6, T7> (IntPtr jnienv, IntPtr self, T0 p0, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, delegate* managed<TPeer, T0, T1, T2, T3, T4, T5, T6, T7, void> body)
			where TPeer : class, IJavaObject
			where T0 : unmanaged
			where T1 : unmanaged
			where T2 : unmanaged
			where T3 : unmanaged
			where T4 : unmanaged
			where T5 : unmanaged
			where T6 : unmanaged
			where T7 : unmanaged
		{
			AndroidRuntimeInternal.WaitForBridgeProcessing ();

			if (!JniEnvironment.BeginMarshalMethod (jnienv, out var __envp, out var __r))
				return;

			try {
				var __this = global::Java.Lang.Object.GetObject<TPeer> (self, JniHandleOwnership.DoNotTransfer);
				if (__this is null)
					throw new NullReferenceException (PeerLookupFailed);
				body (__this, p0, p1, p2, p3, p4, p5, p6, p7);
			} catch (Exception __e) {
				__r.OnUserUnhandledException (ref __envp, __e);
				return;
			} finally {
				JniEnvironment.EndMarshalMethod (ref __envp);
			}
		}

		[DebuggerDisableUserUnhandledExceptions]
		public static unsafe TResult Invoke_SSSSSSSSS<[DynamicallyAccessedMembers (Constructors)] TPeer, T0, T1, T2, T3, T4, T5, T6, T7, TResult> (IntPtr jnienv, IntPtr self, T0 p0, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, delegate* managed<TPeer, T0, T1, T2, T3, T4, T5, T6, T7, TResult> body)
			where TPeer : class, IJavaObject
			where T0 : unmanaged
			where T1 : unmanaged
			where T2 : unmanaged
			where T3 : unmanaged
			where T4 : unmanaged
			where T5 : unmanaged
			where T6 : unmanaged
			where T7 : unmanaged
			where TResult : unmanaged
		{
			AndroidRuntimeInternal.WaitForBridgeProcessing ();

			if (!JniEnvironment.BeginMarshalMethod (jnienv, out var __envp, out var __r))
				return default;

			try {
				var __this = global::Java.Lang.Object.GetObject<TPeer> (self, JniHandleOwnership.DoNotTransfer);
				if (__this is null)
					throw new NullReferenceException (PeerLookupFailed);
				return body (__this, p0, p1, p2, p3, p4, p5, p6, p7);
			} catch (Exception __e) {
				__r.OnUserUnhandledException (ref __envp, __e);
				return default;
			} finally {
				JniEnvironment.EndMarshalMethod (ref __envp);
			}
		}

		[DebuggerDisableUserUnhandledExceptions]
		public static unsafe IntPtr Invoke_SSSSSSSSO<[DynamicallyAccessedMembers (Constructors)] TPeer, T0, T1, T2, T3, T4, T5, T6, T7> (IntPtr jnienv, IntPtr self, T0 p0, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, delegate* managed<TPeer, T0, T1, T2, T3, T4, T5, T6, T7, IJavaObject?> body)
			where TPeer : class, IJavaObject
			where T0 : unmanaged
			where T1 : unmanaged
			where T2 : unmanaged
			where T3 : unmanaged
			where T4 : unmanaged
			where T5 : unmanaged
			where T6 : unmanaged
			where T7 : unmanaged
		{
			AndroidRuntimeInternal.WaitForBridgeProcessing ();

			if (!JniEnvironment.BeginMarshalMethod (jnienv, out var __envp, out var __r))
				return default;

			try {
				var __this = global::Java.Lang.Object.GetObject<TPeer> (self, JniHandleOwnership.DoNotTransfer);
				if (__this is null)
					throw new NullReferenceException (PeerLookupFailed);
				return JNIEnv.ToLocalJniHandle (body (__this, p0, p1, p2, p3, p4, p5, p6, p7));
			} catch (Exception __e) {
				__r.OnUserUnhandledException (ref __envp, __e);
				return default;
			} finally {
				JniEnvironment.EndMarshalMethod (ref __envp);
			}
		}
	}
}
