parameters:
  buildPoolName: $(LinuxBuildPoolName)
  buildPoolImage: $(LinuxBuildPoolImage)
  buildResultArtifactName: Build Results - Linux
  checkoutCommit: ''
  checkoutPath: 's/xamarin-android'
  checkoutPersistCredentials: false
  dependsOn: ''
  dependsOnResult: ''
  jobName: linux_build_create_sdk_pack
  jobDisplayName: Linux > Build
  nugetArtifactName: $(LinuxNuGetArtifactName)
  repositoryAlias: self
  stageName: linux_build
  stageDisplayName: Linux

stages:
- stage: ${{ parameters.stageName }}
  displayName: ${{ parameters.stageDisplayName }}
  dependsOn: ${{ parameters.dependsOn }}
  ${{ if and(ne(parameters.dependsOn, ''), ne(parameters.dependsOnResult, '')) }}:
    condition: eq(dependencies.${{ parameters.dependsOn }}.result, '${{ parameters.dependsOnResult }}')
  jobs:
  - job: ${{ parameters.jobName }}
    displayName: ${{ parameters.jobDisplayName }}
    pool:
      name: ${{ parameters.buildPoolName }}
      vmImage: ${{ parameters.buildPoolImage }}
    timeoutInMinutes: 180
    workspace:
      clean: all
    variables:
      CXX: g++-10
      CC: gcc-10
    steps:
    - template: sdk-unified/steps/checkout/v1.yml@yaml-templates
      parameters:
        resource: ${{ parameters.repositoryAlias }}
        commit: ${{ parameters.checkoutCommit }}
        path: ${{ parameters.checkoutPath }}
        persistCredentials: ${{ parameters.checkoutPersistCredentials }}

    # Always checkout a second resource to ensure we are using multi-repo checkout behavior
    #  https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout?view=azure-devops#checkout-path
    - checkout: maui

    - template: setup-ubuntu.yaml

    - ${{ if ne(variables['System.PullRequest.IsFork'], 'True') }}:
      - checkout: monodroid
        clean: true
        submodules: recursive
        path: s/xamarin-android/external/monodroid
        persistCredentials: true

      - script: rm -rf external/monodroid/external/xamarin-android
        workingDirectory: $(System.DefaultWorkingDirectory)/xamarin-android
        displayName: delete external xamarin-android submodule

      - script: make prepare-external-git-dependencies PREPARE_CI=1 CONFIGURATION=$(XA.Build.Configuration)
        workingDirectory: $(System.DefaultWorkingDirectory)/xamarin-android
        displayName: make prepare-external-git-dependencies

    - task: NuGetAuthenticate@0
      displayName: authenticate with azure artifacts
      inputs:
        forceReinstallCredentialProvider: true

    - script: make jenkins PREPARE_CI=1 PREPARE_AUTOPROVISION=1 CONFIGURATION=$(XA.Build.Configuration)
      workingDirectory: $(System.DefaultWorkingDirectory)/xamarin-android
      displayName: make jenkins

    - script: make create-nupkgs CONFIGURATION=$(XA.Build.Configuration)
      workingDirectory: $(System.DefaultWorkingDirectory)/xamarin-android
      displayName: make create-nupkgs

    - script: >
        df -h &&
        mkdir -p $(System.DefaultWorkingDirectory)/xamarin-android/bin/Build$(XA.Build.Configuration)/nuget-linux &&
        ln $(System.DefaultWorkingDirectory)/xamarin-android/bin/Build$(XA.Build.Configuration)/nuget-unsigned/Microsoft.Android.Sdk.Linux*.nupkg
        $(System.DefaultWorkingDirectory)/xamarin-android/bin/Build$(XA.Build.Configuration)/nuget-linux &&
        ln $(System.DefaultWorkingDirectory)/xamarin-android/bin/Build$(XA.Build.Configuration)/nuget-unsigned/SignList.xml
        $(System.DefaultWorkingDirectory)/xamarin-android/bin/Build$(XA.Build.Configuration)/nuget-linux
      workingDirectory: $(System.DefaultWorkingDirectory)/xamarin-android
      displayName: copy linux sdk

    - task: PublishPipelineArtifact@1
      displayName: upload linux sdk
      inputs:
        artifactName: ${{ parameters.nugetArtifactName }}
        targetPath: $(System.DefaultWorkingDirectory)/xamarin-android/bin/Build$(XA.Build.Configuration)/nuget-linux

    - powershell: |
        [IO.Directory]::CreateDirectory("$(Build.StagingDirectory)/empty")
        [IO.Directory]::CreateDirectory("$(Build.StagingDirectory)/sbom-components")
      displayName: create SBOM directories
      condition: and(succeeded(), eq(variables['MicroBuildSignType'], 'Real'))

    - task: AzureArtifacts.manifest-generator-task.manifest-generator-task.ManifestGeneratorTask@0
      displayName: generate components SBOM
      condition: and(succeeded(), eq(variables['MicroBuildSignType'], 'Real'))
      inputs:
        BuildDropPath: $(Build.StagingDirectory)/empty
        BuildComponentPath: $(System.DefaultWorkingDirectory)/xamarin-android
        ManifestDirPath: $(Build.StagingDirectory)/sbom-components
        PackageName: .NET Android
        Verbosity: Verbose

    - task: PublishBuildArtifacts@1
      displayName: publish components SBOM
      condition: and(succeeded(), eq(variables['MicroBuildSignType'], 'Real'))
      inputs:
        artifactName: sbom-components-linux
        pathToPublish: $(Build.StagingDirectory)/sbom-components

    - template: upload-results.yaml
      parameters:
        xaSourcePath: $(System.DefaultWorkingDirectory)/xamarin-android
        artifactName: ${{ parameters.buildResultArtifactName }}
        includeBuildResults: true

    - template: fail-on-issue.yaml
