parameters:
  buildPool: $(1ESWindowsPool)
  buildResultArtifactName: Build Results - Windows
  checkoutCommit: ''
  checkoutPath: ''
  checkoutPersistCredentials: false
  dependsOn: ''
  dependsOnResult: ''
  jobName: win_build_test
  jobDisplayName: Windows > Build & Smoke Test
  repositoryAlias: self
  stageName: win_build_test
  stageDisplayName: Windows

# This stage ensures Windows specific build steps continue to work, and runs unit tests.
stages:
- stage: ${{ parameters.stageName }}
  displayName: ${{ parameters.stageDisplayName }}
  dependsOn: ${{ parameters.dependsOn }}
  ${{ if and(ne(parameters.dependsOn, ''), ne(parameters.dependsOnResult, '')) }}:
    condition: eq(dependencies.${{ parameters.dependsOn }}.result, '${{ parameters.dependsOnResult }}')
  jobs:
  # Check - "Xamarin.Android (Windows > Build & Smoke Test)"
  - job: ${{ parameters.jobName }}
    displayName: ${{ parameters.jobDisplayName }}
    pool: ${{ parameters.buildPool }}
    timeoutInMinutes: 360
    steps:
    - template: sdk-unified/steps/checkout/v1.yml@yaml-templates
      parameters:
        resource: ${{ parameters.repositoryAlias }}
        commit: ${{ parameters.checkoutCommit }}
        path: ${{ parameters.checkoutPath }}
        persistCredentials: ${{ parameters.checkoutPersistCredentials }}

    - template: kill-processes.yaml

    - template: clean.yaml

    - script: |
        echo ##vso[task.setvariable variable=JI_JAVA_HOME]%JAVA_HOME_11_X64%
      displayName: set JI_JAVA_HOME

    - template: use-dot-net.yaml
      parameters:
        remove_dotnet: true

    - task: DotNetCoreCLI@2
      displayName: Prepare Solution
      inputs:
        projects: Xamarin.Android.sln
        arguments: '-c $(XA.Build.Configuration) -t:Prepare --no-restore -p:AutoProvision=true -bl:$(System.DefaultWorkingDirectory)\bin\Build$(XA.Build.Configuration)\dotnet-build-prepare.binlog'

    # Build, pack .nupkgs, and extract workload packs to dotnet preview test directory
    - template: run-dotnet-preview.yaml
      parameters:
        project: Xamarin.Android.sln
        arguments: >-
          -t:BuildDotNet,PackDotNet -c $(XA.Build.Configuration) -v:n
          -bl:$(System.DefaultWorkingDirectory)\bin\Build$(XA.Build.Configuration)\dotnet-build.binlog
        displayName: Build Solution
        continueOnError: false

    - template: install-global-tool.yaml
      parameters:
        toolName: apkdiff
        version: $(ApkDiffToolVersion)

    - template: run-nunit-tests.yaml
      parameters:
        testRunTitle: Smoke MSBuild Tests - Windows Dotnet Build
        testAssembly: $(System.DefaultWorkingDirectory)\bin\Test$(XA.Build.Configuration)\$(DotNetStableTargetFramework)\Xamarin.Android.Build.Tests.dll
        testResultsFile: TestResult-SmokeMSBuildTests-WinDotnetBuild-$(XA.Build.Configuration).xml
        dotNetTestExtraArgs: --filter "TestCategory = SmokeTests"

    - task: BatchScript@1
      displayName: Test dotnet-local.cmd
      inputs:
        filename: dotnet-local.cmd
        arguments: build samples\HelloWorld\HelloWorld\HelloWorld.DotNet.csproj

    - template: upload-results.yaml
      parameters:
        artifactName: ${{ parameters.buildResultArtifactName }}
        includeBuildResults: true

    - template: fail-on-issue.yaml
