parameters:
  buildResultArtifactName: Build Results - macOS
  checkoutCommit: ''
  checkoutPath: 's/xamarin-android'
  checkoutPersistCredentials: false
  dependsOn: ''
  dependsOnResult: ''
  installerArtifactName: $(InstallerArtifactName)
  jobName: mac_build_create_installers
  jobDisplayName: macOS > Build
  nugetArtifactName: $(NuGetArtifactName)
  repositoryAlias: self
  stageName: mac_build
  stageDisplayName: Mac
  testAssembliesArtifactName: $(TestAssembliesArtifactName)
  windowsToolchainPdbArtifactName: $(WindowsToolchainPdbArtifactName)

stages:
- stage: ${{ parameters.stageName }}
  displayName: ${{ parameters.stageDisplayName }}
  dependsOn: ${{ parameters.dependsOn }}
  ${{ if and(ne(parameters.dependsOn, ''), ne(parameters.dependsOnResult, '')) }}:
    condition: eq(dependencies.${{ parameters.dependsOn }}.result, '${{ parameters.dependsOnResult }}')
  jobs:
  # Check - "Xamarin.Android (macOS > Build)"
  - job: ${{ parameters.jobName }}
    displayName: ${{ parameters.jobDisplayName }}
    pool:
      name: $(MacBuildPoolName)
      vmImage: $(MacBuildPoolImage)
      os: macOS
      ${{ if ne(variables['MicroBuildSignType'], 'Real') }}:
        demands: macOS.Name -equals Monterey
    timeoutInMinutes: 240
    cancelTimeoutInMinutes: 5
    workspace:
      clean: all
    steps:
    - template: sdk-unified/steps/checkout/v1.yml@yaml-templates
      parameters:
        resource: ${{ parameters.repositoryAlias }}
        commit: ${{ parameters.checkoutCommit }}
        path: ${{ parameters.checkoutPath }}
        persistCredentials: ${{ parameters.checkoutPersistCredentials }}

    - template: /build-tools/automation/yaml-templates/commercial-build.yaml@self
      parameters:
        installerArtifactName: ${{ parameters.installerArtifactName }}
        nugetArtifactName: ${{ parameters.nugetArtifactName }}
        testAssembliesArtifactName: ${{ parameters.testAssembliesArtifactName }}
        windowsToolchainPdbArtifactName: ${{ parameters.windowsToolchainPdbArtifactName }}

    - template: /build-tools/automation/yaml-templates/upload-results.yaml@self
      parameters:
        xaSourcePath: $(System.DefaultWorkingDirectory)/xamarin-android
        artifactName: ${{ parameters.buildResultArtifactName }}
        includeBuildResults: true
