parameters:
  buildResultArtifactName: Build Results - Windows
  checkoutCommit: ''
  checkoutPath: ''
  checkoutPersistCredentials: false
  dependsOn: ''
  dependsOnResult: ''
  jobName: win_build_test
  jobDisplayName: Windows > Build & Smoke Test
  repositoryAlias: self
  stageName: win_build_test
  stageDisplayName: Windows

# This stage ensures Windows specific build steps continue to work, and runs unit tests.
stages:
- stage: ${{ parameters.stageName }}
  displayName: ${{ parameters.stageDisplayName }}
  dependsOn: ${{ parameters.dependsOn }}
  ${{ if and(ne(parameters.dependsOn, ''), ne(parameters.dependsOnResult, '')) }}:
    condition: eq(dependencies.${{ parameters.dependsOn }}.result, '${{ parameters.dependsOnResult }}')
  jobs:
  # Check - "Xamarin.Android (Windows Windows > Build & Smoke Test)"
  - job: ${{ parameters.jobName }}
    displayName: ${{ parameters.jobDisplayName }}
    pool:
      name: MAUI-1ESPT
      image: $(WindowsPoolImage1ESPT)
      os: windows
    timeoutInMinutes: 240
    steps:
    - template: sdk-unified/steps/checkout/v1.yml@yaml-templates
      parameters:
        resource: ${{ parameters.repositoryAlias }}
        commit: ${{ parameters.checkoutCommit }}
        path: ${{ parameters.checkoutPath }}
        persistCredentials: ${{ parameters.checkoutPersistCredentials }}

    - template: /build-tools/automation/yaml-templates/kill-processes.yaml

    - template: /build-tools/automation/yaml-templates/clean.yaml

    - script: |
        echo ##vso[task.setvariable variable=JI_JAVA_HOME]%JAVA_HOME_17_X64%
      displayName: set JI_JAVA_HOME to $(JAVA_HOME_17_X64)

    - template: /build-tools/automation/yaml-templates/use-dot-net.yaml
      parameters:
        remove_dotnet: true

    # Downgrade the XA .vsix installed into the instance of VS that we are building with so that we don't restore/build against a test version.
    # The VS installer will attempt to resume any failed or partial installation before trying to downgrade Xamarin.Android.
    # VSIXInstaller.exe will exit non-zero when the downgrade attempt is a no-op, so we will allow this step to fail silently.
    - powershell: |
        $vsWhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
        & "$vsWhere" -all -prerelease -latest | Out-Default
        $isLatestVSLaunchable = & "$vsWhere" -all -prerelease -latest -property isLaunchable
        if ($isLatestVSLaunchable -eq 0) {
            $vsPath = & "$vsWhere" -all -prerelease -latest -property installationPath
            Write-Host "Attempting to repair VS instance:" $vsPath
            $vsInstaller = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vs_installer.exe"
            & "$vsInstaller" resume --installPath $vsPath --quiet --norestart | Out-Default
            Write-Host "vs_installer.exe resume attempt complete"
        }
        $vsixInstaller = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe"
        $ts = Get-Date -Format FileDateTimeUniversal
        $log = "xavsixdowngrade-$ts.log"
        $process = Start-Process -NoNewWindow -FilePath $vsixInstaller -ArgumentList "/downgrade:Xamarin.Android.Sdk /admin /quiet /logFile:$log" -Wait -PassThru -RedirectStandardError "err.txt"
        Get-Content "err.txt" | Write-Host
        Get-Content "${env:TEMP}\$log" | Write-Host
        Write-Host "VSInstaller.exe exited with code:" $process.ExitCode
        Remove-Item "${env:TEMP}\$log"
      displayName: downgrade XA to stable
      ignoreLASTEXITCODE: true

    - task: DotNetCoreCLI@2
      displayName: Prepare Solution
      inputs:
        projects: Xamarin.Android.sln
        arguments: '-c $(XA.Build.Configuration) -t:Prepare --no-restore -p:AutoProvision=true -bl:$(System.DefaultWorkingDirectory)\bin\Build$(XA.Build.Configuration)\dotnet-build-prepare.binlog'

    # Build, pack .nupkgs, and extract workload packs to dotnet preview test directory
    - template: /build-tools/automation/yaml-templates/run-dotnet-preview.yaml
      parameters:
        project: Xamarin.Android.sln
        arguments: >-
          -t:BuildDotNet,PackDotNet -c $(XA.Build.Configuration) -v:n
          -bl:$(System.DefaultWorkingDirectory)\bin\Build$(XA.Build.Configuration)\dotnet-build.binlog
        displayName: Build Solution
        continueOnError: false

    - template: /build-tools/automation/yaml-templates/install-dotnet-tool.yaml
      parameters:
        toolName: apkdiff
        version: $(ApkDiffToolVersion)

    - template: /build-tools/automation/yaml-templates/run-nunit-tests.yaml
      parameters:
        testRunTitle: Smoke MSBuild Tests - Windows Dotnet Build
        testAssembly: $(System.DefaultWorkingDirectory)\bin\Test$(XA.Build.Configuration)\$(DotNetStableTargetFramework)\Xamarin.Android.Build.Tests.dll
        dotNetTestExtraArgs: --filter "TestCategory = SmokeTests"

    - task: BatchScript@1
      displayName: Test dotnet-local.cmd
      inputs:
        filename: dotnet-local.cmd
        arguments: build samples\HelloWorld\HelloWorld\HelloWorld.DotNet.csproj

    - template: /build-tools/automation/yaml-templates/upload-results.yaml
      parameters:
        artifactName: ${{ parameters.buildResultArtifactName }}
        includeBuildResults: true

    - template: /build-tools/automation/yaml-templates/fail-on-issue.yaml
