parameters:
  buildResultArtifactName: Build Results - Linux
  checkoutCommit: ''
  checkoutPath: 's/xamarin-android'
  checkoutPersistCredentials: false
  dependsOn: ''
  dependsOnResult: ''
  jobName: linux_build_create_sdk_pack
  jobDisplayName: Linux > Build
  nugetArtifactName: $(LinuxNuGetArtifactName)
  repositoryAlias: self
  stageName: linux_build
  stageDisplayName: Linux

stages:
- stage: ${{ parameters.stageName }}
  displayName: ${{ parameters.stageDisplayName }}
  dependsOn: ${{ parameters.dependsOn }}
  ${{ if and(ne(parameters.dependsOn, ''), ne(parameters.dependsOnResult, '')) }}:
    condition: eq(dependencies.${{ parameters.dependsOn }}.result, '${{ parameters.dependsOnResult }}')
  jobs:
  - job: ${{ parameters.jobName }}
    displayName: ${{ parameters.jobDisplayName }}
    pool:
      name: AzurePipelines-EO
      image: $(LinuxPoolImage1ESPT)
      os: linux
    timeoutInMinutes: 240
    workspace:
      clean: all
    variables:
      CXX: g++-10
      CC: gcc-10
    steps:
    - template: sdk-unified/steps/checkout/v1.yml@yaml-templates
      parameters:
        resource: ${{ parameters.repositoryAlias }}
        commit: ${{ parameters.checkoutCommit }}
        path: ${{ parameters.checkoutPath }}
        persistCredentials: ${{ parameters.checkoutPersistCredentials }}

    # Always checkout a second resource to ensure we are using multi-repo checkout behavior
    #  https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout?view=azure-devops#checkout-path
    - checkout: maui

    - template: /build-tools/automation/yaml-templates/setup-ubuntu.yaml@self

    - ${{ if ne(variables['System.PullRequest.IsFork'], 'True') }}:
      - checkout: monodroid
        clean: true
        submodules: recursive
        path: s/xamarin-android/external/monodroid
        persistCredentials: true

      - script: rm -rf external/monodroid/external/xamarin-android
        workingDirectory: $(System.DefaultWorkingDirectory)/xamarin-android
        displayName: delete external xamarin-android submodule

      - script: make prepare-external-git-dependencies PREPARE_CI=1 CONFIGURATION=$(XA.Build.Configuration)
        workingDirectory: $(System.DefaultWorkingDirectory)/xamarin-android
        displayName: make prepare-external-git-dependencies

    - task: NuGetAuthenticate@1
      displayName: authenticate with azure artifacts
      inputs:
        forceReinstallCredentialProvider: true

    - script: make jenkins PREPARE_CI=1 PREPARE_AUTOPROVISION=1 CONFIGURATION=$(XA.Build.Configuration)
      workingDirectory: $(System.DefaultWorkingDirectory)/xamarin-android
      displayName: make jenkins

    - script: make create-nupkgs CONFIGURATION=$(XA.Build.Configuration)
      workingDirectory: $(System.DefaultWorkingDirectory)/xamarin-android
      displayName: make create-nupkgs

    - script: >
        df -h &&
        mkdir -p $(System.DefaultWorkingDirectory)/xamarin-android/bin/Build$(XA.Build.Configuration)/nuget-linux &&
        ln $(System.DefaultWorkingDirectory)/xamarin-android/bin/Build$(XA.Build.Configuration)/nuget-unsigned/Microsoft.Android.Sdk.Linux*.nupkg
        $(System.DefaultWorkingDirectory)/xamarin-android/bin/Build$(XA.Build.Configuration)/nuget-linux &&
        ln $(System.DefaultWorkingDirectory)/xamarin-android/bin/Build$(XA.Build.Configuration)/nuget-unsigned/SignList.xml
        $(System.DefaultWorkingDirectory)/xamarin-android/bin/Build$(XA.Build.Configuration)/nuget-linux
      workingDirectory: $(System.DefaultWorkingDirectory)/xamarin-android
      displayName: copy linux sdk

    - task: 1ES.PublishPipelineArtifact@1
      displayName: upload linux sdk
      inputs:
        artifactName: ${{ parameters.nugetArtifactName }}
        targetPath: $(System.DefaultWorkingDirectory)/xamarin-android/bin/Build$(XA.Build.Configuration)/nuget-linux

    - template: /build-tools/automation/yaml-templates/upload-results.yaml@self
      parameters:
        xaSourcePath: $(System.DefaultWorkingDirectory)/xamarin-android
        artifactName: ${{ parameters.buildResultArtifactName }}
        includeBuildResults: true

    - template: /build-tools/automation/yaml-templates/fail-on-issue.yaml@self
