parameters:
  buildResultArtifactName: Build Results - Linux
  checkoutCommit: ''
  checkoutPath: 's/android'
  xaSourcePath: $(System.DefaultWorkingDirectory)/android
  checkoutPersistCredentials: false
  dependsOn: ''
  dependsOnResult: ''
  jobName: linux_build_create_sdk_pack
  jobDisplayName: Linux > Build
  nugetArtifactName: $(LinuxNuGetArtifactName)
  repositoryAlias: self
  stageName: linux_build
  stageDisplayName: Linux
  use1ESTemplate: true

stages:
- stage: ${{ parameters.stageName }}
  displayName: ${{ parameters.stageDisplayName }}
  dependsOn: ${{ parameters.dependsOn }}
  ${{ if and(ne(parameters.dependsOn, ''), ne(parameters.dependsOnResult, '')) }}:
    condition: eq(dependencies.${{ parameters.dependsOn }}.result, '${{ parameters.dependsOnResult }}')
  jobs:
  # Check - "Xamarin.Android (Linux Linux > Build)"
  - job: ${{ parameters.jobName }}
    displayName: ${{ parameters.jobDisplayName }}
    pool:
      name: MAUI-1ESPT
      image: $(LinuxPoolImage1ESPT)
      os: linux
    timeoutInMinutes: 240
    workspace:
      clean: all
    variables:
      CXX: g++-10
      CC: gcc-10
    ${{ if eq(parameters.use1ESTemplate, true) }}:
      templateContext:
        outputs:
        - output: pipelineArtifact
          displayName: upload linux sdk
          artifactName: ${{ parameters.nugetArtifactName }}
          targetPath: ${{ parameters.xaSourcePath }}/bin/Build$(XA.Build.Configuration)/nuget-linux
        - output: pipelineArtifact
          displayName: upload linux sdk symbols
          artifactName: ${{ parameters.nugetArtifactName }}-symbols
          targetPath: ${{ parameters.xaSourcePath }}/bin/Build$(XA.Build.Configuration)/nuget-linux-symbols
    steps:
    - template: sdk-unified/steps/checkout/v1.yml@yaml-templates
      parameters:
        resource: ${{ parameters.repositoryAlias }}
        commit: ${{ parameters.checkoutCommit }}

    # Always checkout a second resource to ensure we are using multi-repo checkout behavior
    #  https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout?view=azure-devops#checkout-path
    - checkout: maui

    - ${{ if ne(variables['System.PullRequest.IsFork'], 'True') }}:
      - checkout: android-platform-support
        clean: true
        submodules: recursive
        path: s/android/external/android-platform-support
        persistCredentials: true

    - template: /build-tools/automation/yaml-templates/build-linux-steps.yaml
      parameters:
        buildResultArtifactName: ${{ parameters.buildResultArtifactName }}
        xaSourcePath: ${{ parameters.xaSourcePath }}
        nugetArtifactName: ${{ parameters.nugetArtifactName }}
        use1ESTemplate: ${{ parameters.use1ESTemplate }}

    - ${{ if ne(variables['System.PullRequest.IsFork'], 'True') }}:
      - script: make prepare-external-git-dependencies PREPARE_CI=1 CONFIGURATION=$(XA.Build.Configuration)
        workingDirectory: ${{ parameters.xaSourcePath }}
        displayName: make prepare-external-git-dependencies
