parameters:
  buildResultArtifactName: Build Results - Windows
  checkoutCommit: ''
  checkoutPath: ''
  checkoutPersistCredentials: false
  dependsOn: ''
  dependsOnResult: ''
  jobName: win_build_test
  jobDisplayName: Windows > Build & Smoke Test
  repositoryAlias: self
  stageName: win_build_test
  stageDisplayName: Windows
  use1ESTemplate: true

# This stage ensures Windows specific build steps continue to work, and runs unit tests.
stages:
- stage: ${{ parameters.stageName }}
  displayName: ${{ parameters.stageDisplayName }}
  dependsOn: ${{ parameters.dependsOn }}
  ${{ if and(ne(parameters.dependsOn, ''), ne(parameters.dependsOnResult, '')) }}:
    condition: eq(dependencies.${{ parameters.dependsOn }}.result, '${{ parameters.dependsOnResult }}')
  jobs:
  # Check - "Xamarin.Android (Windows Windows > Build & Smoke Test)"
  - job: ${{ parameters.jobName }}
    displayName: ${{ parameters.jobDisplayName }}
    pool:
      name: MAUI-1ESPT
      image: $(WindowsPoolImage1ESPT)
      os: windows
    timeoutInMinutes: 240
    steps:
    - template: sdk-unified/steps/checkout/v1.yml@yaml-templates
      parameters:
        resource: ${{ parameters.repositoryAlias }}
        commit: ${{ parameters.checkoutCommit }}

    - template: /build-tools/automation/yaml-templates/build-windows-steps.yaml
      parameters:
        buildResultArtifactName: ${{ parameters.buildResultArtifactName }}
        use1ESTemplate: ${{ parameters.use1ESTemplate }}
