parameters:
  buildResultArtifactName: Build Results - Windows
  checkoutCommit: ''
  checkoutPath: ''
  checkoutPersistCredentials: false
  dependsOn: ''
  dependsOnResult: ''
  jobName: win_build_test
  jobDisplayName: Windows > Build & Smoke Test
  repositoryAlias: self
  stageName: win_build_test
  stageDisplayName: Windows

# This stage ensures Windows specific build steps continue to work, and runs unit tests.
stages:
- stage: ${{ parameters.stageName }}
  displayName: ${{ parameters.stageDisplayName }}
  dependsOn: ${{ parameters.dependsOn }}
  ${{ if and(ne(parameters.dependsOn, ''), ne(parameters.dependsOnResult, '')) }}:
    condition: eq(dependencies.${{ parameters.dependsOn }}.result, '${{ parameters.dependsOnResult }}')
  jobs:
  # Check - "Xamarin.Android (Windows Windows > Build & Smoke Test)"
  - job: ${{ parameters.jobName }}
    displayName: ${{ parameters.jobDisplayName }}
    pool:
      name: MAUI-1ESPT
      image: $(WindowsPoolImage1ESPT)
      os: windows
    timeoutInMinutes: 240
    steps:
    - template: sdk-unified/steps/checkout/v1.yml@yaml-templates
      parameters:
        resource: ${{ parameters.repositoryAlias }}
        commit: ${{ parameters.checkoutCommit }}
        path: ${{ parameters.checkoutPath }}
        persistCredentials: ${{ parameters.checkoutPersistCredentials }}

    - template: /build-tools/automation/yaml-templates/kill-processes.yaml

    - template: /build-tools/automation/yaml-templates/clean.yaml

    - template: /build-tools/automation/yaml-templates/setup-jdk-variables.yaml
      parameters:
        useAgentJdkPath: false
        jdkMajorVersion: $(LatestJavaSdkMajorVersion)

    - template: /build-tools/automation/yaml-templates/use-dot-net.yaml
      parameters:
        remove_dotnet: true

    - script: systeminfo
      displayName: Display system information

    - task: DotNetCoreCLI@2
      displayName: Prepare Solution
      inputs:
        projects: Xamarin.Android.sln
        arguments: '-c $(XA.Build.Configuration) -t:Prepare --no-restore -p:AutoProvision=true -bl:$(System.DefaultWorkingDirectory)\bin\Build$(XA.Build.Configuration)\dotnet-build-prepare.binlog'

    - pwsh: >
        & "C:\Android\android-sdk\emulator\emulator.exe" -accel-check
      displayName: emulator -accel-check

    - task: DotNetCoreCLI@2
      displayName: install emulator
      inputs:
        projects: $(System.DefaultWorkingDirectory)/src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Emulator.csproj
        arguments: >-
          -c $(XA.Build.Configuration) -t:InstallAvdImage
          -p:TestAvdApiLevel=34
          -p:TestAvdAbi=x86_64
          -p:TestAvdType=default
          -bl:$(System.DefaultWorkingDirectory)/bin/Test$(XA.Build.Configuration)/install-emulator-34.binlog

    - task: BatchScript@1
      inputs:
        filename: C:\Android\android-sdk\cmdline-tools\12.0\bin\avdmanager.bat
        arguments: create avd --abi x86_64 --force --name XamarinAndroidTestRunner34-x86_64 --package "system-images;android-34;default;x86_64"

    - pwsh: >
        & "C:\Android\android-sdk\emulator\emulator.exe" -no-window -no-boot-anim -debug -verbose -avd XamarinAndroidTestRunner34-x86_64
      displayName: start avd

    - template: /build-tools/automation/yaml-templates/start-stop-emulator.yaml
      parameters:
        specificImage: true
        avdApiLevel: 34
        avdAbi: x86_64
        avdType: google_apis
        #emulatorMSBuildArgs: -p:TestAvdShowWindow=true

    # # Build Xamarin.Android and configure local workloads to test improved local build loop
    # - template: /build-tools/automation/yaml-templates/run-dotnet-preview.yaml
    #   parameters:
    #     project: Xamarin.Android.sln
    #     arguments: >-
    #       -t:BuildDotNet -c $(XA.Build.Configuration) -v:n
    #       -bl:$(System.DefaultWorkingDirectory)\bin\Build$(XA.Build.Configuration)\dotnet-build.binlog
    #     displayName: Build Solution
    #     continueOnError: false

    # - template: /build-tools/automation/yaml-templates/run-dotnet-preview.yaml
    #   parameters:
    #     project: build-tools/create-packs/Microsoft.Android.Sdk.proj
    #     arguments: >-
    #       -t:ConfigureLocalWorkload -c $(XA.Build.Configuration) -v:n -p:RunningOnCI=false
    #       -bl:$(System.DefaultWorkingDirectory)\bin\Build$(XA.Build.Configuration)\local-workload.binlog
    #     displayName: Run ConfigureLocalWorkload target
    #     continueOnError: false

    # - template: /build-tools/automation/yaml-templates/install-dotnet-tool.yaml
    #   parameters:
    #     toolName: apkdiff
    #     version: $(ApkDiffToolVersion)

    # - template: /build-tools/automation/yaml-templates/run-nunit-tests.yaml
    #   parameters:
    #     testRunTitle: Smoke MSBuild Tests - Windows Dotnet Build
    #     testAssembly: $(System.DefaultWorkingDirectory)\bin\Test$(XA.Build.Configuration)\$(DotNetStableTargetFramework)\Xamarin.Android.Build.Tests.dll
    #     dotNetTestExtraArgs: --filter "TestCategory = SmokeTests"

    # - template: /build-tools/automation/yaml-templates/run-dotnet-preview.yaml@self
    #   parameters:
    #     command: test
    #     project: src/Microsoft.Android.Sdk.Analysis/Tests/Microsoft.Android.Sdk.Analysis.Tests.csproj 
    #     arguments: -c $(XA.Build.Configuration)
    #     displayName: Test Microsoft.Android.Sdk.Analysis $(XA.Build.Configuration)
    #     continueOnError: false

    # - task: BatchScript@1
    #   displayName: Test dotnet-local.cmd - create template
    #   inputs:
    #     filename: dotnet-local.cmd
    #     arguments: new android -o $(Build.StagingDirectory)/LocalWorkloadTest

    # - task: BatchScript@1
    #   displayName: Test dotnet-local.cmd - build template
    #   inputs:
    #     filename: dotnet-local.cmd
    #     arguments: build -v:n $(Build.StagingDirectory)/LocalWorkloadTest

    # # Pack .nupkgs and extract workload packs to dotnet preview test directory
    # - template: /build-tools/automation/yaml-templates/run-dotnet-preview.yaml
    #   parameters:
    #     project: Xamarin.Android.sln
    #     arguments: >-
    #       -t:PackDotNet -c $(XA.Build.Configuration) -v:n
    #       -bl:$(System.DefaultWorkingDirectory)\bin\Build$(XA.Build.Configuration)\dotnet-pack.binlog
    #     displayName: Test PackDotNet

    - template: /build-tools/automation/yaml-templates/upload-results.yaml
      parameters:
        artifactName: ${{ parameters.buildResultArtifactName }}
        includeBuildResults: true

    - template: /build-tools/automation/yaml-templates/fail-on-dirty-tree.yaml

    - template: /build-tools/automation/yaml-templates/fail-on-issue.yaml
