# Public version of build-windows stage template - no private repo references
# Used by the public pipeline running on dnceng-public

parameters:
  buildResultArtifactName: Build Results - Windows
  checkoutCommit: ''
  checkoutPath: ''
  checkoutPersistCredentials: false
  dependsOn: ''
  dependsOnResult: ''
  jobName: win_build_test
  jobDisplayName: Windows > Build & Smoke Test
  repositoryAlias: self
  stageName: win_build_test
  stageDisplayName: Windows
  use1ESTemplate: false

# This stage ensures Windows specific build steps continue to work, and runs unit tests.
stages:
- stage: ${{ parameters.stageName }}
  displayName: ${{ parameters.stageDisplayName }}
  dependsOn: ${{ parameters.dependsOn }}
  ${{ if and(ne(parameters.dependsOn, ''), ne(parameters.dependsOnResult, '')) }}:
    condition: eq(dependencies.${{ parameters.dependsOn }}.result, '${{ parameters.dependsOnResult }}')
  jobs:
  # Check - "Xamarin.Android (Windows Windows > Build & Smoke Test)"
  - job: ${{ parameters.jobName }}
    displayName: ${{ parameters.jobDisplayName }}
    pool:
      name: Azure Pipelines
      vmImage: $(WindowsPoolImage)
      os: windows
    timeoutInMinutes: 240
    steps:
    - checkout: ${{ parameters.repositoryAlias }}
      ${{ if ne(parameters.checkoutCommit, '') }}:
        ref: ${{ parameters.checkoutCommit }}
      path: ${{ parameters.checkoutPath }}
      persistCredentials: ${{ parameters.checkoutPersistCredentials }}

    - template: /build-tools/automation/yaml-templates/build-windows-steps.yaml
      parameters:
        buildResultArtifactName: ${{ parameters.buildResultArtifactName }}
        use1ESTemplate: false
