parameters:
  buildResultArtifactName: Build Results - macOS
  checkoutCommit: ''
  checkoutPath: 's/android'
  xaSourcePath: $(System.DefaultWorkingDirectory)/android
  checkoutPersistCredentials: false
  dependsOn: ''
  dependsOnResult: ''
  installerArtifactName: $(InstallerArtifactName)
  jobName: mac_build_create_installers
  jobDisplayName: macOS > Build
  nugetArtifactName: $(NuGetArtifactName)
  repositoryAlias: self
  stageName: mac_build
  stageDisplayName: Mac
  testAssembliesArtifactName: $(TestAssembliesArtifactName)
  windowsToolchainPdbArtifactName: $(WindowsToolchainPdbArtifactName)
  use1ESTemplate: true

stages:
- stage: ${{ parameters.stageName }}
  displayName: ${{ parameters.stageDisplayName }}
  dependsOn: ${{ parameters.dependsOn }}
  ${{ if and(ne(parameters.dependsOn, ''), ne(parameters.dependsOnResult, '')) }}:
    condition: eq(dependencies.${{ parameters.dependsOn }}.result, '${{ parameters.dependsOnResult }}')
  jobs:
  # Check - "Xamarin.Android (Mac macOS > Build)"
  - job: ${{ parameters.jobName }}
    displayName: ${{ parameters.jobDisplayName }}
    pool:
      ${{ if or(eq(variables['Build.DefinitionName'], 'Xamarin.Android-PR'), eq(variables['Build.DefinitionName'], 'Xamarin.Android Nightly')) }}:
        name: $(SharedMacPool)
        demands:
        - macOS.Name -equals $(SharedMacName)
        - Agent.OSArchitecture -equals $(SharedMacArch)
      ${{ else }}:
        name: Azure Pipelines
        vmImage: $(HostedMacImage)
      os: macOS
    timeoutInMinutes: 240
    cancelTimeoutInMinutes: 5
    workspace:
      clean: all
    ${{ if eq(parameters.use1ESTemplate, true) }}:
      templateContext:
        outputParentDirectory: ${{ parameters.xaSourcePath }}/bin
        outputs:
        - output: pipelineArtifact
          displayName: upload nupkgs
          artifactName: ${{ parameters.nugetArtifactName }}
          targetPath: ${{ parameters.xaSourcePath }}/bin/Build$(XA.Build.Configuration)/nuget-unsigned
        - output: pipelineArtifact
          displayName: upload symbols nupkgs
          artifactName: ${{ parameters.nugetArtifactName }}-symbols
          targetPath: ${{ parameters.xaSourcePath }}/bin/Build$(XA.Build.Configuration)/nuget-unsigned-symbols
        - output: pipelineArtifact
          displayName: upload Windows toolchain pdb files
          artifactName: ${{ parameters.windowsToolchainPdbArtifactName }}
          targetPath: ${{ parameters.xaSourcePath }}/bin/Build$(XA.Build.Configuration)/windows-toolchain-pdb
        - output: pipelineArtifact
          displayName: upload test assemblies
          artifactName: ${{ parameters.testAssembliesArtifactName }}
          targetPath: ${{ parameters.xaSourcePath }}/bin/Test$(XA.Build.Configuration)
          sbomEnabled: false
        - output: pipelineArtifact
          displayName: upload build tools inventory
          artifactName: AndroidBuildToolsInventory
          targetPath: ${{ parameters.xaSourcePath }}/bin/Build$(XA.Build.Configuration)/buildtoolsinventory.csv
          sbomEnabled: false
    steps:
    - ${{ if eq(parameters.use1ESTemplate, true) }}:
      - template: sdk-unified/steps/checkout/v1.yml@yaml-templates
        parameters:
          resource: ${{ parameters.repositoryAlias }}
          commit: ${{ parameters.checkoutCommit }}
          path: ${{ parameters.checkoutPath }}
          persistCredentials: ${{ parameters.checkoutPersistCredentials }}
    - ${{ if ne(parameters.use1ESTemplate, true) }}:
      - checkout: ${{ parameters.repositoryAlias }}
        ${{ if ne(parameters.checkoutCommit, '') }}:
          ref: ${{ parameters.checkoutCommit }}
        path: ${{ parameters.checkoutPath }}
        persistCredentials: ${{ parameters.checkoutPersistCredentials }}

    # Always checkout a second resource to ensure we are using multi-repo checkout behavior
    #  https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout?view=azure-devops#checkout-path
    - ${{ if eq(parameters.use1ESTemplate, true) }}:
      - checkout: maui

    - ${{ if ne(variables['System.PullRequest.IsFork'], 'True') }}:
      - checkout: android-platform-support
        submodules: recursive
        path: s/android/external/android-platform-support
        persistCredentials: true

      - script: make prepare-external-git-dependencies PREPARE_CI=1 CONFIGURATION=$(XA.Build.Configuration)
        workingDirectory: ${{ parameters.xaSourcePath }}
        displayName: make prepare-external-git-dependencies

    - task: CodeQL3000Init@0
      displayName: CodeQL 3000 Init
      condition: and(succeeded(), eq(variables['Codeql.Enabled'], 'true'), eq(variables['Build.SourceBranch'], 'refs/heads/main'))

    # Call the shared build steps template
    - template: /build-tools/automation/yaml-templates/build-macos-steps.yaml
      parameters:
        xaSourcePath: ${{ parameters.xaSourcePath }}
        installerArtifactName: ${{ parameters.installerArtifactName }}
        nugetArtifactName: ${{ parameters.nugetArtifactName }}
        testAssembliesArtifactName: ${{ parameters.testAssembliesArtifactName }}
        windowsToolchainPdbArtifactName: ${{ parameters.windowsToolchainPdbArtifactName }}
        buildResultArtifactName: ${{ parameters.buildResultArtifactName }}
        use1ESTemplate: ${{ parameters.use1ESTemplate }}

    - task: CodeQL3000Finalize@0
      displayName: CodeQL 3000 Finalize
      condition: and(succeededOrFailed(), eq(variables['Codeql.Enabled'], 'true'), eq(variables['Build.SourceBranch'], 'refs/heads/main'))

    - task: DotNetCoreCLI@2
      displayName: macOS signing - add runtime entitlements
      condition: and(succeeded(), and(startsWith(variables['Build.SourceBranch'], 'refs/heads/release/'), ne(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.DefinitionName'], 'Xamarin.Android')))
      inputs:
        projects: ${{ parameters.xaSourcePath }}/build-tools/installers/sign-content.proj
        arguments: >-
          /t:AddMachOEntitlements /p:Configuration=$(XA.Build.Configuration)
          /bl:${{ parameters.xaSourcePath }}/bin/Build$(XA.Build.Configuration)/sign-content.binlog
