# Runs a test or set of tests on an emulator running on macOS

parameters:
  emulatorMSBuildArgs: ''
  jobName: CheckTimeZoneInfoIsCorrectNode1
  jobTimeout: 360
  testSteps: []

jobs:
  - job: mac_${{ parameters.jobName }}_tests
    displayName: ${{ parameters.jobName }} Emulator Tests
    pool:
      vmImage: $(HostedMacImage)
    timeoutInMinutes: ${{ parameters.jobTimeout }}
    workspace:
      clean: all
    steps:
    - template: setup-test-environment.yaml
      parameters:
        installLegacyDotNet: false
        restoreNUnitConsole: false
        updateMono: false
        xaprepareScenario: EmulatorTestDependencies

    - task: DownloadPipelineArtifact@2
      inputs:
        artifactName: $(TestAssembliesArtifactName)
        downloadPath: $(System.DefaultWorkingDirectory)/bin/Test$(XA.Build.Configuration)

    - template: start-stop-emulator.yaml
      parameters:
        emulatorMSBuildArgs: ${{ parameters.emulatorMSBuildArgs }}

    - ${{ parameters.testSteps }}

    - template: upload-results.yaml
      parameters:
        artifactName: Test Results - ${{ parameters.jobName }} With Emulator - macOS

    - template: fail-on-issue.yaml
