# Runs MSBuild tests against a device running on macOS

parameters:
  node_id: 0
  job_name: ''
  job_suffix: ''
  nunit_categories: ''
  target_framework: 'net472'
  run_extra_tests: false
  condition: succeededOrFailed()

jobs:
  - job: ${{ parameters.job_name }}
    displayName: MSBuild ${{ parameters.job_suffix }} - Mac-${{ parameters.node_id }}
    pool: $(HostedMac)
    condition: ${{ parameters.condition }}
    timeoutInMinutes: 180
    cancelTimeoutInMinutes: 5
    workspace:
      clean: all
    variables:
      UseDotNet: ${{ eq(parameters.target_framework, 'netcoreapp3.1') }}
    steps:
    - template: setup-test-environment.yaml

    - task: DownloadPipelineArtifact@1
      inputs:
        artifactName: $(TestAssembliesArtifactName)
        downloadPath: $(System.DefaultWorkingDirectory)/bin/Test$(XA.Build.Configuration)

    - task: DownloadPipelineArtifact@1
      inputs:
        artifactName: $(NuGetArtifactName)
        downloadPath: $(System.DefaultWorkingDirectory)/bin/Build$(XA.Build.Configuration)/$(NuGetArtifactName)

    - template: run-nunit-tests.yaml
      parameters:
        useDotNet: $(UseDotNet)
        testRunTitle: Xamarin.Android.Build.Tests - macOS-${{ parameters.node_id }} - ${{ parameters.job_suffix }}
        testAssembly: $(System.DefaultWorkingDirectory)/bin/Test$(XA.Build.Configuration)/${{ parameters.target_framework }}/Xamarin.Android.Build.Tests.dll
        nunitConsoleExtraArgs: --where "cat == Node-${{ parameters.node_id }} ${{ parameters.nunit_categories }}"
        dotNetTestExtraArgs: --filter "TestCategory = Node-${{ parameters.node_id }} ${{ parameters.nunit_categories }}"
        testResultsFile: TestResult-MSBuildTests-${{ parameters.job_name }}-$(XA.Build.Configuration).xml

    # Only run these tests on node 2
    - ${{ if eq(parameters.run_extra_tests, true) }}:
      - template: run-nunit-tests.yaml
        parameters:
          useDotNet: $(UseDotNet)
          testRunTitle: Xamarin.Android.Build.Tests.Commercial - macOS
          testAssembly: $(System.DefaultWorkingDirectory)/bin/Test$(XA.Build.Configuration)/Xamarin.Android.Build.Tests.Commercial.dll
          testResultsFile: TestResult-MSBuildTestsCommercial-macOS-$(XA.Build.Configuration).xml
          
      - template: run-nunit-tests.yaml
        parameters:
          useDotNet: $(UseDotNet)
          testRunTitle: Xamarin.Android.Build.Tests - macOS - No Node
          testAssembly: $(System.DefaultWorkingDirectory)/bin/Test$(XA.Build.Configuration)/${{ parameters.target_framework }}/Xamarin.Android.Build.Tests.dll
          nunitConsoleExtraArgs: --where "cat != Node-1 && cat != Node-2 && cat != Node-3"
          dotNetTestExtraArgs: --filter "TestCategory != Node-1 & TestCategory != Node-2 & TestCategory != Node-3"
          testResultsFile: TestResult-MSBuildTests-macOS-NoNode-$(XA.Build.Configuration).xml

    - template: upload-results.yaml
      parameters:
        artifactName: Test Results - MSBuild - Mac-${{ parameters.node_id }} - ${{ parameters.job_suffix }}

    - template: fail-on-issue.yaml
