# Runs MSBuild tests against a device running on Windows

parameters:
  node_id: 0

jobs:
  - job: win_msbuild_tests${{ parameters.node_id }}
    displayName: MSBuild - Windows-${{ parameters.node_id }}
    pool: $(VSEngWinVS2019)
    timeoutInMinutes: 180
    cancelTimeoutInMinutes: 5
    variables:
      VSINSTALLDIR: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
    steps:

    - template: kill-processes.yaml

    - template: clean.yaml

    - template: setup-test-environment.yaml
      parameters:
        provisionExtraArgs: -vv PROVISIONATOR_VISUALSTUDIO_LOCATION="$(VSINSTALLDIR)" -f

    - task: DownloadPipelineArtifact@1
      inputs:
        artifactName: $(TestAssembliesArtifactName)
        downloadPath: $(System.DefaultWorkingDirectory)\bin\Test$(XA.Build.Configuration)

    - task: DownloadPipelineArtifact@1
      inputs:
        artifactName: $(NuGetArtifactName)
        downloadPath: $(System.DefaultWorkingDirectory)/bin/Build$(XA.Build.Configuration)

    # Limit the amount of worker threads used to run these tests in parallel to half of what is currently available (8) on the Windows pool.
    # Using all available cores seems to occasionally bog down our machines and cause parallel test execution to slow down dramatically.
    - template: run-nunit-tests.yaml
      parameters:
        testRunTitle: Xamarin.Android.Build.Tests - Windows-${{ parameters.node_id }}
        testAssembly: $(System.DefaultWorkingDirectory)\bin\Test$(XA.Build.Configuration)\Xamarin.Android.Build.Tests.dll
        nunitConsoleExtraArgs: --workers=4 --where "cat == Node-${{ parameters.node_id }}"
        testResultsFile: TestResult-MSBuildTests-Windows-Node${{ parameters.node_id }}-$(XA.Build.Configuration).xml

    # Only run these tests on node 2
    - ${{ if eq(parameters.node_id, 2) }}:
      - template: run-nunit-tests.yaml
        parameters:
          testRunTitle: Xamarin.Android.Build.Tests.Commercial - Windows
          testAssembly: $(System.DefaultWorkingDirectory)\bin\Test$(XA.Build.Configuration)\Xamarin.Android.Build.Tests.Commercial.dll
          testResultsFile: TestResult-MSBuildTestsCommercial-Windows-$(XA.Build.Configuration).xml
          
      - template: run-nunit-tests.yaml
        parameters:
          testRunTitle: Xamarin.Android.Build.Tests - Windows - No Node
          testAssembly: $(System.DefaultWorkingDirectory)\bin\Test$(XA.Build.Configuration)\Xamarin.Android.Build.Tests.dll
          nunitConsoleExtraArgs: --workers=4 --where "cat != Node-1 && cat != Node-2 && cat != Node-3"
          testResultsFile: TestResult-MSBuildTests-Windows-Node${{ parameters.node_id }}-$(XA.Build.Configuration).xml

    - template: upload-results.yaml
      parameters:
        artifactName: Test Results - MSBuild - Windows-${{ parameters.node_id }}
