parameters:
  configuration: $(XA.Build.Configuration)
  provisionExtraArgs: -vv -f

steps:
- template: run-installer.yaml
  parameters:
    provisionExtraArgs: ${{ parameters.provisionExtraArgs }}

- task: UseDotNet@2
  displayName: install .NET Core $(DotNetCoreVersion)
  inputs:
    version: $(DotNetCoreVersion)

# Restore solutions for Xamarin.Android.Tools.sln, Xamarin.Android.sln, and Xamarin.Android-Tests.sln
- task: NuGetToolInstaller@0
  inputs:
    versionSpec: 5.x
    
- task: NuGetCommand@2
  inputs:
    command: 'custom'
    arguments: 'install NUnit.ConsoleRunner -Version 3.9.0 -OutputDirectory packages'
