# Runs MSBuild tests against a device running on macOS

parameters:
  stageName: msbuilddevice_tests
  job_name: 'mac_dotnetdevice_tests'
  dependsOn: mac_build
  agent_count: 8
  stageCondition: succeeded()
  stagePrefix: ''
  xaSourcePath: $(System.DefaultWorkingDirectory)
  repositoryAlias: 'self'
  commit: ''
  usesCleanImages: true
  shouldFailOnIssue: true
  emulatorStartContinueOnError: false

stages:
- stage: ${{ parameters.stageName }}
  displayName: ${{ parameters.stagePrefix }}MSBuild Emulator Tests
  dependsOn: ${{ parameters.dependsOn }}
  condition: ${{ parameters.stageCondition }}
  jobs:
  - job: ${{ parameters.job_name }}
    strategy:
      parallel: ${{ parameters.agent_count }}
    displayName: "macOS > Tests > MSBuild+Emulator"
    pool:
      vmImage: $(HostedMacImage)
    timeoutInMinutes: 180
    cancelTimeoutInMinutes: 5
    workspace:
      clean: all
    steps:
    - template: setup-test-environment.yaml@self
      parameters:
        installTestSlicer: true
        installApkDiff: false
        installLegacyXamarinAndroid: true
        updateMono: true
        xaSourcePath: ${{ parameters.xaSourcePath }}
        repositoryAlias: ${{ parameters.repositoryAlias }}
        commit: ${{ parameters.commit }}
        xaprepareScenario: EmulatorTestDependencies

    - task: DownloadPipelineArtifact@2
      inputs:
        artifactName: $(TestAssembliesArtifactName)
        downloadPath: ${{ parameters.xaSourcePath }}/bin/Test$(XA.Build.Configuration)

    - template: start-stop-emulator.yaml@self
      parameters:
        xaSourcePath: ${{ parameters.xaSourcePath }}
        startContinueOnError: ${{ parameters.emulatorStartContinueOnError }}

    - template: run-sliced-nunit-tests.yaml@self
      parameters:
        testAssembly: ${{ parameters.xaSourcePath }}/bin/Test$(XA.Build.Configuration)/MSBuildDeviceIntegration/$(DotNetStableTargetFramework)/MSBuildDeviceIntegration.dll
        testFilter: $(ExcludedNightlyNUnitCategories)
        testRunTitle: MSBuildDeviceIntegration On Device - macOS

    - ${{ if ne(parameters.usesCleanImages, true) }}:
      - template: start-stop-emulator.yaml@self
        parameters:
          command: stop
          xaSourcePath: ${{ parameters.xaSourcePath }}

    - template: upload-results.yaml@self
      parameters:
        artifactName: Test Results - MSBuild With Emulator - macOS-$(System.JobPositionInPhase)
        xaSourcePath: ${{ parameters.xaSourcePath }}

    - template: fail-on-issue.yaml@self
      parameters:
        condition: ${{ parameters.shouldFailOnIssue }}

  - job: wear_tests
    displayName: macOS > Tests > WearOS 
    timeoutInMinutes: 180
    cancelTimeoutInMinutes: 2
    strategy:
      parallel: 1
    variables:
      avdApiLevel: 30
      avdAbi: x86
      avdType: android-wear
      deviceName: wear_square
      androidSdkPlatforms: 34
    pool:
      vmImage: $(HostedMacImage)
    workspace:
      clean: all
    steps:
    - template: setup-test-environment.yaml@self
      parameters:
        installTestSlicer: true
        installApkDiff: false
        xaSourcePath: ${{ parameters.xaSourcePath }}
        repositoryAlias: ${{ parameters.repositoryAlias }}
        commit: ${{ parameters.commit }}
        xaprepareScenario: EmulatorTestDependencies

    - task: DownloadPipelineArtifact@2
      inputs:
        artifactName: $(TestAssembliesArtifactName)
        downloadPath: ${{ parameters.xaSourcePath }}/bin/Test$(XA.Build.Configuration)

    - template: start-stop-emulator.yaml@self
      parameters:
        specificImage: true
        deviceName: $(deviceName)
        avdApiLevel: $(avdApiLevel)
        avdAbi: $(avdAbi)
        avdType: $(avdType)
        xaSourcePath: ${{ parameters.xaSourcePath }}
        startContinueOnError: ${{ parameters.emulatorStartContinueOnError }}

    - template: run-sliced-nunit-tests.yaml@self
      parameters:
        testRunTitle: WearOS On Device - macOS
        testAssembly: ${{ parameters.xaSourcePath }}/bin/Test$(XA.Build.Configuration)/MSBuildDeviceIntegration/$(DotNetStableTargetFramework)/MSBuildDeviceIntegration.dll
        testFilter: cat = WearOS
        xaSourcePath: ${{ parameters.xaSourcePath }}

    - ${{ if ne(parameters.usesCleanImages, true) }}:
      - template: start-stop-emulator.yaml@self
        parameters:
          command: stop
          specificImage: true
          deviceName: $(deviceName)
          avdApiLevel: $(avdApiLevel)
          avdAbi: $(avdAbi)
          avdType: $(avdType)
          xaSourcePath: ${{ parameters.xaSourcePath }}

    - template: upload-results.yaml@self
      parameters:
        configuration: $(XA.Build.Configuration)
        artifactName: Test Results - Emulator $(avdApiLevel)-$(avdAbi)-$(avdType) - macOS
        xaSourcePath: ${{ parameters.xaSourcePath }}

    - template: fail-on-issue.yaml@self
      parameters:
        condition: ${{ parameters.shouldFailOnIssue }}
