# Runs MSBuild tests that do not require devices on Mac/Windows

parameters:
  stageName: msbuild_dotnet
  stageCondition: succeeded()
  dependsOn: mac_build
  stagePrefix: ''
  xaSourcePath: $(System.DefaultWorkingDirectory)
  repositoryAlias: 'self'
  commit: ''
  shouldFailOnIssue: true
  use1ESTemplate: true

stages:
- stage: ${{ parameters.stageName }}
  displayName: ${{ parameters.stagePrefix }}MSBuild Tests
  dependsOn: ${{ parameters.dependsOn }}
  condition: ${{ parameters.stageCondition }}
  jobs:
  - template: /build-tools/automation/yaml-templates/run-msbuild-tests.yaml
    parameters:
      testOS: macOS
      jobName: mac_msbuild_tests
      jobDisplayName: macOS > Tests > MSBuild
      agentCount: 10
      xaSourcePath: ${{ parameters.xaSourcePath }}
      repositoryAlias: ${{ parameters.repositoryAlias }}
      commit: ${{ parameters.commit }}
      shouldFailOnIssue: ${{ parameters.shouldFailOnIssue }}
      use1ESTemplate: ${{ parameters.use1ESTemplate }}

  - template: /build-tools/automation/yaml-templates/run-msbuild-tests.yaml
    parameters:
      testOS: Windows
      jobName: win_msbuild_tests
      jobDisplayName: Windows > Tests > MSBuild
      agentCount: 8
      xaSourcePath: ${{ parameters.xaSourcePath }}
      repositoryAlias: ${{ parameters.repositoryAlias }}
      commit: ${{ parameters.commit }}
      shouldFailOnIssue: ${{ parameters.shouldFailOnIssue }}
      use1ESTemplate: ${{ parameters.use1ESTemplate }}

  - job: unit_tests_mac
    displayName: macOS > Unit Tests
    pool:
      name: Azure Pipelines
      vmImage: macOS-14
      os: macOS
    timeoutInMinutes: 10
    steps:
    - checkout: ${{ parameters.repositoryAlias }}
      path: s/android
      persistCredentials: false

    - task: UseDotNet@2
      displayName: Install .NET SDK
      inputs:
        useGlobalJson: true
        workingDirectory: ${{ parameters.xaSourcePath }}

    - script: >-
        dotnet test
        ${{ parameters.xaSourcePath }}/tests/Microsoft.Android.Sdk.TrimmableTypeMap.Tests/Microsoft.Android.Sdk.TrimmableTypeMap.Tests.csproj
        --logger "trx;LogFileName=TestResults.trx"
      displayName: Run TrimmableTypeMap Scanner Tests

    - task: PublishTestResults@2
      displayName: Publish Test Results
      condition: always()
      inputs:
        testResultsFormat: VSTest
        testResultsFiles: '**/TestResults.trx'
        testRunTitle: TrimmableTypeMap Scanner Tests - macOS

  - job: unit_tests_win
    displayName: Windows > Unit Tests
    pool:
      name: Azure Pipelines
      vmImage: windows-latest
      os: windows
    timeoutInMinutes: 10
    steps:
    - checkout: ${{ parameters.repositoryAlias }}
      path: s/android
      persistCredentials: false

    - task: UseDotNet@2
      displayName: Install .NET SDK
      inputs:
        useGlobalJson: true
        workingDirectory: ${{ parameters.xaSourcePath }}

    - script: >-
        dotnet test
        ${{ parameters.xaSourcePath }}/tests/Microsoft.Android.Sdk.TrimmableTypeMap.Tests/Microsoft.Android.Sdk.TrimmableTypeMap.Tests.csproj
        --logger "trx;LogFileName=TestResults.trx"
      displayName: Run TrimmableTypeMap Scanner Tests

    - task: PublishTestResults@2
      displayName: Publish Test Results
      condition: always()
      inputs:
        testResultsFormat: VSTest
        testResultsFiles: '**/TestResults.trx'
        testRunTitle: TrimmableTypeMap Scanner Tests - Windows

  - job: integration_tests_mac
    displayName: macOS > Integration Tests
    pool:
      name: Azure Pipelines
      vmImage: macOS-14
      os: macOS
    timeoutInMinutes: 10
    steps:
    - checkout: ${{ parameters.repositoryAlias }}
      path: s/android
      persistCredentials: false

    - task: UseDotNet@2
      displayName: Install .NET SDK
      inputs:
        useGlobalJson: true
        workingDirectory: ${{ parameters.xaSourcePath }}

    - task: DownloadPipelineArtifact@2
      inputs:
        artifactName: $(TestAssembliesArtifactName)
        downloadPath: ${{ parameters.xaSourcePath }}/bin/Test$(XA.Build.Configuration)

    - script: >-
        dotnet test
        ${{ parameters.xaSourcePath }}/bin/Test$(XA.Build.Configuration)/$(DotNetTargetFramework)/Microsoft.Android.Sdk.TrimmableTypeMap.IntegrationTests.dll
        --logger "trx;LogFileName=TestResults.trx"
      displayName: Run TrimmableTypeMap Integration Tests

    - task: PublishTestResults@2
      displayName: Publish Test Results
      condition: always()
      inputs:
        testResultsFormat: VSTest
        testResultsFiles: '**/TestResults.trx'
        testRunTitle: TrimmableTypeMap Integration Tests - macOS

  - job: integration_tests_win
    displayName: Windows > Integration Tests
    pool:
      name: Azure Pipelines
      vmImage: windows-latest
      os: windows
    timeoutInMinutes: 10
    steps:
    - checkout: ${{ parameters.repositoryAlias }}
      path: s/android
      persistCredentials: false

    - task: UseDotNet@2
      displayName: Install .NET SDK
      inputs:
        useGlobalJson: true
        workingDirectory: ${{ parameters.xaSourcePath }}

    - task: DownloadPipelineArtifact@2
      inputs:
        artifactName: $(TestAssembliesArtifactName)
        downloadPath: ${{ parameters.xaSourcePath }}/bin/Test$(XA.Build.Configuration)

    - script: >-
        dotnet test
        ${{ parameters.xaSourcePath }}/bin/Test$(XA.Build.Configuration)/$(DotNetTargetFramework)/Microsoft.Android.Sdk.TrimmableTypeMap.IntegrationTests.dll
        --logger "trx;LogFileName=TestResults.trx"
      displayName: Run TrimmableTypeMap Integration Tests

    - task: PublishTestResults@2
      displayName: Publish Test Results
      condition: always()
      inputs:
        testResultsFormat: VSTest
        testResultsFiles: '**/TestResults.trx'
        testRunTitle: TrimmableTypeMap Integration Tests - Windows
