# Runs MSBuild tests that do not require devices on Mac/Windows

parameters:
  stageName: msbuild_dotnet
  stageCondition: succeeded()
  dependsOn: mac_build
  stagePrefix: ''
  xaSourcePath: $(System.DefaultWorkingDirectory)
  repositoryAlias: 'self'
  commit: ''
  shouldFailOnIssue: true

stages:
- stage: ${{ parameters.stageName }}
  displayName: ${{ parameters.stagePrefix }}MSBuild Tests
  dependsOn: ${{ parameters.dependsOn }}
  condition: ${{ parameters.stageCondition }}
  jobs:
  - template: run-msbuild-tests.yaml@self
    parameters:
      testOS: macOS
      jobName: mac_msbuild_tests
      jobDisplayName: macOS > Tests > MSBuild
      agentCount: 8
      xaSourcePath: ${{ parameters.xaSourcePath }}
      repositoryAlias: ${{ parameters.repositoryAlias }}
      commit: ${{ parameters.commit }}
      shouldFailOnIssue: ${{ parameters.shouldFailOnIssue }}

  - template: run-msbuild-tests.yaml@self
    parameters:
      testOS: Windows
      jobName: win_msbuild_tests
      jobDisplayName: Windows > Tests > MSBuild
      agentCount: 6
      xaSourcePath: ${{ parameters.xaSourcePath }}
      repositoryAlias: ${{ parameters.repositoryAlias }}
      commit: ${{ parameters.commit }}
      shouldFailOnIssue: ${{ parameters.shouldFailOnIssue }}
