# Runs MSBuild tests that do not require devices on Mac/Windows

parameters:
  stageName: msbuild_dotnet
  stageCondition: succeeded()
  dependsOn: mac_build
  stagePrefix: ''
  xaSourcePath: $(System.DefaultWorkingDirectory)
  repositoryAlias: 'self'
  commit: ''

stages:
- stage: ${{ parameters.stageName }}
  displayName: ${{ parameters.stagePrefix }}MSBuild Tests
  dependsOn: ${{ parameters.dependsOn }}
  condition: ${{ parameters.stageCondition }}
  jobs:
  - template: run-msbuild-tests.yaml
    parameters:
      testOS: macOS
      jobName: mac_msbuild_tests
      jobDisplayName: macOS > Tests > MSBuild
      agentCount: 10
      testFilter: cat != Dummy  # This is because $(ExcludedNUnitCategories) gets appended which starts with '&'
      xaSourcePath: ${{ parameters.xaSourcePath }}
      repositoryAlias: ${{ parameters.repositoryAlias }}
      commit: ${{ parameters.commit }}

  - template: run-msbuild-tests.yaml
    parameters:
      testOS: Windows
      jobName: win_msbuild_tests
      jobDisplayName: Windows > Tests > MSBuild
      agentCount: 6
      testFilter: cat != Dummy  # This is because $(ExcludedNUnitCategories) gets appended which starts with '&'
      xaSourcePath: ${{ parameters.xaSourcePath }}
      repositoryAlias: ${{ parameters.repositoryAlias }}
      commit: ${{ parameters.commit }}
