//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xamarin.Android.Build.Debugging.Tasks.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xamarin.Android.Build.Debugging.Tasks.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Starting Debugger on {0}:{1}
        ///Start sdb then run the following command
        ///  connect {0} {1}
        ///    .
        /// </summary>
        internal static string StartDebugger_ipAddress_port {
            get {
                return ResourceManager.GetString("StartDebugger_ipAddress_port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adb is not running. {0}.
        /// </summary>
        internal static string XA0010_Adb {
            get {
                return ResourceManager.GetString("XA0010_Adb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid adb target name &apos;{0}&apos;. Target names must start with `-d`, `-e`, or `-s`..
        /// </summary>
        internal static string XA0010_AdbTarget {
            get {
                return ResourceManager.GetString("XA0010_AdbTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve the Android ABI for the attached device or emulator. Please reconnect the device or restart the emulator, and try again..
        /// </summary>
        internal static string XA0010_NoAbi {
            get {
                return ResourceManager.GetString("XA0010_NoAbi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No available device..
        /// </summary>
        internal static string XA0010_NoDevice {
            get {
                return ResourceManager.GetString("XA0010_NoDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected device is not running..
        /// </summary>
        internal static string XA0010_Selected {
            get {
                return ResourceManager.GetString("XA0010_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to copy Fast Deployment tools to &apos;{0}/{1}&apos; on the target device.
        ///This device might not be compatible with Fast Deployment.
        ///Please set the &apos;EmbedAssembliesIntoApk&apos; MSBuild property to &apos;true&apos; to disable Fast Deployment in the Visual Studio project property pages, or edit the project file in a text editor..
        /// </summary>
        internal static string XA0126_UnableToCopyFastDevTools {
            get {
                return ResourceManager.GetString("XA0126_UnableToCopyFastDevTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deploying &apos;{0}&apos; using &apos;{1}: {2}&apos;.
        ///Please set the &apos;EmbedAssembliesIntoApk&apos; MSBuild property to &apos;true&apos; to disable Fast Deployment in the Visual Studio project property pages, or edit the project file in a text editor..
        /// </summary>
        internal static string XA0127_ErrorDeployingFile {
            get {
                return ResourceManager.GetString("XA0127_ErrorDeployingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;log.redirect-stdio&apos; Android system property is set to &apos;true&apos; on the target device or emulator.
        ///To enable compatibility with Fast Deployment, set the property to &apos;false&apos; or reboot the device or emulator to clear the value..
        /// </summary>
        internal static string XA0128_RedirectStdioIsEnabled {
            get {
                return ResourceManager.GetString("XA0128_RedirectStdioIsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deploying &apos;{0}&apos;.
        ///Please set the &apos;EmbedAssembliesIntoApk&apos; MSBuild property to &apos;true&apos; to disable Fast Deployment in the Visual Studio project property pages, or edit the project file in a text editor..
        /// </summary>
        internal static string XA0129_ErrorDeployingFile {
            get {
                return ResourceManager.GetString("XA0129_ErrorDeployingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry. Fast Deployment is only supported on devices running Android 5.0 (API level 21) or higher.
        ///Please set the &apos;EmbedAssembliesIntoApk&apos; MSBuild property to &apos;true&apos; to disable Fast Deployment in the Visual Studio project property pages, or edit the project file in a text editor..
        /// </summary>
        internal static string XA0130_FastDevNotSupported {
            get {
                return ResourceManager.GetString("XA0130_FastDevNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;run-as&apos; tool has been disabled on this device. Either enable it by activating the developer options on the device or by setting `ro.boot.disable_runas` to `false`..
        /// </summary>
        internal static string XA0131_DeveloperModeNotEnabled {
            get {
                return ResourceManager.GetString("XA0131_DeveloperModeNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The package was not installed. Please check you do not have it installed under any other user.
        ///If the package does show up on the device, try manually uninstalling it then try again.
        ///You should be able to uninstall the app via the Settings app on the device..
        /// </summary>
        internal static string XA0132_PackageNotInstalled {
            get {
                return ResourceManager.GetString("XA0132_PackageNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;run-as&apos; tool required by the Fast Deployment system has been disabled on this device by the manufacturer.
        ///Please disable Fast Deployment in the Visual Studio project property pages or edit the project file in a text editor and set the &apos;EmbedAssembliesIntoApk&apos; MSBuild property to &apos;true&apos;..
        /// </summary>
        internal static string XA0133_RunAsPermissionDenied {
            get {
                return ResourceManager.GetString("XA0133_RunAsPermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application does not have the &apos;android:debuggable&apos; attribute set in the AndroidManifest.xml.
        ///This is required in order for Fast Deployment to work. This is normally enabled by default by 
        ///the Xamarin.Android build system for Debug builds. Please check that you to not have this attribute
        ///set on the &apos;application&apos; element in your &apos;AndroidManifest.xml&apos;.
        ///If you have a class that derives from &apos;Android.App.Application&apos; and are using the &apos;[Application]&apos; make sure the 
        ///&apos;Debuggable&apos; property is not set at all as  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XA0134_RunAsPackageNotDebuggable {
            get {
                return ResourceManager.GetString("XA0134_RunAsPackageNotDebuggable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The package is a &apos;system&apos; application. These are applications which install under
        /// the &apos;system&apos; user on a device. These types of applications cannot use &apos;run-as&apos;.
        /// The Fast Deployment system should have handled this particular error automatically
        /// and used a backup installation path. However if you are seeing this error please file
        /// an issue with the exact error message using the &apos;Help-&gt;Send Feedback-&gt;Report a Problem&apos; menu item in Visual Studio
        /// or &apos;Help-&gt;Report a Problem&apos; in Visual Studio for Mac. If poss [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XA0135_RunAsPackageNotAndApplication {
            get {
                return ResourceManager.GetString("XA0135_RunAsPackageNotAndApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;run-as&apos; command failed with &apos;{0}&apos;.
        ///The currently installation of the package in corrupt. Please manually uninstall the 
        ///package from all the users on device and try again. If that does not work you can disable Fast Deployment.
        ///Fast Deployment can be disabled in the Visual Studio project property pages or edit the project file in a text editor and set the &apos;EmbedAssembliesIntoApk&apos; MSBuild property to &apos;true&apos;.
        ///.
        /// </summary>
        internal static string XA0136_RunAsCorruptInstallation {
            get {
                return ResourceManager.GetString("XA0136_RunAsCorruptInstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;run-as&apos; command failed with &apos;{0}&apos;.
        ///Fast Deployment is not currently supported on this device.
        ///Please file an issue with the exact error message using the &apos;Help-&gt;Send Feedback-&gt;Report a Problem&apos; menu item in Visual Studio
        ///or &apos;Help-&gt;Report a Problem&apos; in Visual Studio for Mac.
        ///Please set the &apos;EmbedAssembliesIntoApk&apos; MSBuild property to &apos;true&apos; to disable Fast Deployment in the Visual Studio project property pages, or edit the project file in a text editor..
        /// </summary>
        internal static string XA0137_RunAsOSCorrupt {
            get {
                return ResourceManager.GetString("XA0137_RunAsOSCorrupt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to
        ///Error deploying &apos;{0}&apos; using &apos;{1}: {2}&apos;.
        ///This is usually due to an error in `adb` when the file data is sent over to the device. 
        ///Normal cause for this is a loose or low quality USB cable. Please try a different cable.
        ///Alternatively try using Wifi Debugging, this can be more reliable than USB debugging for certain devices. 
        ///Please set the &apos;EmbedAssembliesIntoApk&apos; MSBuild property to &apos;true&apos; to disable Fast Deployment in the Visual Studio project property pages, or edit the project file in a text editor..
        /// </summary>
        internal static string XA0138_ErrorReadingStdin {
            get {
                return ResourceManager.GetString("XA0138_ErrorReadingStdin", resourceCulture);
            }
        }
    }
}
