# https://docs.github.com/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/
version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
