# https://docs.github.com/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/
version: 2
updates:
  - package-ecosystem: "gradle"
    directories:
      - "/src/r8"
      - "/src/manifestmerger"
      - "/src/proguard-android"
      - "/tests/CodeGen-Binding/Xamarin.Android.LibraryProjectZip-LibBinding/java/JavaLib"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "external/constexpr-xxh3"
      - dependency-name: "external/lz4"
      - dependency-name: "external/robin-map"
      - dependency-name: "external/xxHash"
