#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using Java.Interop.Tools.JavaCallableWrappers;
using Microsoft.Android.Build.Tasks;
using Microsoft.Build.Utilities;
using Mono.Cecil;
using Mono.Linker;
using Mono.Linker.Steps;
using Xamarin.Android.Tasks;
using Xamarin.Android.Tools;

namespace MonoDroid.Tuner;

/// <summary>
/// Scans an assembly for JLOs that need JCWs generated and writes them to an XML file.
/// </summary>
public class RewriteMarshalMethodsStep : BaseStep, IAssemblyModifierPipelineStep
{
	public TaskLoggingHelper Log { get; set; }

	bool? brokenExceptionTransitionsEnabled;

	public RewriteMarshalMethodsStep (TaskLoggingHelper log)
	{
		Log = log;
	}

	public bool ProcessAssembly (AssemblyDefinition assembly, StepContext context)
	{
		if (!context.IsAndroidAssembly)
			return false;

		var action = Annotations.HasAction (assembly) ? Annotations.GetAction (assembly) : AssemblyAction.Skip;

		if (action == AssemblyAction.Delete)
			return false;

		// We need to parse the environment files supplied by the user to see if they want to use broken exception transitions. This information is needed
		// in order to properly generate wrapper methods in the marshal methods assembly rewriter.
		// We don't care about those generated by us, since they won't contain the `XA_BROKEN_EXCEPTION_TRANSITIONS` variable we look for.
		if (!brokenExceptionTransitionsEnabled.HasValue) {
			var environmentParser = new EnvironmentFilesParser ();
			brokenExceptionTransitionsEnabled = environmentParser.AreBrokenExceptionTransitionsEnabled (context.Environments);
		}

		var allJavaTypes = ScanForJavaTypes (assembly, context.Architecture);
		var javaTypesForJCW = allJavaTypes.Where (t => !JavaTypeScanner.ShouldSkipJavaCallableWrapperGeneration (t, Context)).ToList ();

		var jcwContext = new JCWGeneratorContext (context.Architecture, Context.Resolver, context.ResolvedAssemblies, javaTypesForJCW, Context, true);
		var jcwGenerator = new JCWGenerator (Log, jcwContext) {
			CodeGenerationTarget = context.CodeGenerationTarget,
		};

		jcwGenerator.Classify (context.AndroidSdkPlatform);

		var state = new NativeCodeGenState (context.Architecture, Context, Context.Resolver, allJavaTypes, javaTypesForJCW, jcwGenerator.Classifier);
		Run (state, context);

		// TODO: Only return true if we actually modified the assembly
		return true;
	}

	List<TypeDefinition> ScanForJavaTypes (AssemblyDefinition assembly, AndroidTargetArch arch)
	{
		var types = new List<TypeDefinition> ();

		var scanner = new XAJavaTypeScanner (arch, Log, Context);

		foreach (ModuleDefinition md in assembly.Modules) {
			foreach (TypeDefinition td in md.Types) {
				scanner.AddJavaType (td, types);
			}
		}

		return types;
	}

	void Run (NativeCodeGenState state, StepContext context)
	{
		if (state.Classifier is null) {
			Log.LogError ("state.Classifier cannot be null if marshal methods are enabled");
			return;
		}

		if (!context.EnableManagedMarshalMethodsLookup) {
			RewriteMethods (state, brokenExceptionTransitionsEnabled.GetValueOrDefault ());
			state.Classifier.AddSpecialCaseMethods ();
		} else {
			// We need to run `AddSpecialCaseMethods` before `RewriteMarshalMethods` so that we can see the special case
			// methods (such as TypeManager.n_Activate_mm) when generating the managed lookup tables.
			state.Classifier.AddSpecialCaseMethods ();
			state.ManagedMarshalMethodsLookupInfo = new ManagedMarshalMethodsLookupInfo (Log);
			RewriteMethods (state, brokenExceptionTransitionsEnabled.GetValueOrDefault ());
		}

		Log.LogDebugMessage ($"[{state.TargetArch}] Number of generated marshal methods: {state.Classifier.MarshalMethods.Count}");
		if (state.Classifier.RejectedMethodCount > 0) {
			Log.LogWarning ($"[{state.TargetArch}] Number of methods in the project that will be registered dynamically: {state.Classifier.RejectedMethodCount}");
		}

		if (state.Classifier.WrappedMethodCount > 0) {
			// TODO: change to LogWarning once the generator can output code which requires no non-blittable wrappers
			Log.LogDebugMessage ($"[{state.TargetArch}] Number of methods in the project that need marshal method wrappers: {state.Classifier.WrappedMethodCount}");
		}
	}

	void RewriteMethods (NativeCodeGenState state, bool brokenExceptionTransitionsEnabled)
	{
		if (state.Classifier == null) {
			return;
		}

		var rewriter = new MarshalMethodsAssemblyRewriter (Log, state.TargetArch, state.Classifier, state.Resolver, state.ManagedMarshalMethodsLookupInfo);
		rewriter.Rewrite (brokenExceptionTransitionsEnabled);
	}
}
