<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\Configuration.props" />

  <PropertyGroup>
    <TargetFramework>$(DotNetStableTargetFramework)</TargetFramework>
    <RootNamespace>Microsoft.Android.Run.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>..\..\product.snk</AssemblyOriginatorKeyFile>
    <OutputPath>$(TestOutputDirectory)Microsoft.Android.Run-Tests\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <Nullable>enable</Nullable>
    <RollForward>Major</RollForward>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NUnit" Version="$(NUnitVersion)" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.2.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.7.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="ManagedLaunchTestAdbProxy\**" />
    <EmbeddedResource Remove="ManagedLaunchTestAdbProxy\**" />
    <None Remove="ManagedLaunchTestAdbProxy\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Microsoft.Android.Run\Microsoft.Android.Run.csproj" />
    <ProjectReference Include="ManagedLaunchTestAdbProxy\ManagedLaunchTestAdbProxy.csproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
    </ProjectReference>
  </ItemGroup>

</Project>
