<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\Configuration.props" />
  <PropertyGroup>
    <Company>Microsoft Corporation</Company>
    <Copyright>2020 Microsoft Corporation</Copyright>
    <Version>0.0.1</Version>
    <TargetFrameworks>$(DotNetTargetFramework)</TargetFrameworks>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>../../bin/$(Configuration)/bin/typemap-tool</OutputPath>
    <OutputType>Exe</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>enable</Nullable>
    <RollForward>Major</RollForward>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="../../src/Xamarin.Android.Build.Tasks/Utilities/TypeMapHelper.cs" />
    <Compile Include="..\..\.github\skills\read-assembly-store\src\AssemblyStore\AssemblyCompression.cs" />
    <Compile Include="..\..\.github\skills\read-assembly-store\src\AssemblyStore\ELFPayloadError.cs" />
    <Compile Include="..\..\.github\skills\read-assembly-store\src\AssemblyStore\FileFormat.cs" />
    <Compile Include="..\..\.github\skills\read-assembly-store\src\AssemblyStore\Log.cs" />
    <Compile Include="..\..\.github\skills\read-assembly-store\src\AssemblyStore\Utils.cs" />
    <Compile Include="..\..\.github\skills\read-assembly-store\src\AssemblyStore\V1\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Mono.Options" Version="$(MonoOptionsVersion)" />
    <PackageReference Include="Mono.Cecil" Version="$(MonoCecilVersion)" />
    <PackageReference Include="System.IO.Hashing" Version="$(SystemIOHashingPackageVersion)" />
    <PackageReference Include="ELFSharp" Version="$(ELFSharpVersion)" />
    <PackageReference Include="K4os.Compression.LZ4" Version="$(LZ4PackageVersion)" />
  </ItemGroup>
</Project>
