using Android.Runtime;

namespace Microsoft.Android.Runtime;

internal static class TypeMap
{
	// Initialization generated by src/Microsoft.Android.Sdk.ILLink/TypeMappingStep.cs
	private static readonly ulong[] s_hashes;

	internal static int Count => s_hashes.Length;

	internal static Type? GetType (string javaClassName)
	{
		// // TODO in this case it would be faster to calculate the hash without the JNI call
		// IntPtr javaClass = JNIEnv.FindClass (javaClassName);
		// if (javaClass == IntPtr.Zero) {
		// 	return null;
		// }

		// return GetType (javaClass);
		throw new NotImplementedException ();
	}

	internal static Type? GetType (IntPtr javaClass)
	{
		// TODO use the xxhash64 once I figure out the damned
		// ulong hash = AndroidRuntimeInternal.GetJavaClassNameHash (javaClass);
		// if (hash == 0) {
		// 	return null;
		// }
		string name = Java.Interop.TypeManager.GetClassName (javaClass);
		ulong hash = (ulong)name.GetHashCode ();

		int index = MemoryExtensions.BinarySearch (s_hashes, hash);
		if (index < 0) {
			return null;
		}

		return GetTypeByIndex (index);
	}

	internal static Type? GetTypeByIndex (int index)
	{
		// Replaced by src/Microsoft.Android.Sdk.ILLink/TypeMappingStep.cs
		throw new NotImplementedException ();
	}
}
