<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(DotNetStableTargetFramework)</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AssemblyName>Mono.Android</AssemblyName>
    <RootNamespace>Mono.Android</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

</Project>
