using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Reflection.Metadata;
using System.Reflection.Metadata.Ecma335;
using System.Reflection.PortableExecutable;
using System.Xml.Linq;
using Xunit;

namespace Microsoft.Android.Sdk.TrimmableTypeMap.Tests;

public class TrimmableTypeMapGeneratorTests : FixtureTestBase
{
	readonly List<string> logMessages = new ();

	sealed class TestTrimmableTypeMapLogger (List<string> logMessages, List<string>? warnings = null) : ITrimmableTypeMapLogger
	{
		public void LogNoJavaPeerTypesFound () =>
			logMessages.Add ("No Java peer types found, skipping typemap generation.");
		public void LogJavaPeerScanInfo (int assemblyCount, int peerCount) =>
			logMessages.Add ($"Scanned {assemblyCount} assemblies, found {peerCount} Java peer types.");
		public void LogGeneratingJcwFilesInfo (int jcwPeerCount, int totalPeerCount) =>
			logMessages.Add ($"Generating JCW files for {jcwPeerCount} types (filtered from {totalPeerCount} total).");
		public void LogDeferredRegistrationTypesInfo (int typeCount) =>
			logMessages.Add ($"Found {typeCount} Application/Instrumentation types for deferred registration.");
		public void LogGeneratedTypeMapAssemblyInfo (string assemblyName, int typeCount) =>
			logMessages.Add ($"  {assemblyName}: {typeCount} types");
		public void LogGeneratedRootTypeMapInfo (int assemblyReferenceCount) =>
			logMessages.Add ($"  Root: {assemblyReferenceCount} per-assembly refs");
		public void LogGeneratedTypeMapAssembliesInfo (int assemblyCount) =>
			logMessages.Add ($"Generated {assemblyCount} typemap assemblies.");
		public void LogGeneratedJcwFilesInfo (int sourceCount) =>
			logMessages.Add ($"Generated {sourceCount} JCW Java source files.");
		public void LogRootingManifestReferencedTypeInfo (string javaTypeName, string managedTypeName) =>
			logMessages.Add ($"Rooting manifest-referenced type '{javaTypeName}' ({managedTypeName}) as unconditional.");
		public void LogManifestReferencedTypeNotFoundWarning (string javaTypeName) =>
			warnings?.Add ($"Manifest-referenced type '{javaTypeName}' was not found in any scanned assembly. It may be a framework type.");
		public void LogLibraryManifestMergeWarning (string message) =>
			warnings?.Add (message);
		public void LogInvalidManifestPlaceholderWarning (string placeholders) =>
			warnings?.Add ($"Invalid $(AndroidManifestPlaceholders) '{placeholders}'.");
		public void LogUnresolvableJavaPeerSkippedWarning (
			string managedTypeName,
			string assemblyName,
			string unresolvedTypeName,
			string unresolvedAssemblyName,
			string unresolvedAssemblyPath) =>
			warnings?.Add (
				$"Skipping Java peer '{managedTypeName}' from '{assemblyName}' because referenced type " +
				$"'{unresolvedTypeName}' from '{unresolvedAssemblyName}' at '{unresolvedAssemblyPath}' could not be resolved.");
		public void LogJniAddNativeMethodRegistrationAttributeError (string managedTypeName) =>
			logMessages.Add ($"XA4251: Type '{managedTypeName}' uses [JniAddNativeMethodRegistrationAttribute], which is not supported by the trimmable type map.");
		public void LogInvalidJavaNameError (string javaName, string invalidIdentifier) =>
			logMessages.Add ($"XA4258: Java name '{javaName}' contains invalid or unsupported Java identifier '{invalidIdentifier}'.");
		public void LogDuplicateJavaTypeError (string javaName) =>
			logMessages.Add ($"XA4215: The Java type `{javaName}` is generated by more than one managed type.");
		public void LogDuplicateJavaTypeDetailsError (string javaName, string managedTypeName) =>
			logMessages.Add ($"XA4215:   `{javaName}` generated by: {managedTypeName}");
		public void LogExportFieldWithParametersError () =>
			logMessages.Add ("XA4205: [ExportField] can only be used on methods with 0 parameters.");
		public void LogExportOnGenericTypeError () =>
			logMessages.Add ("XA4206: [Export] cannot be used on a generic type.");
		public void LogExportFieldReturnsVoidError () =>
			logMessages.Add ("XA4208: [ExportField] cannot be used on a method returning 'void'.");
		public void LogExportFieldOnGenericTypeError () =>
			logMessages.Add ("XA4207: [ExportField] cannot be used on a generic type.");
		public void LogUnsupportedExportSignatureError (string memberName, string managedTypeName) =>
			logMessages.Add ($"XA4263: The exported member '{memberName}' has unsupported signature type '{managedTypeName}'.");
		public void LogCustomJavaObjectError (string managedTypeName) =>
			logMessages.Add ($"XA4212: Type `{managedTypeName}` implements `Android.Runtime.IJavaObject` but does not inherit `Java.Lang.Object` or `Java.Lang.Throwable`. This is not supported.");
		public void LogCustomJavaObjectWarning (string managedTypeName) =>
			warnings?.Add ($"XA4212: Type `{managedTypeName}` implements `Android.Runtime.IJavaObject` but does not inherit `Java.Lang.Object` or `Java.Lang.Throwable`. This is not supported.");
	}

	[Theory]
	[InlineData ("com/for/Example", "for")]
	[InlineData ("com/example/for", "for")]
	[InlineData ("com/example/record", "record")]
	[InlineData ("com/1example/Peer", "1example")]
	[InlineData ("com/e\u0301xample/Peer", "e\u0301xample")]
	[InlineData ("com/\U00010428xample/Peer", "\U00010428xample")]
	public void ValidateJavaNames_InvalidOrUnsupportedIdentifier_LogsError (string javaName, string invalidIdentifier)
	{
		var peers = new List<JavaPeerInfo> {
			new JavaPeerInfo {
				JavaName = javaName,
				CompatJniName = javaName,
				ManagedTypeName = "Example.Type",
				ManagedTypeNamespace = "Example",
				ManagedTypeShortName = "Type",
				AssemblyName = "Example",
			},
		};

		Assert.False (CreateGenerator ().ValidateJavaNames (peers));
		Assert.Contains (
			logMessages,
			message => message.Contains (
				$"XA4258: Java name '{javaName}' contains invalid or unsupported Java identifier '{invalidIdentifier}'.",
				StringComparison.Ordinal
			)
		);
	}

	[Fact]
	public void ValidateJavaNames_ContextualKeywordInPackage_IsValid ()
	{
		var peers = new List<JavaPeerInfo> {
			new JavaPeerInfo {
				JavaName = "com/record/Example",
				CompatJniName = "com/record/Example",
				ManagedTypeName = "Example.Type",
				ManagedTypeNamespace = "Example",
				ManagedTypeShortName = "Type",
				AssemblyName = "Example",
			},
		};

		Assert.True (CreateGenerator ().ValidateJavaNames (peers));
		Assert.DoesNotContain (logMessages, message => message.Contains ("XA4258"));
	}

	[Fact]
	public void ValidateJavaNames_DuplicateGeneratedJcw_LogsXA4215 ()
	{
		var peers = new List<JavaPeerInfo> {
			new JavaPeerInfo {
				JavaName = "examplelib/DuplicatePeer",
				CompatJniName = "examplelib/DuplicatePeer",
				ManagedTypeName = "Library1.FirstPeer",
				ManagedTypeNamespace = "Library1",
				ManagedTypeShortName = "FirstPeer",
				AssemblyName = "Library1",
			},
			new JavaPeerInfo {
				JavaName = "examplelib/DuplicatePeer",
				CompatJniName = "examplelib/DuplicatePeer",
				ManagedTypeName = "Library2.SecondPeer",
				ManagedTypeNamespace = "Library2",
				ManagedTypeShortName = "SecondPeer",
				AssemblyName = "Library2",
			},
		};

		Assert.False (CreateGenerator ().ValidateJavaNames (peers));
		Assert.Contains (logMessages, message => message == "XA4215: The Java type `examplelib.DuplicatePeer` is generated by more than one managed type.");
		Assert.Contains (logMessages, message => message == "XA4215:   `examplelib.DuplicatePeer` generated by: Library1.FirstPeer, Library1");
		Assert.Contains (logMessages, message => message == "XA4215:   `examplelib.DuplicatePeer` generated by: Library2.SecondPeer, Library2");
	}

	[Theory]
	[InlineData ("com/example/\u00a2Peer")]
	[InlineData ("com/example/\u203fPeer")]
	public void ValidateJavaNames_JavaTypeOnlyStartWithoutComponent_IsValid (string javaName)
	{
		var peer = new JavaPeerInfo {
			JavaName = javaName,
			CompatJniName = javaName,
			ManagedTypeName = "Example.Type",
			ManagedTypeNamespace = "Example",
			ManagedTypeShortName = "Type",
			AssemblyName = "Example",
		};

		Assert.True (CreateGenerator ().ValidateJavaNames ([peer]));
		Assert.DoesNotContain (logMessages, message => message.Contains ("XA4258"));
	}

	[Fact]
	public void ValidateJavaNames_JavaTypeOnlyNestedReferences_AreValid ()
	{
		const string nestedName = "com/example/\u00a2Outer$Inner";
		var peer = new JavaPeerInfo {
			JavaName = "com/example/Peer",
			CompatJniName = "com/example/Peer",
			ManagedTypeName = "Example.Type",
			ManagedTypeNamespace = "Example",
			ManagedTypeShortName = "Type",
			AssemblyName = "Example",
			JavaConstructors = [
				new JavaConstructorInfo {
					JniSignature = "()V",
					ConstructorIndex = 0,
					ThrownNames = [nestedName],
				},
			],
			JavaFields = [
				new JavaFieldInfo {
					FieldName = "VALUE",
					JavaTypeName = "com.example.\u00a2Outer.Inner",
					JniTypeName = $"L{nestedName};",
					InitializerMethodName = "GetValue",
					Visibility = "public",
				},
			],
		};

		Assert.True (CreateGenerator ().ValidateJavaNames ([peer]));
		Assert.DoesNotContain (logMessages, message => message.Contains ("XA4258"));
	}

	[Theory]
	[InlineData ("com/example/\u00a2Peer", "\u00a2Peer")]
	[InlineData ("com/example/\u203fPeer", "\u203fPeer")]
	public void ValidateJavaNames_JavaTypeOnlyStartOnComponent_LogsError (string javaName, string invalidIdentifier)
	{
		var peer = new JavaPeerInfo {
			JavaName = javaName,
			CompatJniName = javaName,
			ManagedTypeName = "Example.Type",
			ManagedTypeNamespace = "Example",
			ManagedTypeShortName = "Type",
			AssemblyName = "Example",
			ComponentAttribute = new ComponentInfo { Kind = ComponentKind.Activity },
		};

		Assert.False (CreateGenerator ().ValidateJavaNames ([peer]));
		Assert.Contains (logMessages, message =>
			message.Contains ($"Java name '{javaName}' contains invalid or unsupported Java identifier '{invalidIdentifier}'."));
	}

	[Fact]
	public void ValidateJavaNames_JavaTypeOnlyStartOnAbstractComponent_IsValid ()
	{
		var peer = new JavaPeerInfo {
			JavaName = "com/example/\u00a2Peer",
			CompatJniName = "com/example/\u00a2Peer",
			ManagedTypeName = "Example.Type",
			ManagedTypeNamespace = "Example",
			ManagedTypeShortName = "Type",
			AssemblyName = "Example",
			IsAbstract = true,
			ComponentAttribute = new ComponentInfo { Kind = ComponentKind.Activity },
		};

		Assert.True (CreateGenerator ().ValidateJavaNames ([peer]));
		Assert.DoesNotContain (logMessages, message => message.Contains ("XA4258"));
	}

	[Fact]
	public void ValidateJavaNames_JavaTypeOnlyStartInManifestTemplate_LogsError ()
	{
		var manifest = XDocument.Parse ("""
			<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.example">
			  <application>
			    <activity android:name=".¢Peer" />
			  </application>
			</manifest>
			""");

		Assert.False (CreateGenerator ().ValidateJavaNames ([], manifest: manifest));
		Assert.Contains (logMessages, message =>
			message.Contains ("Java name 'com.example.¢Peer' contains invalid or unsupported Java identifier '¢Peer'."));
	}

	[Fact]
	public void ValidateJavaNames_DefaultPackageNestedThrownKeyword_LogsError ()
	{
		var peer = new JavaPeerInfo {
			JavaName = "com/example/Peer",
			CompatJniName = "com/example/Peer",
			ManagedTypeName = "Example.Type",
			ManagedTypeNamespace = "Example",
			ManagedTypeShortName = "Type",
			AssemblyName = "Example",
			JavaConstructors = [
				new JavaConstructorInfo {
					JniSignature = "()V",
					ConstructorIndex = 0,
					ThrownNames = ["Outer$record"],
				},
			],
		};

		Assert.False (CreateGenerator ().ValidateJavaNames ([peer]));
		Assert.Contains (logMessages, message =>
			message.Contains ("Java name 'Outer$record' contains invalid or unsupported Java identifier 'record'."));
	}

	[Theory]
	[InlineData ("com/example/Outer$for", null, "for")]
	[InlineData ("com/example/Outer$record", null, "record")]
	[InlineData (null, "com/example/Outer$for", "for")]
	[InlineData (null, "com/example/Outer$record", "record")]
	public void ValidateJavaNames_ReservedReferencedTypeIdentifier_LogsError (string? baseJavaName, string? interfaceName, string invalidIdentifier)
	{
		var interfaces = interfaceName is null ? [] : new [] { interfaceName };
		var referencedName = baseJavaName ?? interfaceName;
		var peers = new List<JavaPeerInfo> {
			new JavaPeerInfo {
				JavaName = "com/example/Derived",
				CompatJniName = "com/example/Derived",
				ManagedTypeName = "Example.Derived",
				ManagedTypeNamespace = "Example",
				ManagedTypeShortName = "Derived",
				AssemblyName = "Example",
				BaseJavaName = baseJavaName,
				ImplementedInterfaceJavaNames = interfaces,
			},
		};

		Assert.False (CreateGenerator ().ValidateJavaNames (peers));
		Assert.Contains (logMessages, message =>
			message.Contains ($"XA4258: Java name '{referencedName}' contains invalid or unsupported Java identifier '{invalidIdentifier}'."));
	}

	[Theory]
	[InlineData ("com/example/Outer$for")]
	[InlineData ("com/example/Outer$record")]
	public void ValidateJavaNames_DollarInDeclaredTypeName_IsValid (string javaName)
	{
		var peers = new List<JavaPeerInfo> {
			new JavaPeerInfo {
				JavaName = javaName,
				CompatJniName = javaName,
				ManagedTypeName = "Example.Type",
				ManagedTypeNamespace = "Example",
				ManagedTypeShortName = "Type",
				AssemblyName = "Example",
			},
		};

		Assert.True (CreateGenerator ().ValidateJavaNames (peers));
		Assert.DoesNotContain (logMessages, message => message.Contains ("XA4258"));
	}

	[Theory]
	[InlineData ("com/example/Outer$for", "for")]
	[InlineData ("com/example/Outer$record", "record")]
	public void ValidateJavaNames_ReservedDeferredRegistrationTypeIdentifier_LogsError (string javaName, string invalidIdentifier)
	{
		var peers = new List<JavaPeerInfo> {
			new JavaPeerInfo {
				JavaName = javaName,
				CompatJniName = javaName,
				ManagedTypeName = "Example.Application",
				ManagedTypeNamespace = "Example",
				ManagedTypeShortName = "Application",
				AssemblyName = "Example",
				CannotRegisterInStaticConstructor = true,
			},
		};

		Assert.False (CreateGenerator ().ValidateJavaNames (peers));
		Assert.Contains (logMessages, message =>
			message.Contains ($"XA4258: Java name '{javaName}' contains invalid or unsupported Java identifier '{invalidIdentifier}'."));
	}

	[Fact]
	public void ValidateJavaNames_ReservedEmittedTypeReferences_LogErrors ()
	{
		var peers = new List<JavaPeerInfo> {
			new JavaPeerInfo {
				JavaName = "com/example/Derived",
				CompatJniName = "com/example/Derived",
				ManagedTypeName = "Example.Derived",
				ManagedTypeNamespace = "Example",
				ManagedTypeShortName = "Derived",
				AssemblyName = "Example",
				JavaConstructors = [
					new JavaConstructorInfo {
						JniSignature = "(Lcom/example/Outer$for;)V",
						ConstructorIndex = 0,
						ThrownNames = ["com/example/Outer$permits"],
					},
				],
				MarshalMethods = [
					new MarshalMethodInfo {
						JniName = "method",
						JniSignature = "([Lcom/example/Outer$record;)Lcom/example/Outer$yield;",
						ManagedMethodName = "Method",
						NativeCallbackName = "n_method",
						ThrownNames = ["com/example/Outer$sealed"],
					},
				],
				JavaFields = [
					new JavaFieldInfo {
						FieldName = "VALUE",
						JavaTypeName = "com.example.Outer.sealed",
						InitializerMethodName = "getValue",
						Visibility = "public",
					},
				],
			},
		};

		Assert.False (CreateGenerator ().ValidateJavaNames (peers));
		Assert.Contains (logMessages, message => message.Contains ("Java name 'com/example/Outer$for' contains invalid or unsupported Java identifier 'for'."));
		Assert.Contains (logMessages, message =>
			message.Contains ("Java name 'com/example/Outer$record' contains invalid or unsupported Java identifier 'record'."));
		Assert.Contains (logMessages, message =>
			message.Contains ("Java name 'com/example/Outer$yield' contains invalid or unsupported Java identifier 'yield'."));
		Assert.Contains (logMessages, message =>
			message.Contains ("Java name 'com/example/Outer$permits' contains invalid or unsupported Java identifier 'permits'."));
		Assert.Contains (logMessages, message =>
			message.Contains ("Java name 'com/example/Outer$sealed' contains invalid or unsupported Java identifier 'sealed'."));
		Assert.Contains (logMessages, message =>
			message.Contains ("Java name 'com.example.Outer.sealed' contains invalid or unsupported Java identifier 'sealed'."));
	}

	[Fact]
	public void ValidateJavaNames_AfterDeferredRegistrationPropagation_ValidatesRegistrationName ()
	{
		var basePeer = new JavaPeerInfo {
			JavaName = "com/example/Outer$for",
			CompatJniName = "com/example/Outer$for",
			ManagedTypeName = "Example.BaseApplication",
			ManagedTypeNamespace = "Example",
			ManagedTypeShortName = "BaseApplication",
			AssemblyName = "Example",
		};
		var applicationPeer = new JavaPeerInfo {
			JavaName = "com/example/Application",
			CompatJniName = "com/example/Application",
			ManagedTypeName = "Example.Application",
			ManagedTypeNamespace = "Example",
			ManagedTypeShortName = "Application",
			AssemblyName = "Example",
			BaseJavaName = basePeer.JavaName,
			CannotRegisterInStaticConstructor = true,
		};
		var peers = new List<JavaPeerInfo> { basePeer, applicationPeer };

		TrimmableTypeMapGenerator.PropagateDeferredRegistrationToBaseClasses (peers);

		Assert.True (basePeer.CannotRegisterInStaticConstructor);
		Assert.False (CreateGenerator ().ValidateJavaNames (peers));
		Assert.Contains (logMessages, message =>
			message.Contains ("Java name 'com/example/Outer$for' contains invalid or unsupported Java identifier 'for'."));
	}

	[Fact]
	public void ValidateJavaNames_ReservedApplicationJavaClassIdentifier_LogsError ()
	{
		Assert.False (CreateGenerator ().ValidateJavaNames ([], "com.example.Outer.for"));
		Assert.Contains (logMessages, message => message.Contains ("Java name 'com.example.Outer.for' contains invalid or unsupported Java identifier 'for'."));
	}

	[Theory]
	[InlineData (true, false, "com/for/Example")]
	[InlineData (false, true, "com/for/Example")]
	[InlineData (true, false, "com/example/Outer$record")]
	[InlineData (false, true, "com/example/Outer$record")]
	public void ValidateJavaNames_TypeWithoutJcw_IsNotValidated (bool doNotGenerateAcw, bool isInterface, string javaName)
	{
		var peers = new List<JavaPeerInfo> {
			new JavaPeerInfo {
				JavaName = javaName,
				CompatJniName = javaName,
				ManagedTypeName = "Example.Type",
				ManagedTypeNamespace = "Example",
				ManagedTypeShortName = "Type",
				AssemblyName = "Example",
				DoNotGenerateAcw = doNotGenerateAcw,
				IsInterface = isInterface,
			},
		};

		Assert.True (CreateGenerator ().ValidateJavaNames (peers));
		Assert.DoesNotContain (logMessages, message => message.Contains ("XA4258"));
	}

	[Fact]
	public void Execute_EmptyAssemblyList_ReturnsEmptyResults ()
	{
		var result = CreateGenerator ().Execute ([], new Version (11, 0), new HashSet<string> ());
		Assert.Empty (result.GeneratedAssemblies);
		Assert.Empty (result.GeneratedJavaSources);
		Assert.Empty (result.AllPeers);
		Assert.Contains (logMessages, m => m.Contains ("No Java peer types found"));
	}

	[Fact]
	public void Execute_InvalidManifestComponentWithoutPeers_ReportsError ()
	{
		var manifest = XDocument.Parse ("""
			<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.example">
			  <application>
			    <activity android:name=".¢Peer" />
			  </application>
			</manifest>
			""");

		var result = CreateGenerator ().Execute (
			[],
			new Version (11, 0),
			new HashSet<string> (),
			manifestTemplate: manifest);

		Assert.Empty (result.GeneratedAssemblies);
		Assert.Empty (result.GeneratedJavaSources);
		Assert.Contains (logMessages, message => message.StartsWith ("XA4258:", StringComparison.Ordinal));
		Assert.DoesNotContain (logMessages, message => message.Contains ("No Java peer types found"));
	}

	[Fact]
	public void Execute_AssemblyWithNoPeers_ReturnsEmpty ()
	{
		// Use the test assembly itself — it has no [Register] types
		var testAssemblyPath = typeof (TrimmableTypeMapGeneratorTests).Assembly.Location;
		using var peReader = new PEReader (File.OpenRead (testAssemblyPath));
		var result = CreateGenerator ().Execute (
			[Input ("TestAssembly", peReader)],
			new Version (11, 0),
			new HashSet<string> ());
		Assert.Empty (result.GeneratedAssemblies);
		Assert.Empty (result.GeneratedJavaSources);
		Assert.Contains (logMessages, m => m.Contains ("No Java peer types found"));
	}

	[Fact]
	public void Execute_WithTestFixtures_ProducesOutputs ()
	{
		using var peReader = CreateTestFixturePEReader ();
		var result = CreateGenerator ().Execute ([Input ("TestFixtures", peReader)], new Version (11, 0), new HashSet<string> ());
		Assert.NotEmpty (result.GeneratedAssemblies);
		Assert.NotEmpty (result.GeneratedJavaSources);
		Assert.Contains (result.GeneratedAssemblies, a => a.Name == "_Microsoft.Android.TypeMaps");
		Assert.Contains (result.GeneratedAssemblies, a => a.Name == "_TestFixtures.TypeMap");
	}

	[Fact]
	public void Execute_CanSkipUnusedNonAcwMarshalMethods ()
	{
		using var fullReader = CreateTestFixturePEReader ();
		using var optimizedReader = CreateTestFixturePEReader ();
		var generator = CreateGenerator ();
		var full = generator.Execute ([Input ("TestFixtures", fullReader)], new Version (11, 0), new HashSet<string> ());
		var optimized = generator.Execute (
			[Input ("TestFixtures", optimizedReader)],
			new Version (11, 0),
			new HashSet<string> (),
			collectMarshalMethodsForNonAcw: false);

		var fullActivity = Assert.Single (full.AllPeers, peer => peer.JavaName == "android/app/Activity");
		var optimizedActivity = Assert.Single (optimized.AllPeers, peer => peer.JavaName == "android/app/Activity");
		Assert.NotEmpty (fullActivity.MarshalMethods);
		Assert.Empty (optimizedActivity.MarshalMethods);

		var fullAcw = Assert.Single (full.AllPeers, peer => peer.JavaName == "my/app/MyHelper");
		var optimizedAcw = Assert.Single (optimized.AllPeers, peer => peer.JavaName == "my/app/MyHelper");
		Assert.Equal (
			fullAcw.MarshalMethods.Select (method => (method.JniName, method.JniSignature, method.ManagedMethodName, method.CallManagedMethodDirectly)),
			optimizedAcw.MarshalMethods.Select (method => (method.JniName, method.JniSignature, method.ManagedMethodName, method.CallManagedMethodDirectly)));
		Assert.Equal (full.GeneratedJavaSources, optimized.GeneratedJavaSources);
		Assert.Equal (full.GeneratedAssemblies.Count, optimized.GeneratedAssemblies.Count);
		for (int i = 0; i < full.GeneratedAssemblies.Count; i++) {
			Assert.Equal (full.GeneratedAssemblies [i].Name, optimized.GeneratedAssemblies [i].Name);
			Assert.Equal (full.GeneratedAssemblies [i].Content.ToArray (), optimized.GeneratedAssemblies [i].Content.ToArray ());
		}
	}

	[Fact]
	public void Execute_UnsupportedExportSignatures_ReportCodedDiagnosticsWithoutPartialMembers ()
	{
		using var peReader = CreateTestFixturePEReader ();
		var result = CreateGenerator ().Execute ([Input ("TestFixtures", peReader)], new Version (11, 0), new HashSet<string> ());

		Assert.Equal (11, logMessages.Count (message => message.StartsWith ("XA4263:", StringComparison.Ordinal)));
		Assert.Equal (1, logMessages.Count (message => message.StartsWith ("XA4206:", StringComparison.Ordinal)));
		foreach (var javaName in new [] {
			"my/app/ExportWithUnsupportedManagedParameter",
			"my/app/ExportWithUnsupportedManagedReturn",
			"my/app/ExportFieldWithUnsupportedManagedReturn",
			"my/app/ExportWithGenericMethodParameter",
			"my/app/ExportWithGenericInstantiation",
			"my/app/ExportWithInvalidExportParameterType",
			"my/app/ExportWithInvalidExportParameterKind",
			"my/app/ExportWithGenericExportParameter",
			"my/app/ExportFieldWithInvalidExportParameterType",
			"my/app/GenericExportType",
		}) {
			var peer = result.AllPeers.Single (candidate => candidate.JavaName == javaName);
			Assert.DoesNotContain (peer.MarshalMethods, method => method.ManagedMethodName == "UnsupportedMember");
			Assert.Empty (peer.JavaFields);
			var source = result.GeneratedJavaSources.Single (candidate => candidate.RelativePath == javaName + ".java");
			Assert.DoesNotContain (" unsupported (", source.Content, StringComparison.Ordinal);
			Assert.DoesNotContain ("UNSUPPORTED_FIELD", source.Content, StringComparison.Ordinal);
		}

		foreach (var javaName in new [] {
			"my/app/ExportConstructorUnsupportedManagedParameter",
			"my/app/ExportConstructorInvalidExportParameter",
		}) {
			var peer = result.AllPeers.Single (candidate => candidate.JavaName == javaName);
			Assert.DoesNotContain (peer.MarshalMethods, method => method.IsConstructor && method.IsExport);
		}
	}

	[Fact]
	public void GenerateTypeMapAssemblies_UnchangedFingerprintsSkipAllEmission ()
	{
		var peers = new List<JavaPeerInfo> {
			CreatePeer ("MyApp", "MyApp.MainActivity", "my/app/MainActivity"),
			CreatePeer ("MyLibrary", "MyLibrary.Widget", "my/library/Widget"),
		};
		var fingerprints = new Dictionary<string, byte []> (StringComparer.Ordinal);
		var generator = CreateGenerator ();
		var first = generator.GenerateTypeMapAssemblies (
			peers,
			new Version (11, 0),
			useSharedTypemapUniverse: true,
			(name, fingerprint) => {
				fingerprints.Add (name, fingerprint);
				return true;
			});
		DisposeGeneratedAssemblies (first);

		var second = generator.GenerateTypeMapAssemblies (
			peers,
			new Version (11, 0),
			useSharedTypemapUniverse: true,
			(name, fingerprint) => !fingerprints [name].SequenceEqual (fingerprint));

		Assert.Empty (second);
	}

	[Fact]
	public void Execute_IncrementalCallbackPreservesGeneratedBytes ()
	{
		using var fullReader = CreateTestFixturePEReader ();
		using var incrementalReader = CreateTestFixturePEReader ();
		var generator = CreateGenerator ();
		var full = generator.Execute (
			[Input ("TestFixtures", fullReader)],
			new Version (11, 0),
			new HashSet<string> ());
		var incremental = generator.Execute (
			[Input ("TestFixtures", incrementalReader)],
			new Version (11, 0),
			new HashSet<string> (),
			shouldGenerateTypeMapAssembly: (_, _) => true);

		Assert.Equal (full.GeneratedAssemblies.Count, incremental.GeneratedAssemblies.Count);
		for (int i = 0; i < full.GeneratedAssemblies.Count; i++) {
			Assert.Equal (full.GeneratedAssemblies [i].Name, incremental.GeneratedAssemblies [i].Name);
			Assert.Equal (full.GeneratedAssemblies [i].Content.ToArray (), incremental.GeneratedAssemblies [i].Content.ToArray ());
		}
		DisposeGeneratedAssemblies (full.GeneratedAssemblies);
		DisposeGeneratedAssemblies (incremental.GeneratedAssemblies);
	}

	[Fact]
	public void GenerateTypeMapAssemblies_ChangedCrossAssemblyAliasRegeneratesOwner ()
	{
		var owner = CreatePeer ("Owner", "Owner.JavaObject", "java/lang/Object");
		var alias = CreatePeer ("Alias", "Alias.JavaObject", "java/lang/Object") with {
			IsFromJniTypeSignature = true,
		};
		var unrelatedAliasPeer = CreatePeer ("Alias", "Alias.Widget", "alias/Widget");
		var peers = new List<JavaPeerInfo> { owner, alias, unrelatedAliasPeer };
		var fingerprints = new Dictionary<string, byte []> (StringComparer.Ordinal);
		var generator = CreateGenerator ();
		var first = generator.GenerateTypeMapAssemblies (
			peers,
			new Version (11, 0),
			useSharedTypemapUniverse: true,
			(name, fingerprint) => {
				fingerprints.Add (name, fingerprint);
				return true;
			});
		DisposeGeneratedAssemblies (first);

		peers [1] = alias with {
			ManagedTypeName = "Alias.ChangedJavaObject",
			ManagedTypeShortName = "ChangedJavaObject",
		};
		var regenerated = generator.GenerateTypeMapAssemblies (
			peers,
			new Version (11, 0),
			useSharedTypemapUniverse: true,
			(name, fingerprint) => !fingerprints [name].SequenceEqual (fingerprint));

		var assembly = Assert.Single (regenerated);
		Assert.Equal ("_Owner.TypeMap", assembly.Name);
		DisposeGeneratedAssemblies (regenerated);
	}

	[Fact]
	public void GenerateTypeMapAssemblies_ChangedAssemblySetRegeneratesRoot ()
	{
		var initialPeers = new List<JavaPeerInfo> {
			CreatePeer ("MyApp", "MyApp.MainActivity", "my/app/MainActivity"),
		};
		var fingerprints = new Dictionary<string, byte []> (StringComparer.Ordinal);
		var generator = CreateGenerator ();
		var first = generator.GenerateTypeMapAssemblies (
			initialPeers,
			new Version (11, 0),
			useSharedTypemapUniverse: true,
			(name, fingerprint) => {
				fingerprints.Add (name, fingerprint);
				return true;
			});
		DisposeGeneratedAssemblies (first);

		var peersWithLibrary = new List<JavaPeerInfo> (initialPeers) {
			CreatePeer ("MyLibrary", "MyLibrary.Widget", "my/library/Widget"),
		};
		var regenerated = generator.GenerateTypeMapAssemblies (
			peersWithLibrary,
			new Version (11, 0),
			useSharedTypemapUniverse: true,
			(name, fingerprint) => !fingerprints.TryGetValue (name, out var prior) || !prior.SequenceEqual (fingerprint));

		Assert.Equal (
			["_MyLibrary.TypeMap", "_Microsoft.Android.TypeMaps"],
			regenerated.Select (assembly => assembly.Name));
		DisposeGeneratedAssemblies (regenerated);
	}

	[Fact]
	public void Execute_CollectsDeferredRegistrationTypes_ForAllApplicationAndInstrumentationSubtypes ()
	{
		using var peReader = CreateTestFixturePEReader ();
		var result = CreateGenerator ().Execute ([Input ("TestFixtures", peReader)], new Version (11, 0), new HashSet<string> ());

		// Abstract Instrumentation/Application subtypes are included too: their native
		// methods (e.g. n_OnCreate, n_OnStart) are declared on the abstract base class
		// and must be registered via ApplicationRegistration.registerApplications ().
		Assert.Contains ("my.app.MyApplication", result.ApplicationRegistrationTypes);
		Assert.Contains ("my.app.MyInstrumentation", result.ApplicationRegistrationTypes);
		Assert.Contains ("my.app.BaseApplication", result.ApplicationRegistrationTypes);
		Assert.Contains ("my.app.BaseInstrumentation", result.ApplicationRegistrationTypes);
		Assert.Contains ("my.app.IntermediateInstrumentation", result.ApplicationRegistrationTypes);
	}

	static JavaPeerInfo CreatePeer (string assemblyName, string managedTypeName, string javaName)
	{
		int separator = managedTypeName.LastIndexOf ('.');
		return new JavaPeerInfo {
			JavaName = javaName,
			CompatJniName = javaName,
			ManagedTypeName = managedTypeName,
			ManagedTypeNamespace = separator < 0 ? "" : managedTypeName.Substring (0, separator),
			ManagedTypeShortName = separator < 0 ? managedTypeName : managedTypeName.Substring (separator + 1),
			AssemblyName = assemblyName,
			DoNotGenerateAcw = true,
		};
	}

	static void DisposeGeneratedAssemblies (IEnumerable<GeneratedAssembly> assemblies)
	{
		foreach (var assembly in assemblies) {
			assembly.Content.Dispose ();
		}
	}

	[Fact]
	public void CollectApplicationRegistrationTypes_ExcludesLegacyFrameworkDescendants ()
	{
		var peers = new List<JavaPeerInfo> {
			new JavaPeerInfo {
				JavaName = "android/app/Application", CompatJniName = "android.app.Application",
				ManagedTypeName = "Android.App.Application", ManagedTypeNamespace = "Android.App", ManagedTypeShortName = "Application",
				AssemblyName = "Mono.Android", DoNotGenerateAcw = true, CannotRegisterInStaticConstructor = true,
			},
			new JavaPeerInfo {
				JavaName = "android/app/Instrumentation", CompatJniName = "android.app.Instrumentation",
				ManagedTypeName = "Android.App.Instrumentation", ManagedTypeNamespace = "Android.App", ManagedTypeShortName = "Instrumentation",
				AssemblyName = "Mono.Android", DoNotGenerateAcw = true, CannotRegisterInStaticConstructor = true,
			},
			new JavaPeerInfo {
				JavaName = "android/test/InstrumentationTestRunner", CompatJniName = "android.test.InstrumentationTestRunner",
				ManagedTypeName = "Android.Test.InstrumentationTestRunner", ManagedTypeNamespace = "Android.Test", ManagedTypeShortName = "InstrumentationTestRunner",
				AssemblyName = "Mono.Android", BaseJavaName = "android/app/Instrumentation", DoNotGenerateAcw = true, CannotRegisterInStaticConstructor = true,
			},
			new JavaPeerInfo {
				JavaName = "android/test/mock/MockApplication", CompatJniName = "android.test.mock.MockApplication",
				ManagedTypeName = "Android.Test.Mock.MockApplication", ManagedTypeNamespace = "Android.Test.Mock", ManagedTypeShortName = "MockApplication",
				AssemblyName = "Mono.Android", BaseJavaName = "android/app/Application", DoNotGenerateAcw = true, CannotRegisterInStaticConstructor = true,
			},
			new JavaPeerInfo {
				JavaName = "my/app/BaseInstrumentation", CompatJniName = "my.app.BaseInstrumentation",
				ManagedTypeName = "My.App.BaseInstrumentation", ManagedTypeNamespace = "My.App", ManagedTypeShortName = "BaseInstrumentation",
				AssemblyName = "MyApp", IsAbstract = true, CannotRegisterInStaticConstructor = true,
			},
			new JavaPeerInfo {
				JavaName = "my/app/MyInstrumentation", CompatJniName = "my.app.MyInstrumentation",
				ManagedTypeName = "My.App.MyInstrumentation", ManagedTypeNamespace = "My.App", ManagedTypeShortName = "MyInstrumentation",
				AssemblyName = "MyApp", BaseJavaName = "my/app/BaseInstrumentation", CannotRegisterInStaticConstructor = true,
			},
		};

		var types = TrimmableTypeMapGenerator.CollectApplicationRegistrationTypes (peers);

		Assert.Contains ("android.app.Application", types);
		Assert.Contains ("android.app.Instrumentation", types);
		Assert.Contains ("my.app.BaseInstrumentation", types);
		Assert.Contains ("my.app.MyInstrumentation", types);
		Assert.DoesNotContain ("android.test.InstrumentationTestRunner", types);
		Assert.DoesNotContain ("android.test.mock.MockApplication", types);
	}

	[Fact]
	public void Execute_NullAssemblyList_Throws ()
	{
		IReadOnlyList<AssemblyInput>? n = null;
#pragma warning disable CS8604
		Assert.Throws<ArgumentNullException> (() => CreateGenerator ().Execute (n, new Version (11, 0), new HashSet<string> ()));
#pragma warning restore CS8604
	}

	[Fact]
	public void Execute_GeneratedAssembliesAreValidPE ()
	{
		using var peReader = CreateTestFixturePEReader ();
		var result = CreateGenerator ().Execute ([Input ("TestFixtures", peReader)], new Version (11, 0), new HashSet<string> ());
		foreach (var assembly in result.GeneratedAssemblies) {
			assembly.Content.Position = 0;
			using var vr = new PEReader (assembly.Content, PEStreamOptions.LeaveOpen);
			var md = vr.GetMetadataReader ();
			Assert.Equal (assembly.Name, md.GetString (md.GetAssemblyDefinition ().Name));
		}
	}

	[Fact]
	public void Execute_JavaSourcesHaveCorrectStructure ()
	{
		using var peReader = CreateTestFixturePEReader ();
		var result = CreateGenerator ().Execute ([Input ("TestFixtures", peReader)], new Version (11, 0), new HashSet<string> ());
		foreach (var source in result.GeneratedJavaSources)
			Assert.Contains ("class ", source.Content);
	}

	[Fact]
	public void Execute_FrameworkAssembly_GeneratesFrameworkJcwTypes ()
	{
		using var peReader = CreateTestFixturePEReader ();
		var result = CreateGenerator ().Execute (
			[Input ("Mono.Android", peReader)],
			new Version (11, 0),
			new HashSet<string> (StringComparer.OrdinalIgnoreCase) { "Mono.Android" });

		Assert.Contains (result.GeneratedJavaSources, s => s.RelativePath == "xamarin/android/net/ServerCertificateCustomValidator_TrustManager.java");
		Assert.Contains (result.GeneratedJavaSources, s => s.RelativePath == "xamarin/android/net/ServerCertificateCustomValidator_TrustManager_FakeSSLSession.java");
		Assert.Contains (result.GeneratedJavaSources, s => s.RelativePath == "xamarin/android/net/ServerCertificateCustomValidator_AlwaysAcceptingHostnameVerifier.java");
		Assert.Contains (result.GeneratedJavaSources, s => s.RelativePath == "xamarin/android/net/ServerCertificateCustomValidator_NonRequiredFrameworkAcw.java");
	}

	[Fact]
	public void Execute_ManifestPlaceholdersAreResolvedBeforeRooting ()
	{
		using var peReader = CreateTestFixturePEReader ();
		var manifestTemplate = System.Xml.Linq.XDocument.Parse ("""
			<?xml version="1.0" encoding="utf-8"?>
			<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="${PACKAGENAME}">
			  <application>
			    <activity android:name=".SimpleActivity" />
			  </application>
			</manifest>
			""");

		var result = CreateGenerator ().Execute (
			[Input ("TestFixtures", peReader)],
			new Version (11, 0),
			new HashSet<string> (),
			useSharedTypemapUniverse: false,
			new ManifestConfig (
				PackageName: "my.app",
				AndroidApiLevel: "35",
				SupportedOSPlatformVersion: "24",
				RuntimeProviderJavaName: "mono.MonoRuntimeProvider"),
			manifestTemplate);

		var peer = result.AllPeers.First (p => p.ManagedTypeName == "MyApp.SimpleActivity");
		Assert.True (peer.IsUnconditional, "Unresolved template packages should use PackageName before expanding relative components.");
		Assert.DoesNotContain (logMessages, message => message.StartsWith ("XA4258:", StringComparison.Ordinal));
	}

	[Fact]
	public void Execute_InvalidResolvedPackageBeforeRelativeComponent_ReportsBeforeOutputs ()
	{
		using var peReader = CreateTestFixturePEReader ();
		var manifestTemplate = XDocument.Parse ("""
			<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="${PACKAGENAME}">
			  <application>
			    <activity android:name=".SimpleActivity" />
			  </application>
			</manifest>
			""");

		var result = CreateGenerator ().Execute (
			[Input ("TestFixtures", peReader)],
			new Version (11, 0),
			new HashSet<string> (),
			manifestConfig: new ManifestConfig (
				PackageName: "com.¢pkg",
				AndroidApiLevel: "35",
				SupportedOSPlatformVersion: "24",
				RuntimeProviderJavaName: "mono.MonoRuntimeProvider"),
			manifestTemplate: manifestTemplate);

		Assert.Empty (result.GeneratedAssemblies);
		Assert.Empty (result.GeneratedJavaSources);
		Assert.Contains (logMessages, message =>
			message.Contains ("Java name 'com.¢pkg.SimpleActivity' contains invalid or unsupported Java identifier '¢pkg'."));
	}

	[Fact]
	public void Execute_ActivityAliasPlaceholdersAreResolvedBeforeValidationAndRooting ()
	{
		using var peReader = CreateTestFixturePEReader ();
		var manifestTemplate = XDocument.Parse ("""
			<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="${applicationId}">
			  <application>
			    <activity-alias
			        android:name="${applicationId}.UnnamedAlias"
			        android:targetActivity="${targetPackage}.UnnamedActivity" />
			  </application>
			</manifest>
			""");

		var result = CreateGenerator ().Execute (
			[Input ("TestFixtures", peReader)],
			new Version (11, 0),
			new HashSet<string> (),
			manifestConfig: new ManifestConfig (
				PackageName: "my.app",
				AndroidApiLevel: "35",
				SupportedOSPlatformVersion: "24",
				RuntimeProviderJavaName: "mono.MonoRuntimeProvider",
				ManifestPlaceholders: "targetPackage=myapp"),
			manifestTemplate: manifestTemplate);

		var peer = result.AllPeers.First (candidate => candidate.ManagedTypeName == "MyApp.UnnamedActivity");
		Assert.True (peer.IsUnconditional, "The activity-alias target should root its Java peer.");
		Assert.NotEmpty (result.GeneratedJavaSources);
		Assert.DoesNotContain (logMessages, message => message.StartsWith ("XA4258:", StringComparison.Ordinal));
		var alias = Assert.Single (result.Manifest?.Document.Descendants ("activity-alias") ?? []);
		XNamespace android = "http://schemas.android.com/apk/res/android";
		Assert.Equal ("my.app.UnnamedAlias", (string?) alias.Attribute (android + "name"));
		Assert.Equal (
			JniSignatureHelper.JniNameToJavaBinaryName (peer.JavaName),
			(string?) alias.Attribute (android + "targetActivity")
		);
		Assert.NotEqual ("myapp.UnnamedActivity", (string?) alias.Attribute (android + "targetActivity"));
	}

	[Theory]
	[InlineData ("${applicationId}.¢Alias", "${applicationId}.SimpleActivity", "com.example.¢Alias", "¢Alias")]
	[InlineData ("${applicationId}.SimpleAlias", "${applicationId}.¢Peer", "com.example.¢Peer", "¢Peer")]
	public void Execute_InvalidActivityAliasNameOrTarget_ReportsBeforeOutputs (
		string aliasName,
		string targetActivity,
		string invalidName,
		string invalidIdentifier)
	{
		using var peReader = CreateTestFixturePEReader ();
		var manifestTemplate = XDocument.Parse ($$"""
			<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="${applicationId}">
			  <application>
			    <activity-alias android:name="{{aliasName}}" android:targetActivity="{{targetActivity}}" />
			  </application>
			</manifest>
			""");

		var result = CreateGenerator ().Execute (
			[Input ("TestFixtures", peReader)],
			new Version (11, 0),
			new HashSet<string> (),
			manifestConfig: new ManifestConfig (
				PackageName: "com.example",
				AndroidApiLevel: "35",
				SupportedOSPlatformVersion: "24",
				RuntimeProviderJavaName: "mono.MonoRuntimeProvider"),
			manifestTemplate: manifestTemplate);

		Assert.Empty (result.GeneratedAssemblies);
		Assert.Empty (result.GeneratedJavaSources);
		Assert.Contains (logMessages, message =>
			message.Contains (
				$"Java name '{invalidName}' contains invalid or unsupported Java identifier '{invalidIdentifier}'.",
				StringComparison.Ordinal
			)
		);
	}

	[Theory]
	[InlineData (StaleReferenceShape.BaseType, "MissingDependency.MissingBase")]
	[InlineData (StaleReferenceShape.Interface, "MissingDependency.IMissingInterface")]
	[InlineData (StaleReferenceShape.GenericBaseArgument, "MissingDependency.MissingArgument")]
	[InlineData (StaleReferenceShape.GenericConstraint, "MissingDependency.MissingConstraint")]
	public void Execute_SkipsJavaPeerWithUnresolvableBaseInterfaceOrGenericArgumentTypeRef (StaleReferenceShape shape, string unresolvedTypeName)
	{
		var warnings = new List<string> ();
		var peerPath = Path.Combine (Path.GetTempPath (), "StalePeerAssembly.dll");
		var missingDependencyPath = Path.Combine (Path.GetTempPath (), "MissingDependency.dll");
		using var peerStream = CreateStaleJavaPeerAssembly (shape);
		using var missingDependencyStream = CreateEmptyAssembly ("MissingDependency");
		using var peerReader = new PEReader (peerStream, PEStreamOptions.LeaveOpen);
		using var missingDependencyReader = new PEReader (missingDependencyStream, PEStreamOptions.LeaveOpen);

		var result = CreateGenerator (warnings).Execute (
			[
				new AssemblyInput ("StalePeerAssembly", peerPath, peerReader),
				new AssemblyInput ("MissingDependency", missingDependencyPath, missingDependencyReader),
			],
			new Version (11, 0),
			new HashSet<string> ());

		Assert.DoesNotContain (result.AllPeers, p => p.ManagedTypeName == "Test.BrokenPeer");
		var warning = Assert.Single (warnings);
		Assert.Contains ("Test.BrokenPeer", warning);
		Assert.Contains (unresolvedTypeName, warning);
		Assert.Contains ("MissingDependency", warning);
		Assert.Contains (missingDependencyPath, warning);
	}

	[Fact]
	public void Execute_DoesNotSkipJavaPeer_WhenReferencedAssemblyIsNotScanned ()
	{
		// The base type's assembly ('MissingDependency') is not part of the scanned
		// set, so the scanner cannot prove the reference is stale. Existing behavior
		// must be preserved: the peer is kept and no XA4257 is emitted.
		var warnings = new List<string> ();
		var peerPath = Path.Combine (Path.GetTempPath (), "StalePeerAssembly.dll");
		using var peerStream = CreateStaleJavaPeerAssembly (StaleReferenceShape.BaseType);
		using var peerReader = new PEReader (peerStream, PEStreamOptions.LeaveOpen);

		var result = CreateGenerator (warnings).Execute (
			[new AssemblyInput ("StalePeerAssembly", peerPath, peerReader)],
			new Version (11, 0),
			new HashSet<string> ());

		Assert.Contains (result.AllPeers, p => p.ManagedTypeName == "Test.BrokenPeer");
		Assert.Empty (warnings);
	}

	[Fact]
	public void Execute_DoesNotSkipJavaPeer_WhenBaseTypeIsTypeForwarded ()
	{
		// 'MissingDependency' is scanned but does not define 'MissingBase' — it only
		// re-exports it via a type-forward row. The scanner must treat the reference
		// as resolvable through AssemblyIndex.ExportedTypeNames and keep the peer.
		var warnings = new List<string> ();
		var peerPath = Path.Combine (Path.GetTempPath (), "StalePeerAssembly.dll");
		var forwardingPath = Path.Combine (Path.GetTempPath (), "MissingDependency.dll");
		using var peerStream = CreateStaleJavaPeerAssembly (StaleReferenceShape.BaseType);
		using var forwardingStream = CreateAssemblyForwardingType ("MissingDependency", "MissingDependency", "MissingBase");
		using var peerReader = new PEReader (peerStream, PEStreamOptions.LeaveOpen);
		using var forwardingReader = new PEReader (forwardingStream, PEStreamOptions.LeaveOpen);

		var result = CreateGenerator (warnings).Execute (
			[
				new AssemblyInput ("StalePeerAssembly", peerPath, peerReader),
				new AssemblyInput ("MissingDependency", forwardingPath, forwardingReader),
			],
			new Version (11, 0),
			new HashSet<string> ());

		Assert.Contains (result.AllPeers, p => p.ManagedTypeName == "Test.BrokenPeer");
		Assert.Empty (warnings);
	}

	TrimmableTypeMapGenerator CreateGenerator () => new (new TestTrimmableTypeMapLogger (logMessages));

	TrimmableTypeMapGenerator CreateGenerator (List<string> warnings) =>
		new (new TestTrimmableTypeMapLogger (logMessages, warnings));

	static AssemblyInput Input (string name, PEReader reader) => new (name, "", reader);

	public enum StaleReferenceShape {
		BaseType,
		Interface,
		GenericBaseArgument,
		GenericConstraint,
	}

	static MemoryStream CreateEmptyAssembly (string assemblyName)
	{
		var stream = new MemoryStream ();
		var pe = new PEAssemblyBuilder (new Version (11, 0, 0, 0));
		pe.EmitPreamble (assemblyName, assemblyName + ".dll");
		pe.WritePE (stream);
		stream.Position = 0;
		return stream;
	}

	static MemoryStream CreateAssemblyForwardingType (string assemblyName, string ns, string typeName)
	{
		var stream = new MemoryStream ();
		var pe = new PEAssemblyBuilder (new Version (11, 0, 0, 0));
		pe.EmitPreamble (assemblyName, assemblyName + ".dll");

		var forwardTargetRef = pe.FindOrAddAssemblyRef ("ForwardTarget");
		// 0x00200000 is the type-forwarder flag (TypeAttributes has no named constant for it).
		pe.Metadata.AddExportedType (
			(TypeAttributes) 0x00200000,
			pe.Metadata.GetOrAddString (ns),
			pe.Metadata.GetOrAddString (typeName),
			forwardTargetRef,
			typeDefinitionId: 0);

		pe.WritePE (stream);
		stream.Position = 0;
		return stream;
	}

	static MemoryStream CreateStaleJavaPeerAssembly (StaleReferenceShape shape)
	{
		var stream = new MemoryStream ();
		var pe = new PEAssemblyBuilder (new Version (11, 0, 0, 0));
		pe.EmitPreamble ("StalePeerAssembly", "StalePeerAssembly.dll");

		var missingTypeName = shape switch {
			StaleReferenceShape.Interface => "IMissingInterface",
			StaleReferenceShape.GenericBaseArgument => "MissingArgument",
			StaleReferenceShape.GenericConstraint => "MissingConstraint",
			_ => "MissingBase",
		};
		var missingDependencyRef = pe.FindOrAddAssemblyRef ("MissingDependency");
		var missingTypeRef = pe.Metadata.AddTypeReference (
			missingDependencyRef,
			pe.Metadata.GetOrAddString ("MissingDependency"),
			pe.Metadata.GetOrAddString (missingTypeName));
		var objectRef = pe.Metadata.AddTypeReference (
			pe.SystemRuntimeRef,
			pe.Metadata.GetOrAddString ("System"),
			pe.Metadata.GetOrAddString ("Object"));
		EntityHandle peerBaseType = shape switch {
			StaleReferenceShape.BaseType => missingTypeRef,
			StaleReferenceShape.GenericBaseArgument => CreateGenericBaseTypeSpec (pe, objectRef, missingTypeRef),
			_ => objectRef,
		};

		var registerAttributeRef = pe.Metadata.AddTypeReference (
			pe.MonoAndroidRef,
			pe.Metadata.GetOrAddString ("Android.Runtime"),
			pe.Metadata.GetOrAddString ("RegisterAttribute"));
		var registerCtorRef = pe.AddMemberRef (registerAttributeRef, ".ctor",
			sig => sig.MethodSignature (isInstanceMethod: true).Parameters (1,
				rt => rt.Void (),
				p => p.AddParameter ().Type ().String ()));

		var peerType = pe.Metadata.AddTypeDefinition (
			TypeAttributes.Public | TypeAttributes.Class | TypeAttributes.BeforeFieldInit,
			pe.Metadata.GetOrAddString ("Test"),
			pe.Metadata.GetOrAddString ("BrokenPeer"),
			peerBaseType,
			MetadataTokens.FieldDefinitionHandle (pe.Metadata.GetRowCount (TableIndex.Field) + 1),
			MetadataTokens.MethodDefinitionHandle (pe.Metadata.GetRowCount (TableIndex.MethodDef) + 1));
		pe.Metadata.AddCustomAttribute (
			peerType,
			registerCtorRef,
			pe.BuildAttributeBlob (b => b.WriteSerializedString ("test/BrokenPeer")));

		if (shape == StaleReferenceShape.Interface) {
			pe.Metadata.AddInterfaceImplementation (peerType, missingTypeRef);
		}

		if (shape == StaleReferenceShape.GenericConstraint) {
			var genericParameter = pe.Metadata.AddGenericParameter (
				peerType,
				GenericParameterAttributes.None,
				pe.Metadata.GetOrAddString ("T"),
				0);
			pe.Metadata.AddGenericParameterConstraint (genericParameter, missingTypeRef);
		}

		pe.WritePE (stream);
		stream.Position = 0;
		return stream;
	}

	static TypeSpecificationHandle CreateGenericBaseTypeSpec (PEAssemblyBuilder pe, EntityHandle objectRef, TypeReferenceHandle missingTypeRef)
	{
		var genericBaseType = pe.Metadata.AddTypeDefinition (
			TypeAttributes.Public | TypeAttributes.Class | TypeAttributes.BeforeFieldInit,
			pe.Metadata.GetOrAddString ("Test"),
			pe.Metadata.GetOrAddString ("GenericBase`1"),
			objectRef,
			MetadataTokens.FieldDefinitionHandle (pe.Metadata.GetRowCount (TableIndex.Field) + 1),
			MetadataTokens.MethodDefinitionHandle (pe.Metadata.GetRowCount (TableIndex.MethodDef) + 1));
		pe.Metadata.AddGenericParameter (
			genericBaseType,
			GenericParameterAttributes.None,
			pe.Metadata.GetOrAddString ("T"),
			0);

		var signature = new BlobBuilder ();
		signature.WriteByte ((byte) SignatureTypeCode.GenericTypeInstance);
		signature.WriteByte ((byte) SignatureTypeKind.Class);
		signature.WriteCompressedInteger (CodedIndex.TypeDefOrRefOrSpec (genericBaseType));
		signature.WriteCompressedInteger (1);
		signature.WriteByte ((byte) SignatureTypeKind.Class);
		signature.WriteCompressedInteger (CodedIndex.TypeDefOrRefOrSpec (missingTypeRef));
		return pe.Metadata.AddTypeSpecification (pe.Metadata.GetOrAddBlob (signature));
	}

	[Theory]
	[InlineData ("com/example/MyActivity", "com.example.MyActivity", "com.example", "activity", "com.example.MyActivity")]
	[InlineData ("com/example/MyActivity", "com.example.MyActivity", "com.example", "activity", ".MyActivity")]
	[InlineData ("com/example/MyService", "com.example.MyService", "com.example", "service", "MyService")]
	[InlineData ("crc64123456789abc/MyActivity", "my/app/MyActivity", "my.app", "activity", ".MyActivity")]
	[InlineData ("com/example/Outer$Inner", "com.example.Outer$Inner", "com.example", "activity", "com.example.Outer$Inner")]
	public void RootManifestReferencedTypes_RootsManifestReferencedTypes (
		string javaName,
		string compatJniName,
		string packageName,
		string elementName,
		string manifestName)
	{
		var peers = new List<JavaPeerInfo> {
			new JavaPeerInfo {
				JavaName = javaName, CompatJniName = compatJniName,
				ManagedTypeName = "MyApp.MyTarget", ManagedTypeNamespace = "MyApp", ManagedTypeShortName = "MyTarget",
				AssemblyName = "MyApp", IsUnconditional = false,
			},
			new JavaPeerInfo {
				JavaName = "com/example/OtherType", CompatJniName = "com.example.OtherType",
				ManagedTypeName = "MyApp.OtherType", ManagedTypeNamespace = "MyApp", ManagedTypeShortName = "OtherType",
				AssemblyName = "MyApp", IsUnconditional = false,
			},
		};

		var doc = System.Xml.Linq.XDocument.Parse ($$"""
			<?xml version="1.0" encoding="utf-8"?>
			<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="{{packageName}}">
			  <application>
			    <{{elementName}} android:name="{{manifestName}}" />
			  </application>
			</manifest>
			""");

		var generator = CreateGenerator ();
		generator.RootManifestReferencedTypes (peers, doc);

		Assert.True (peers [0].IsUnconditional, "The manifest-referenced type should be rooted as unconditional.");
		Assert.False (peers [1].IsUnconditional, "Non-matching peers should remain conditional.");
		Assert.Contains (logMessages, m => m.Contains ("Rooting manifest-referenced type"));
	}

	[Fact]
	public void RootCustomViewTypes_RootsReferencedManagedJavaAndCompatNames ()
	{
		var peers = new List<JavaPeerInfo> {
			new JavaPeerInfo {
				JavaName = "crc64123456789abc/CustomView", CompatJniName = "my.app.CustomView",
				ManagedTypeName = "MyApp.CustomView", ManagedTypeNamespace = "MyApp", ManagedTypeShortName = "CustomView",
				AssemblyName = "MyApp",
			},
			new JavaPeerInfo {
				JavaName = "com/example/RegisteredView", CompatJniName = "com/example/RegisteredView",
				ManagedTypeName = "MyApp.RegisteredView", ManagedTypeNamespace = "MyApp", ManagedTypeShortName = "RegisteredView",
				AssemblyName = "MyApp",
			},
			new JavaPeerInfo {
				JavaName = "crc64123456789abc/CompatView", CompatJniName = "my/app/CompatView",
				ManagedTypeName = "MyApp.CompatView", ManagedTypeNamespace = "MyApp", ManagedTypeShortName = "CompatView",
				AssemblyName = "MyApp",
			},
			new JavaPeerInfo {
				JavaName = "crc64123456789abc/UnusedView", CompatJniName = "my.app.UnusedView",
				ManagedTypeName = "MyApp.UnusedView", ManagedTypeNamespace = "MyApp", ManagedTypeShortName = "UnusedView",
				AssemblyName = "MyApp",
			},
		};

		TrimmableTypeMapGenerator.RootCustomViewTypes (peers, [
			"MyApp.CustomView",
			"com.example.RegisteredView",
			"my.app.CompatView",
		]);

		Assert.True (peers [0].IsUnconditional);
		Assert.True (peers [1].IsUnconditional);
		Assert.True (peers [2].IsUnconditional);
		Assert.False (peers [3].IsUnconditional);
	}

	[Fact]
	public void RootManifestReferencedTypes_RootsApplicationAndInstrumentationTypes ()
	{
		var peers = new List<JavaPeerInfo> {
			new JavaPeerInfo {
				JavaName = "com/example/MyApplication", CompatJniName = "com.example.MyApplication",
				ManagedTypeName = "MyApp.MyApplication", ManagedTypeNamespace = "MyApp", ManagedTypeShortName = "MyApplication",
				AssemblyName = "MyApp", IsUnconditional = false,
			},
			new JavaPeerInfo {
				JavaName = "com/example/MyInstrumentation", CompatJniName = "com.example.MyInstrumentation",
				ManagedTypeName = "MyApp.MyInstrumentation", ManagedTypeNamespace = "MyApp", ManagedTypeShortName = "MyInstrumentation",
				AssemblyName = "MyApp", IsUnconditional = false,
			},
		};

		var doc = System.Xml.Linq.XDocument.Parse ("""
			<?xml version="1.0" encoding="utf-8"?>
			<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.example">
			  <application android:name=".MyApplication" />
			  <instrumentation android:name="MyInstrumentation" />
			</manifest>
			""");

		var generator = CreateGenerator ();
		generator.RootManifestReferencedTypes (peers, doc);

		Assert.True (peers [0].IsUnconditional, "Application type should be rooted from <application android:name>.");
		Assert.True (peers [1].IsUnconditional, "Instrumentation type should be rooted from <instrumentation android:name>.");
		Assert.True (peers [0].CannotRegisterInStaticConstructor, "Application type should defer Runtime.registerNatives().");
		Assert.True (peers [1].CannotRegisterInStaticConstructor, "Instrumentation type should defer Runtime.registerNatives().");
	}

	[Fact]
	public void PropagateDeferredRegistrationToBaseClasses_PropagatesToBaseClassesOfManifestReferencedTypes ()
	{
		var basePeer = new JavaPeerInfo {
			JavaName = "crc64aaa/TestInstrumentation_1", CompatJniName = "crc64aaa/TestInstrumentation_1",
			ManagedTypeName = "Tests.TestInstrumentation`1", ManagedTypeNamespace = "Tests", ManagedTypeShortName = "TestInstrumentation`1",
			AssemblyName = "Tests", IsUnconditional = false,
			BaseJavaName = "android/app/Instrumentation",
		};
		var midPeer = new JavaPeerInfo {
			JavaName = "crc64bbb/NUnitTestInstrumentation", CompatJniName = "crc64bbb/NUnitTestInstrumentation",
			ManagedTypeName = "Tests.NUnitTestInstrumentation", ManagedTypeNamespace = "Tests", ManagedTypeShortName = "NUnitTestInstrumentation",
			AssemblyName = "Tests", IsUnconditional = false,
			BaseJavaName = "crc64aaa/TestInstrumentation_1",
		};
		var leafPeer = new JavaPeerInfo {
			JavaName = "crc64ccc/NUnitInstrumentation", CompatJniName = "crc64ccc/NUnitInstrumentation",
			ManagedTypeName = "Tests.NUnitInstrumentation", ManagedTypeNamespace = "Tests", ManagedTypeShortName = "NUnitInstrumentation",
			AssemblyName = "Tests", IsUnconditional = false,
			BaseJavaName = "crc64bbb/NUnitTestInstrumentation",
		};
		var peers = new List<JavaPeerInfo> { basePeer, midPeer, leafPeer };

		var doc = System.Xml.Linq.XDocument.Parse ("""
			<?xml version="1.0" encoding="utf-8"?>
			<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.example">
			  <instrumentation android:name="crc64ccc.NUnitInstrumentation" />
			</manifest>
			""");

		var generator = CreateGenerator ();
		generator.RootManifestReferencedTypes (peers, doc);

		// RootManifestReferencedTypes sets the flag only on the directly matched leaf
		Assert.True (leafPeer.CannotRegisterInStaticConstructor, "Leaf instrumentation should have deferred registration after manifest rooting.");
		Assert.False (midPeer.CannotRegisterInStaticConstructor, "Mid peer should NOT have deferred registration before propagation.");
		Assert.False (basePeer.CannotRegisterInStaticConstructor, "Base peer should NOT have deferred registration before propagation.");

		// PropagateDeferredRegistrationToBaseClasses walks the BaseJavaName chain
		TrimmableTypeMapGenerator.PropagateDeferredRegistrationToBaseClasses (peers);

		Assert.True (leafPeer.CannotRegisterInStaticConstructor, "Leaf instrumentation should still have deferred registration.");
		Assert.True (midPeer.CannotRegisterInStaticConstructor, "Mid peer should have deferred registration after propagation.");
		Assert.True (basePeer.CannotRegisterInStaticConstructor, "Base peer should have deferred registration after propagation.");
	}

	[Fact]
	public void RootManifestReferencedTypes_WarnsForUnresolvedTypes ()
	{
		var peers = new List<JavaPeerInfo> {
			new JavaPeerInfo {
				JavaName = "com/example/MyActivity", CompatJniName = "com.example.MyActivity",
				ManagedTypeName = "MyApp.MyActivity", ManagedTypeNamespace = "MyApp", ManagedTypeShortName = "MyActivity",
				AssemblyName = "MyApp",
			},
		};

		var doc = System.Xml.Linq.XDocument.Parse ("""
			<?xml version="1.0" encoding="utf-8"?>
			<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.example">
			  <application>
			    <service android:name="com.example.NonExistentService" />
			  </application>
			</manifest>
			""");

		var warnings = new List<string> ();
		var generator = CreateGenerator (warnings);
		generator.RootManifestReferencedTypes (peers, doc);

		Assert.Contains (warnings, w => w.Contains ("com.example.NonExistentService"));
	}

	[Fact]
	public void RootManifestReferencedTypes_DoesNotWarnForApplicationJavaClass ()
	{
		// android.support.multidex.MultiDexApplication (injected via $(AndroidApplicationJavaClass)
		// when $(AndroidEnableMultiDex) is true) is a Java framework type with no managed peer,
		// so it must not produce an XA4250 "not found in any scanned assembly" warning.
		var peers = new List<JavaPeerInfo> {
			new JavaPeerInfo {
				JavaName = "com/example/MyActivity", CompatJniName = "com.example.MyActivity",
				ManagedTypeName = "MyApp.MyActivity", ManagedTypeNamespace = "MyApp", ManagedTypeShortName = "MyActivity",
				AssemblyName = "MyApp",
			},
		};

		var doc = System.Xml.Linq.XDocument.Parse ("""
			<?xml version="1.0" encoding="utf-8"?>
			<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.example">
			  <application android:name="android.support.multidex.MultiDexApplication" />
			</manifest>
			""");

		var warnings = new List<string> ();
		var generator = CreateGenerator (warnings);
		generator.RootManifestReferencedTypes (peers, doc, "android.support.multidex.MultiDexApplication");

		Assert.DoesNotContain (warnings, w => w.Contains ("MultiDexApplication"));
	}

	[Fact]
	public void RootManifestReferencedTypes_SkipsAlreadyUnconditional ()
	{
		var peers = new List<JavaPeerInfo> {
			new JavaPeerInfo {
				JavaName = "com/example/MyActivity", CompatJniName = "com.example.MyActivity",
				ManagedTypeName = "MyApp.MyActivity", ManagedTypeNamespace = "MyApp", ManagedTypeShortName = "MyActivity",
				AssemblyName = "MyApp", IsUnconditional = true,
			},
		};

		var doc = System.Xml.Linq.XDocument.Parse ("""
			<?xml version="1.0" encoding="utf-8"?>
			<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.example">
			  <application>
			    <activity android:name="com.example.MyActivity" />
			  </application>
			</manifest>
			""");

		var generator = CreateGenerator ();
		generator.RootManifestReferencedTypes (peers, doc);

		Assert.True (peers [0].IsUnconditional);
		Assert.DoesNotContain (logMessages, m => m.Contains ("Rooting manifest-referenced type"));
	}

	[Fact]
	public void RootManifestReferencedTypes_EmptyManifest_NoChanges ()
	{
		var peers = new List<JavaPeerInfo> {
			new JavaPeerInfo {
				JavaName = "com/example/MyActivity", CompatJniName = "com.example.MyActivity",
				ManagedTypeName = "MyApp.MyActivity", ManagedTypeNamespace = "MyApp", ManagedTypeShortName = "MyActivity",
				AssemblyName = "MyApp",
			},
		};

		var doc = System.Xml.Linq.XDocument.Parse ("""
			<?xml version="1.0" encoding="utf-8"?>
			<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.example">
			</manifest>
			""");

		var generator = CreateGenerator ();
		generator.RootManifestReferencedTypes (peers, doc);

		Assert.False (peers [0].IsUnconditional);
	}

	[Fact]
	public void MergeCrossAssemblyAliases_RegisterTakesPrecedenceOverJniTypeSignature ()
	{
		// Java.Interop has JavaObject with [JniTypeSignature("java/lang/Object")]
		var javaInteropPeer = new JavaPeerInfo {
			JavaName = "java/lang/Object", CompatJniName = "java/lang/Object",
			ManagedTypeName = "Java.Interop.JavaObject", ManagedTypeNamespace = "Java.Interop", ManagedTypeShortName = "JavaObject",
			AssemblyName = "Java.Interop", IsFromJniTypeSignature = true, DoNotGenerateAcw = true,
		};

		// Mono.Android has Java.Lang.Object with [Register("java/lang/Object")]
		var monoAndroidPeer = new JavaPeerInfo {
			JavaName = "java/lang/Object", CompatJniName = "java/lang/Object",
			ManagedTypeName = "Java.Lang.Object", ManagedTypeNamespace = "Java.Lang", ManagedTypeShortName = "Object",
			AssemblyName = "Mono.Android", IsFromJniTypeSignature = false, DoNotGenerateAcw = true,
		};

		// Another unique peer in Java.Interop that shouldn't be moved
		var otherPeer = new JavaPeerInfo {
			JavaName = "java/interop/SomeHelper", CompatJniName = "java/interop/SomeHelper",
			ManagedTypeName = "Java.Interop.SomeHelper", ManagedTypeNamespace = "Java.Interop", ManagedTypeShortName = "SomeHelper",
			AssemblyName = "Java.Interop", IsFromJniTypeSignature = true,
		};

		var allPeers = new List<JavaPeerInfo> { javaInteropPeer, monoAndroidPeer, otherPeer };
		var result = TrimmableTypeMapGenerator.MergeCrossAssemblyAliases (allPeers);

		// Both java/lang/Object peers should be in the Mono.Android group ([Register] wins)
		var monoAndroidGroup = result.Single (g => g.AssemblyName == "Mono.Android");
		Assert.Equal (2, monoAndroidGroup.Peers.Count);
		Assert.Contains (monoAndroidGroup.Peers, p => p.ManagedTypeName == "Java.Lang.Object");
		Assert.Contains (monoAndroidGroup.Peers, p => p.ManagedTypeName == "Java.Interop.JavaObject");

		// Java.Interop should only have the unique peer
		var javaInteropGroup = result.Single (g => g.AssemblyName == "Java.Interop");
		Assert.Single (javaInteropGroup.Peers);
		Assert.Equal ("Java.Interop.SomeHelper", javaInteropGroup.Peers [0].ManagedTypeName);
	}

	[Fact]
	public void MergeCrossAssemblyAliases_NoDuplicates_NothingMoved ()
	{
		var peer1 = new JavaPeerInfo {
			JavaName = "com/example/Foo", CompatJniName = "com/example/Foo",
			ManagedTypeName = "MyApp.Foo", ManagedTypeNamespace = "MyApp", ManagedTypeShortName = "Foo",
			AssemblyName = "MyApp",
		};
		var peer2 = new JavaPeerInfo {
			JavaName = "com/example/Bar", CompatJniName = "com/example/Bar",
			ManagedTypeName = "MyLib.Bar", ManagedTypeNamespace = "MyLib", ManagedTypeShortName = "Bar",
			AssemblyName = "MyLib",
		};

		var result = TrimmableTypeMapGenerator.MergeCrossAssemblyAliases (new List<JavaPeerInfo> { peer1, peer2 });

		Assert.Equal (2, result.Count);
		Assert.Single (result.Single (g => g.AssemblyName == "MyApp").Peers);
		Assert.Single (result.Single (g => g.AssemblyName == "MyLib").Peers);
	}

	[Fact]
	public void MergeCrossAssemblyAliases_SameAssemblyAliases_NotMoved ()
	{
		// Two peers in the same assembly with the same JNI name — within-assembly alias
		// should NOT be moved; ModelBuilder handles it.
		var peer1 = new JavaPeerInfo {
			JavaName = "java/lang/Object", CompatJniName = "java/lang/Object",
			ManagedTypeName = "Java.Lang.Object", ManagedTypeNamespace = "Java.Lang", ManagedTypeShortName = "Object",
			AssemblyName = "Mono.Android",
		};
		var peer2 = new JavaPeerInfo {
			JavaName = "java/lang/Object", CompatJniName = "java/lang/Object",
			ManagedTypeName = "Java.Lang.IDisposable", ManagedTypeNamespace = "Java.Lang", ManagedTypeShortName = "IDisposable",
			AssemblyName = "Mono.Android",
		};

		var result = TrimmableTypeMapGenerator.MergeCrossAssemblyAliases (new List<JavaPeerInfo> { peer1, peer2 });

		Assert.Single (result);
		Assert.Equal (2, result [0].Peers.Count);
	}

	[Fact]
	public void MergeCrossAssemblyAliases_SameManagedName_DifferentAssemblies_MergedCorrectly ()
	{
		// Reproduces the java/lang/Throwable crash: two assemblies define Java.Lang.Throwable
		// with the same JNI name, plus Java.Interop.JavaException also maps to the same JNI name.
		// All three should be merged into the [Register]-owning assembly's group.
		var javaInteropThrowable = new JavaPeerInfo {
			JavaName = "java/lang/Throwable", CompatJniName = "java/lang/Throwable",
			ManagedTypeName = "Java.Lang.Throwable", ManagedTypeNamespace = "Java.Lang", ManagedTypeShortName = "Throwable",
			AssemblyName = "Java.Interop", IsFromJniTypeSignature = true, DoNotGenerateAcw = true,
		};

		var monoAndroidThrowable = new JavaPeerInfo {
			JavaName = "java/lang/Throwable", CompatJniName = "java/lang/Throwable",
			ManagedTypeName = "Java.Lang.Throwable", ManagedTypeNamespace = "Java.Lang", ManagedTypeShortName = "Throwable",
			AssemblyName = "Mono.Android", IsFromJniTypeSignature = false, DoNotGenerateAcw = true,
		};

		var javaException = new JavaPeerInfo {
			JavaName = "java/lang/Throwable", CompatJniName = "java/lang/Throwable",
			ManagedTypeName = "Java.Interop.JavaException", ManagedTypeNamespace = "Java.Interop", ManagedTypeShortName = "JavaException",
			AssemblyName = "Java.Interop", IsFromJniTypeSignature = true, DoNotGenerateAcw = true,
		};

		var allPeers = new List<JavaPeerInfo> { javaInteropThrowable, monoAndroidThrowable, javaException };
		var result = TrimmableTypeMapGenerator.MergeCrossAssemblyAliases (allPeers);

		// All java/lang/Throwable peers should be in the Mono.Android group ([Register] wins)
		var monoAndroidGroup = result.Single (g => g.AssemblyName == "Mono.Android");
		Assert.Equal (3, monoAndroidGroup.Peers.Count);
		Assert.Contains (monoAndroidGroup.Peers, p => p.ManagedTypeName == "Java.Lang.Throwable" && p.AssemblyName == "Mono.Android");
		Assert.Contains (monoAndroidGroup.Peers, p => p.ManagedTypeName == "Java.Lang.Throwable" && p.AssemblyName == "Java.Interop");
		Assert.Contains (monoAndroidGroup.Peers, p => p.ManagedTypeName == "Java.Interop.JavaException");

		// Java.Interop group should be empty (all peers moved to Mono.Android)
		Assert.DoesNotContain (result, g => g.AssemblyName == "Java.Interop");
	}

	[Fact]
	public void MergeCrossAssemblyAliases_SameManagedName_ProducesCorrectAliasGroup ()
	{
		// End-to-end: after merging, ModelBuilder must produce a 3-way alias group
		// for java/lang/Throwable with indexed entries and a single base entry,
		// ensuring the runtime dictionary only sees java/lang/Throwable once.
		var javaInteropThrowable = new JavaPeerInfo {
			JavaName = "java/lang/Throwable", CompatJniName = "java/lang/Throwable",
			ManagedTypeName = "Java.Lang.Throwable", ManagedTypeNamespace = "Java.Lang", ManagedTypeShortName = "Throwable",
			AssemblyName = "Java.Interop", IsFromJniTypeSignature = true, DoNotGenerateAcw = true,
		};

		var monoAndroidThrowable = new JavaPeerInfo {
			JavaName = "java/lang/Throwable", CompatJniName = "java/lang/Throwable",
			ManagedTypeName = "Java.Lang.Throwable", ManagedTypeNamespace = "Java.Lang", ManagedTypeShortName = "Throwable",
			AssemblyName = "Mono.Android", IsFromJniTypeSignature = false, DoNotGenerateAcw = true,
		};

		var javaException = new JavaPeerInfo {
			JavaName = "java/lang/Throwable", CompatJniName = "java/lang/Throwable",
			ManagedTypeName = "Java.Interop.JavaException", ManagedTypeNamespace = "Java.Interop", ManagedTypeShortName = "JavaException",
			AssemblyName = "Java.Interop", IsFromJniTypeSignature = true, DoNotGenerateAcw = true,
		};

		var allPeers = new List<JavaPeerInfo> { javaInteropThrowable, monoAndroidThrowable, javaException };
		var merged = TrimmableTypeMapGenerator.MergeCrossAssemblyAliases (allPeers);

		// All peers should be in the Mono.Android group
		Assert.Single (merged);
		var group = merged [0];
		Assert.Equal ("Mono.Android", group.AssemblyName);
		Assert.Equal (3, group.Peers.Count);

		// Build the model — should produce a 3-way alias group
		string typeMapAssemblyName = $"_{group.AssemblyName}.TypeMap";
		var model = ModelBuilder.Build (group.Peers, typeMapAssemblyName + ".dll", typeMapAssemblyName);

		// 3 indexed entries + 1 base entry = 4
		Assert.Equal (4, model.Entries.Count);
		Assert.Equal ("java/lang/Throwable[0]", model.Entries [0].MapKey);
		Assert.Equal ("java/lang/Throwable[1]", model.Entries [1].MapKey);
		Assert.Equal ("java/lang/Throwable[2]", model.Entries [2].MapKey);
		Assert.Equal ("java/lang/Throwable", model.Entries [3].MapKey);

		// Exactly 1 alias holder
		Assert.Single (model.AliasHolders);
		Assert.Equal (3, model.AliasHolders [0].AliasKeys.Count);

		// The base "java/lang/Throwable" entry points to the alias holder, not a type directly
		var baseEntry = model.Entries [3];
		Assert.Contains ("_Aliases", baseEntry.ProxyTypeReference);

		// 3 associations (one per peer → alias holder)
		Assert.Equal (3, model.Associations.Count);

		// The bare "java/lang/Throwable" key appears exactly once — no duplicates
		Assert.Single (model.Entries, e => e.MapKey == "java/lang/Throwable");
	}

	[Fact]
	public void RootManifestReferencedTypes_ResolvesRelativeNames ()
	{
		var peers = new List<JavaPeerInfo> {
			new JavaPeerInfo {
				JavaName = "com/example/MyActivity", CompatJniName = "com.example.MyActivity",
				ManagedTypeName = "MyApp.MyActivity", ManagedTypeNamespace = "MyApp", ManagedTypeShortName = "MyActivity",
				AssemblyName = "MyApp", IsUnconditional = false,
			},
			new JavaPeerInfo {
				JavaName = "com/example/MyService", CompatJniName = "com.example.MyService",
				ManagedTypeName = "MyApp.MyService", ManagedTypeNamespace = "MyApp", ManagedTypeShortName = "MyService",
				AssemblyName = "MyApp", IsUnconditional = false,
			},
		};

		var doc = System.Xml.Linq.XDocument.Parse ("""
			<?xml version="1.0" encoding="utf-8"?>
			<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.example">
			  <application>
			    <activity android:name=".MyActivity" />
			    <service android:name="MyService" />
			  </application>
			</manifest>
			""");

		var generator = CreateGenerator ();
		generator.RootManifestReferencedTypes (peers, doc);

		Assert.True (peers [0].IsUnconditional, "Dot-relative name '.MyActivity' should resolve to com.example.MyActivity.");
		Assert.True (peers [1].IsUnconditional, "Simple name 'MyService' should resolve to com.example.MyService.");
	}

	[Fact]
	public void RootManifestReferencedTypes_MatchesCompatNames ()
	{
		var peers = new List<JavaPeerInfo> {
			new JavaPeerInfo {
				JavaName = "crc64123456789abc/MyActivity", CompatJniName = "my/app/MyActivity",
				ManagedTypeName = "My.App.MyActivity", ManagedTypeNamespace = "My.App", ManagedTypeShortName = "MyActivity",
				AssemblyName = "MyApp", IsUnconditional = false,
			},
		};

		var doc = System.Xml.Linq.XDocument.Parse ("""
			<?xml version="1.0" encoding="utf-8"?>
			<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="my.app">
			  <application>
			    <activity android:name=".MyActivity" />
			  </application>
			</manifest>
			""");

		var generator = CreateGenerator ();
		generator.RootManifestReferencedTypes (peers, doc);

		Assert.True (peers [0].IsUnconditional, "Relative manifest name should match CompatJniName when JavaName uses a CRC64 package.");
	}

	[Fact]
	public void RootManifestReferencedTypes_MatchesNestedTypes ()
	{
		var peers = new List<JavaPeerInfo> {
			new JavaPeerInfo {
				JavaName = "com/example/Outer$Inner", CompatJniName = "com.example.Outer$Inner",
				ManagedTypeName = "MyApp.Outer.Inner", ManagedTypeNamespace = "MyApp", ManagedTypeShortName = "Inner",
				AssemblyName = "MyApp", IsUnconditional = false,
			},
		};

		var doc = System.Xml.Linq.XDocument.Parse ("""
			<?xml version="1.0" encoding="utf-8"?>
			<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.example">
			  <application>
			    <activity android:name="com.example.Outer$Inner" />
			  </application>
			</manifest>
			""");

		var generator = CreateGenerator ();
		generator.RootManifestReferencedTypes (peers, doc);

		Assert.True (peers [0].IsUnconditional, "Nested type 'Outer$Inner' should be matched using '$' separator.");
	}


	static PEReader CreateTestFixturePEReader ()
	{
		var dir = Path.GetDirectoryName (typeof (FixtureTestBase).Assembly.Location)
			?? throw new InvalidOperationException ("Cannot determine test assembly directory");
		return new PEReader (File.OpenRead (Path.Combine (dir, "TestFixtures.dll")));
	}
}
