<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\..\..\Configuration.props" />
  <Import Project="..\..\..\..\build-tools\scripts\NUnitReferences.projitems" />
  <PropertyGroup>
    <TargetFramework>$(DotNetStableTargetFramework)</TargetFramework>
    <OutputPath>$(TestOutputDirectory)Xamarin.ProjectTools.Tests\</OutputPath>
    <IsPackable>false</IsPackable>
    <Nullable>annotations</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Xamarin.ProjectTools\Xamarin.ProjectTools.csproj" />
    <Compile Include="..\Xamarin.Android.Build.Tests\HostProcessFixture.cs" Link="HostProcessFixture.cs" />
    <Compile Include="..\Xamarin.Android.Build.Tests\ProjectToolsProcessTests.cs" Link="ProjectToolsProcessTests.cs" />
  </ItemGroup>
</Project>
