<?xml version="1.0" encoding="UTF-8" ?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <AndroidSdkBuildToolsVersion Condition="'$(AndroidSdkBuildToolsVersion)' == ''">37.0.0</AndroidSdkBuildToolsVersion>
    <AndroidCommandLineToolsVersion Condition=" '$(AndroidCommandLineToolsVersion)' == '' ">22.0</AndroidCommandLineToolsVersion>
    <AndroidSdkPlatformToolsVersion Condition="'$(AndroidSdkPlatformToolsVersion)' == ''">37.0.1</AndroidSdkPlatformToolsVersion>
    <AndroidSdkEmulatorVersion Condition="'$(AndroidSdkEmulatorVersion)' == ''"></AndroidSdkEmulatorVersion>
    <AndroidSdkPlatformVersion Condition="'$(AndroidSdkPlatformVersion)' == ''">android-37.0</AndroidSdkPlatformVersion>
    <AndroidNdkVersion Condition="'$(AndroidNdkVersion)' == ''">27.2.12479018</AndroidNdkVersion>
    <JavaSdkVersion Condition="'$(JavaSdkVersion)' == ''">21.0.8</JavaSdkVersion>
    <AndroidManifestFeedVersion Condition=" '$(AndroidManifestFeedVersion)' == '' ">18.0</AndroidManifestFeedVersion>
  </PropertyGroup>
</Project>
