<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Target Name="_GetJavacVersions"
      DependsOnTargets="AndroidPrepareForBuild">
    <PropertyGroup>
      <JarPath Condition=" '$(JarPath)' == '' ">$(JavaSdkDirectory)\bin\jar</JarPath>
      <JavaCPath Condition=" '$(JavaCPath)' == '' ">$(JavaSdkDirectory)\bin\javac</JavaCPath>
    </PropertyGroup>
  </Target>
  <Target Name="_GetJavaRuntimeJarPath">
    <PropertyGroup>
      <_RuntimeJar_InTree>$([System.IO.Path]::GetFullPath ('$(XAInstallPrefix)'))\xbuild\Xamarin\Android\java_runtime.jar</_RuntimeJar_InTree>
      <_RuntimeJar_System Condition=" '$(_XamarinAndroidMSBuildDirectory)' != '' ">$(_XamarinAndroidMSBuildDirectory)\java_runtime.jar</_RuntimeJar_System>
      <_JavaRuntimeJarPath Condition=" Exists($(_RuntimeJar_InTree)) ">$(_RuntimeJar_InTree)</_JavaRuntimeJarPath>
      <_JavaRuntimeJarPath Condition=" '$(_JavaRuntimeJarPath)' == '' and Exists($(_RuntimeJar_System)) ">$(_RuntimeJar_System)</_JavaRuntimeJarPath>
    </PropertyGroup>
    <Error
        Condition=" '$(_JavaRuntimeJarPath)' == '' "
        Text="Could not determine path to `java_runtime.jar`."
    />
  </Target>
  <Target Name="BuildTestJarFile"
      DependsOnTargets="_GetJavacVersions;_GetJavaRuntimeJarPath"
      Inputs="$(MSBuildAllProjects);@(TestJarEntry);$(_JavaRuntimeJarPath)"
      Outputs="%(TestJarEntry.OutputFile)">
    <ItemGroup>
      <_JavacSource
          Include="@(TestJarEntry)"
      />
    </ItemGroup>
    <PropertyGroup>
      <_Javac>"$(JavaCPath)"</_Javac>
      <_Jar>"$(JarPath)"</_Jar>
      <_Targets>--release $(JavacTargetVersion)</_Targets>
      <_Targets Condition=" '$(JavacTargetVersion)' == '1.8' ">--release 8</_Targets>
      <_DestDir>$(IntermediateOutputPath)__CreateTestJarFile-bin</_DestDir>
      <_CP>-classpath "$(AndroidSdkDirectory)\platforms\android-$(_AndroidApiLevelName)\android.jar$(PathSeparator)$(_JavaRuntimeJarPath)"</_CP>
      <_JavacFilesResponse>$(IntermediateOutputPath)__javac_response.txt</_JavacFilesResponse>
    </PropertyGroup>
    <WriteLinesToFile
        File="$(_JavacFilesResponse)"
        Lines="@(_JavacSource)"
        Overwrite="True"
    />
    <MakeDir Directories="$(_DestDir)" />
    <Exec Command="$(_Javac) $(_Targets) -d &quot;$(_DestDir)&quot; $(_CP) &quot;@$(_JavacFilesResponse)&quot;" />
    <Delete Files="$(_JavacFilesResponse)" />
    <Exec
        Command="$(_Jar) cf &quot;classes.jar&quot; ."
        WorkingDirectory="$(_DestDir)"
    />
    <Copy
        SourceFiles="$(_DestDir)\classes.jar"
        DestinationFiles="%(TestJarEntry.OutputFile)"
    />
    <RemoveDir Directories="$(_DestDir)" />
  </Target>
  <Target Name="CleanTestJarFile">
    <Delete Files="%(TestJarEntry.OutputFile)" />
  </Target>
</Project>
