#!/bin/bash -e
NUNIT_VERSION=3.11.1
MYDIR="$(dirname $0)"
PACKAGES_PATH=

function get_path()
{
	shift
	echo $*
}

if [ -n "${NUGET_PACKAGES}" ]; then
	PACKAGES_PATH="${NUGET_PACKAGES}"
fi

if [ -z "${PACKAGES_PATH}" ]; then
	NUGET_PATH="${MYDIR}/../../.nuget/NuGet.exe"
	if [ -f "${NUGET_PATH}" ]; then
		PACKAGES_PATH="$(get_path $(mono ${NUGET_PATH} locals -list global-packages))"
	fi
fi

if [ -z "${PACKAGES_PATH}" ]; then
	PACKAGES_PATH="$HOME/.nuget/packages/"
fi

exec mono "${PACKAGES_PATH}/nunit.consolerunner/${NUNIT_VERSION}/tools/nunit3-console.exe" "$@"
