<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <UsingTask AssemblyFile="$(BootstrapTasksAssembly)" TaskName="Xamarin.Android.Tools.BootstrapTasks.Adb" TaskFactory="TaskHostFactory" Runtime="NET" />
  <UsingTask AssemblyFile="$(BootstrapTasksAssembly)" TaskName="Xamarin.Android.Tools.BootstrapTasks.CheckAdbTarget" TaskFactory="TaskHostFactory" Runtime="NET" />
  <UsingTask AssemblyFile="$(BootstrapTasksAssembly)" TaskName="Xamarin.Android.Tools.BootstrapTasks.CreateAndroidEmulator" TaskFactory="TaskHostFactory" Runtime="NET" />
  <UsingTask AssemblyFile="$(BootstrapTasksAssembly)" TaskName="Xamarin.Android.Tools.BootstrapTasks.RunAndroidEmulatorCheckBootTimes" TaskFactory="TaskHostFactory" Runtime="NET" />
  <UsingTask AssemblyFile="$(BootstrapTasksAssembly)" TaskName="Xamarin.Android.Tools.BootstrapTasks.StartAndroidEmulator" TaskFactory="TaskHostFactory" Runtime="NET" />
  <UsingTask AssemblyFile="$(BootstrapTasksAssembly)" TaskName="Xamarin.Android.Tools.BootstrapTasks.KillProcess" TaskFactory="TaskHostFactory" Runtime="NET" />
  <UsingTask AssemblyFile="$(BootstrapTasksAssembly)" TaskName="Xamarin.Android.Tools.BootstrapTasks.WaitForAndroidEmulator" TaskFactory="TaskHostFactory" Runtime="NET" />
  <UsingTask AssemblyFile="$(PrepTasksAssembly)" TaskName="Xamarin.Android.BuildTools.PrepTasks.XASleepInternal" TaskFactory="TaskHostFactory" Runtime="NET" />

  <PropertyGroup>
    <!-- APK tests might run on 32-bit emulators -->
    <RuntimeIdentifiers Condition=" '$(RuntimeIdentifier)' == '' and '$(PublishAot)' != 'true' and '$(UseMonoRuntime)' == 'true' ">android-arm64;android-x86;android-x64;</RuntimeIdentifiers>
    <TestAvdApiLevel Condition=" '$(TestAvdApiLevel)' == '' ">29</TestAvdApiLevel>
    <TestAvdAbi Condition=" '$(TestAvdAbi)' == '' and '$(HostOS)' == 'Darwin' and  '$(HostOSArchitecture)' == 'Arm64' ">arm64-v8a</TestAvdAbi>
    <TestAvdAbi Condition=" '$(TestAvdAbi)' == '' ">x86_64</TestAvdAbi>
    <TestAvdType Condition=" '$(TestAvdType)' == '' ">default</TestAvdType>
    <TestAvdForceCreation Condition=" '$(TestAvdForceCreation)' == '' ">true</TestAvdForceCreation>
    <TestAvdShowWindow Condition=" '$(TestAvdShowWindow)' == '' and '$(RunningOnCI)' == 'true' ">false</TestAvdShowWindow>
    <TestAvdExtraBootArgs Condition=" '$(TestAvdShowWindow)' == 'false' ">-no-window -no-boot-anim -gpu swiftshader $(TestAvdExtraBootArgs)</TestAvdExtraBootArgs>
    <SdkManagerImageName Condition=" '$(SdkManagerImageName)' == '' ">system-images;android-$(TestAvdApiLevel);$(TestAvdType);$(TestAvdAbi)</SdkManagerImageName>
    <TestAvdName>XamarinAndroidTestRunner$(TestAvdApiLevel)-$(TestAvdAbi)</TestAvdName>
    <_AdbEmulatorPort>5570</_AdbEmulatorPort>
    <AvdLaunchTimeoutMinutes Condition=" '$(AvdLaunchTimeoutMinutes)' == '' ">10</AvdLaunchTimeoutMinutes>
    <AvdLaunchTimeoutSeconds>$([MSBuild]::Multiply($(AvdLaunchTimeoutMinutes), 60))</AvdLaunchTimeoutSeconds>
    <AvdLaunchTimeoutMS>$([MSBuild]::Multiply($(AvdLaunchTimeoutSeconds), 1000))</AvdLaunchTimeoutMS>
    <_LogcatFilenameBase>$(MSBuildThisFileDirectory)..\..\bin\Test$(Configuration)\logcat-$(Configuration)$(TestsFlavor)</_LogcatFilenameBase>
  </PropertyGroup>

  <Target Name="AcquireAndroidTarget">
    <Xamarin.Android.Tools.BootstrapTasks.CheckAdbTarget
        Condition=" '$(RequireNewEmulator)' != 'True' "
        AdbTarget="$(AdbTarget)"
        ToolExe="$(AdbToolExe)"
        ToolPath="$(AdbToolPath)"
        Timeout="60000">
      <Output TaskParameter="DetectedAdbTarget"     PropertyName="_AdbTarget" />
      <Output TaskParameter="IsValidTarget" PropertyName="_ValidAdbTarget"  />
    </Xamarin.Android.Tools.BootstrapTasks.CheckAdbTarget>
    <CreateAndroidEmulator
        Condition=" '$(_ValidAdbTarget)' != 'True' and ( '$(TestAvdForceCreation)' == 'true' or !Exists('$(AvdManagerHome)\.android\avd\$(TestAvdName).avd') ) "
        AndroidAbi="$(TestAvdAbi)"
        AvdManagerHome="$(AvdManagerHome)"
        JavaSdkHome="$(JavaSdkDirectory)"
        SdkVersion="$(TestAvdApiLevel)"
        TargetId="$(SdkManagerImageName)"
        ImageName="$(TestAvdName)"
        ImageType="$(TestAvdType)"
        DeviceName="$(TestDeviceName)"
        ToolExe="$(AvdManagerToolExe)"
        ToolPath="$(CommandLineToolsBinPath)"
        RamSizeMB="3072"
        DataPartitionSizeMB="4096"
    />
    <StartAndroidEmulator
        Condition=" '$(_ValidAdbTarget)' != 'True' "
        AndroidSdkDirectory="$(AndroidSdkDirectory)"
        AvdManagerHome="$(AvdManagerHome)"
        Arguments="$(TestAvdExtraBootArgs)"
        ImageName="$(TestAvdName)"
        LogcatFile="$(_LogcatFilenameBase)-start-emu.txt"
        Port="$(_AdbEmulatorPort)"
        ToolExe="$(EmulatorToolExe)"
        ToolPath="$(EmulatorToolPath)">
      <Output TaskParameter="AdbTarget" PropertyName="_AdbTarget" />
      <Output TaskParameter="AdbTarget" PropertyName="_EmuTarget" />
      <Output TaskParameter="EmulatorProcessId" PropertyName="_EmuPid" />
    </StartAndroidEmulator>
    <Xamarin.Android.Tools.BootstrapTasks.Adb
        EnvironmentVariables="ADB_TRACE=all"
        Condition=" '$(_ValidAdbTarget)' != 'True' "
        Arguments="$(_AdbTarget) wait-for-device"
        ToolExe="$(AdbToolExe)"
        ToolPath="$(AdbToolPath)"
        Timeout="$(AvdLaunchTimeoutMS)"
        WriteOutputAsMessage="True"
    />
    <WaitForAndroidEmulator
        EnvironmentVariables="ADB_TRACE=all"
        Condition=" '$(_ValidAdbTarget)' != 'True' "
        AdbTarget="$(_EmuTarget)"
        ToolExe="$(AdbToolExe)"
        ToolPath="$(AdbToolPath)"
        Timeout="$(AvdLaunchTimeoutMS)"
        WriteOutputAsMessage="True"
    />
    <Xamarin.Android.Tools.BootstrapTasks.Adb
        Arguments="$(_AdbTarget) shell setprop debug.mono.log default,assembly,timing=bare"
        IgnoreExitCode="True"
        ToolExe="$(AdbToolExe)"
        ToolPath="$(AdbToolPath)"
        Timeout="60000"
    />
    <Xamarin.Android.Tools.BootstrapTasks.Adb
        Arguments="$(_AdbTarget) logcat -G 256M"
        IgnoreExitCode="True"
        ToolExe="$(AdbToolExe)"
        ToolPath="$(AdbToolPath)"
        Timeout="60000"
    />
    <Xamarin.Android.Tools.BootstrapTasks.Adb
        Arguments="$(_AdbTarget) logcat -c"
        IgnoreExitCode="True"
        ToolExe="$(AdbToolExe)"
        ToolPath="$(AdbToolPath)"
        Timeout="60000"
    />
    <Message
        Condition=" '$(_EmuTarget)' != '' "
        Text="Launched Android emulator; `adb` target: '$(_AdbTarget)'"
    />
  </Target>

  <Target Name="ReleaseAndroidTarget">
    <PropertyGroup>
      <_EmuTarget Condition=" '$(_EmuTarget)' == '' ">-s emulator-$(_AdbEmulatorPort)</_EmuTarget>
    </PropertyGroup>
    <Xamarin.Android.Tools.BootstrapTasks.Adb
        Condition=" '$(_EmuTarget)' != '' "
        ContinueOnError="ErrorAndContinue"
        Arguments="$(_EmuTarget) emu kill"
        ToolExe="$(AdbToolExe)"
        ToolPath="$(AdbToolPath)"
        Timeout="60000"
    />
    <KillProcess
        Condition=" '$(_EmuPid)' != '' "
        ContinueOnError="ErrorAndContinue"
        ProcessId="$(_EmuPid)"
    />
    <Xamarin.Android.Tools.BootstrapTasks.Adb
        Arguments="kill-server"
        ContinueOnError="ErrorAndContinue"
        ToolExe="$(AdbToolExe)"
        ToolPath="$(AdbToolPath)"
        Timeout="60000"
    />
    <Exec
        Condition=" '$(HostOS)' != 'Windows' And '$(_EmuTarget)' != '' "
        ContinueOnError="WarnAndContinue"
        Command="kill -HUP $(_EmuPid)"
    />
    <XASleepInternal
        Condition=" '$(HostOS)' != 'Windows' And '$(_EmuTarget)' != '' "
        Milliseconds="5000"
    />
    <Exec
        Condition=" '$(HostOS)' != 'Windows' And '$(_EmuTarget)' != '' "
        ContinueOnError="WarnAndContinue"
        IgnoreStandardErrorWarningFormat="true"
        Command="kill -KILL $(_EmuPid)"
    />
  </Target>

  <Target Name="CheckBootTimes"
      DependsOnTargets="AcquireAndroidTarget;ReleaseAndroidTarget">
    <RunAndroidEmulatorCheckBootTimes
        AndroidSdkDirectory="$(AndroidSdkDirectory)"
        AvdManagerHome="$(AvdManagerHome)"
        DeviceName="$(TestAvdName)"
        CheckBootTimesPath="$(MSBuildThisFileDirectory)..\..\bin\Build$(Configuration)\check-boot-times.exe"
    />
  </Target>

  <Target Name="InstallAvdImage" >
    <!-- SDK component installation can be frail, try a few times. -->
    <Exec
        Command="&quot;$(CommandLineToolsBinPath)\sdkmanager&quot; &quot;$(SdkManagerImageName)&quot;"
        EnvironmentVariables="JAVA_HOME=$(JavaSdkDirectory)"
        ContinueOnError="true">
      <Output TaskParameter="ExitCode" PropertyName="_SdkManagerExitCode" />
    </Exec>
    <XASleepInternal
        Milliseconds="5000"
        Condition=" '$(_SdkManagerExitCode)' != '0' "
    />
    <Exec
        Command="&quot;$(CommandLineToolsBinPath)\sdkmanager&quot; &quot;$(SdkManagerImageName)&quot;"
        EnvironmentVariables="JAVA_HOME=$(JavaSdkDirectory)"
        ContinueOnError="true"
        Condition=" '$(_SdkManagerExitCode)' != '0' ">
      <Output TaskParameter="ExitCode" PropertyName="_SdkManagerExitCode" />
    </Exec>
    <XASleepInternal
        Milliseconds="10000"
        Condition=" '$(_SdkManagerExitCode)' != '0' "
    />
    <Exec
        Command="&quot;$(CommandLineToolsBinPath)\sdkmanager&quot; &quot;$(SdkManagerImageName)&quot;"
        EnvironmentVariables="JAVA_HOME=$(JavaSdkDirectory)"
        ContinueOnError="true"
        Condition=" '$(_SdkManagerExitCode)' != '0' ">
      <Output TaskParameter="ExitCode" PropertyName="_SdkManagerExitCode" />
    </Exec>
    <Error
        Text="Attempt to install $(AvdImageName) failed after three attempts."
        Condition=" '$(_SdkManagerExitCode)' != '0' "
    />
  </Target>

</Project>
