<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(DotNetAndroidTargetFramework)</TargetFramework>
    <SupportedOSPlatformVersion>24</SupportedOSPlatformVersion>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationId>net.dot.hybridruntime</ApplicationId>
    <ApplicationVersion>1</ApplicationVersion>
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
    <AndroidPackageFormat>apk</AndroidPackageFormat>
    <RuntimeIdentifier>android-arm64</RuntimeIdentifier>
    <PublishAot>true</PublishAot>
  </PropertyGroup>

  <ItemGroup>
    <AndroidJavaSource Include="java/**/*.java" />
    <ProguardConfiguration Include="proguard.cfg" />
  </ItemGroup>

  <Target Name="_AndroidReplaceCoreClrProcessRuntimeProvider"
      AfterTargets="_GenerateTrimmableTypeMap"
      Condition=" '$(_AndroidRuntime)' == 'NativeAOT' and Exists('$(_TypeMapBaseOutputDir)AndroidManifest.xml') "
      Inputs="$(_TypeMapBaseOutputDir)AndroidManifest.xml"
      Outputs="$(IntermediateOutputPath)replace-coreclr-runtime-provider.stamp">
    <XmlPoke
        XmlInputPath="$(_TypeMapBaseOutputDir)AndroidManifest.xml"
        Query="/*[local-name()='manifest']/*[local-name()='application']/*[local-name()='provider' and @*[local-name()='process']=':coreclr' and starts-with(@*[local-name()='name'], 'net.dot.jni.nativeaot.NativeAotRuntimeProvider')]/@*[local-name()='name']"
        Value="net.dot.hybrid.NoOpRuntimeProvider" />
    <Touch Files="$(IntermediateOutputPath)replace-coreclr-runtime-provider.stamp" AlwaysCreate="true" />
    <ItemGroup>
      <FileWrites Include="$(IntermediateOutputPath)replace-coreclr-runtime-provider.stamp" />
    </ItemGroup>
  </Target>
</Project>
