//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xamarin.Android.Tasks.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xamarin.Android.Tasks.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file name: It must contain only {0}..
        /// </summary>
        internal static string APT0002 {
            get {
                return ResourceManager.GetString("APT0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file name: It must contain only {0}..
        /// </summary>
        internal static string APT0003 {
            get {
                return ResourceManager.GetString("APT0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmbeddedNativeLibrary &apos;{0}&apos; is invalid in Android Application projects. Please use AndroidNativeLibrary instead..
        /// </summary>
        internal static string XA0100 {
            get {
                return ResourceManager.GetString("XA0100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is a Reference Assembly..
        /// </summary>
        internal static string XA0107 {
            get {
                return ResourceManager.GetString("XA0107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignoring Reference Assembly `{0}`..
        /// </summary>
        internal static string XA0107_Ignoring {
            get {
                return ResourceManager.GetString("XA0107_Ignoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AndroidResgen: Warning while updating resource XML &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string XA1001 {
            get {
                return ResourceManager.GetString("XA1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The closest match found for &apos;{0}&apos; is &apos;{1}&apos;, but the capitalization does not match. Please correct the capitalization..
        /// </summary>
        internal static string XA1002 {
            get {
                return ResourceManager.GetString("XA1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting naive type name fixup for element with ID &apos;{0}&apos; and type &apos;{1}&apos;.
        /// </summary>
        internal static string XA1005 {
            get {
                return ResourceManager.GetString("XA1005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the above fixup fails, please add a `xamarin:managedType` attribute to the element to specify the fully qualified managed type name of the element..
        /// </summary>
        internal static string XA1005_Instructions {
            get {
                return ResourceManager.GetString("XA1005_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The TargetFrameworkVersion (Android API level {0}) is higher than the targetSdkVersion ({1}). Please increase the `android:targetSdkVersion` in the `AndroidManifest.xml` so that the API levels match..
        /// </summary>
        internal static string XA1006 {
            get {
                return ResourceManager.GetString("XA1006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minSdkVersion ({0}) is greater than the targetSdkVersion. Please change the value such that the minSdkVersion is less than or equal to the targetSdkVersion ({1})..
        /// </summary>
        internal static string XA1007 {
            get {
                return ResourceManager.GetString("XA1007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The TargetFrameworkVersion (Android API level {0}) is lower than the targetSdkVersion ({1}). Please increase the `$(TargetFrameworkVersion)` or decrease the `android:targetSdkVersion` in the `AndroidManifest.xml` so that the API levels match..
        /// </summary>
        internal static string XA1008 {
            get {
                return ResourceManager.GetString("XA1008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source file &apos;{0}&apos; could not be found..
        /// </summary>
        internal static string XA2001 {
            get {
                return ResourceManager.GetString("XA2001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not AOT the assembly: {0}.
        /// </summary>
        internal static string XA3001 {
            get {
                return ResourceManager.GetString("XA3001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid AOT mode: {0}.
        /// </summary>
        internal static string XA3002 {
            get {
                return ResourceManager.GetString("XA3002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not strip IL of assembly: {0}.
        /// </summary>
        internal static string XA3003 {
            get {
                return ResourceManager.GetString("XA3003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not compile native assembly file: {0}.
        /// </summary>
        internal static string XA3004 {
            get {
                return ResourceManager.GetString("XA3004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not link native shared library: {0}.
        /// </summary>
        internal static string XA3005 {
            get {
                return ResourceManager.GetString("XA3005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to generate Java type for class: {0} due to {1}.
        /// </summary>
        internal static string XA4209 {
            get {
                return ResourceManager.GetString("XA4209", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add a reference to Mono.Android.Export.dll when using ExportAttribute or ExportFieldAttribute..
        /// </summary>
        internal static string XA4210 {
            get {
                return ResourceManager.GetString("XA4210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The managed type `{0}` exists in multiple assemblies: {1}. Please refactor the managed type names in these assemblies so that they are not identical..
        /// </summary>
        internal static string XA4214 {
            get {
                return ResourceManager.GetString("XA4214", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to References to the type `{0}` will refer to `{0}, {1}`..
        /// </summary>
        internal static string XA4214_Result {
            get {
                return ResourceManager.GetString("XA4214_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APK already contains the item {0}; ignoring..
        /// </summary>
        internal static string XA4301 {
            get {
                return ResourceManager.GetString("XA4301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot determine ABI of native library {0}..
        /// </summary>
        internal static string XA4301_ABI {
            get {
                return ResourceManager.GetString("XA4301_ABI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not determine ABI of some native libraries. Ignoring those: {0}.
        /// </summary>
        internal static string XA4301_ABI_Ignoring {
            get {
                return ResourceManager.GetString("XA4301_ABI_Ignoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MultiDex is enabled, but &apos;{0}&apos; was not specified..
        /// </summary>
        internal static string XA4305 {
            get {
                return ResourceManager.GetString("XA4305", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MultiDex is enabled, but main dex list file &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string XA4305_File_Missing {
            get {
                return ResourceManager.GetString("XA4305_File_Missing", resourceCulture);
            }
        }
        
        ///   Looks up a localized string similar to Failed to generate type maps.
        /// </summary>
        internal static string XA4308 {
            get {
                return ResourceManager.GetString("XA4308", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Android NDK toolchains directory &apos;{0}&apos;. Please install the Android NDK..
        /// </summary>
        internal static string XA5101 {
            get {
                return ResourceManager.GetString("XA5101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C compiler for target {0} was not found. Tried paths: &quot;{1}&quot;.
        /// </summary>
        internal static string XA5101_C_Compiler {
            get {
                return ResourceManager.GetString("XA5101_C_Compiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolchain directory for target {0} was not found..
        /// </summary>
        internal static string XA5101_Toolchain {
            get {
                return ResourceManager.GetString("XA5101_Toolchain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not locate the Android NDK. Please make sure the Android NDK is installed in the Android SDK Manager, or if using a custom NDK path, please ensure the $(AndroidNdkDirectory) MSBuild property is set to the custom path..
        /// </summary>
        internal static string XA5102 {
            get {
                return ResourceManager.GetString("XA5102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolchain utility &apos;{0}&apos; for target {1} was not found. Tried in path: &quot;{2}&quot;.
        /// </summary>
        internal static string XA5103 {
            get {
                return ResourceManager.GetString("XA5103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to generate Java type for class: {0} due to MAX_PATH: {1}.
        /// </summary>
        internal static string XA5301 {
            get {
                return ResourceManager.GetString("XA5301", resourceCulture);
            }
        }
    }
}
