//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xamarin.Android.Tasks.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xamarin.Android.Tasks.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file name: It must contain only {0}..
        /// </summary>
        internal static string APT0002 {
            get {
                return ResourceManager.GetString("APT0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file name: It must contain only {0}..
        /// </summary>
        internal static string APT0003 {
            get {
                return ResourceManager.GetString("APT0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not determine API level for $(TargetFrameworkVersion) of &apos;{0}&apos;..
        /// </summary>
        internal static string XA0000_API_for_TargetFrameworkVersion {
            get {
                return ResourceManager.GetString("XA0000_API_for_TargetFrameworkVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not determine $(AndroidApiLevel) or $(TargetFrameworkVersion); should not be reached..
        /// </summary>
        internal static string XA0000_API_or_TargetFrameworkVersion_Fail {
            get {
                return ResourceManager.GetString("XA0000_API_or_TargetFrameworkVersion_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception: {0}.
        /// </summary>
        internal static string XA0000_Exception {
            get {
                return ResourceManager.GetString("XA0000_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not determine $(TargetFrameworkVersion) for API level &apos;{0}.&apos;.
        /// </summary>
        internal static string XA0000_TargetFrameworkVersion_for_API {
            get {
                return ResourceManager.GetString("XA0000_TargetFrameworkVersion_for_API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported or invalid $(TargetFrameworkVersion) value of &apos;{0}&apos;. Please update your Project Options..
        /// </summary>
        internal static string XA0001 {
            get {
                return ResourceManager.GetString("XA0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmbeddedNativeLibrary &apos;{0}&apos; is invalid in Android Application projects. Please use AndroidNativeLibrary instead..
        /// </summary>
        internal static string XA0100 {
            get {
                return ResourceManager.GetString("XA0100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value for `$(AndroidSequencePointsMode)`: {0}.
        /// </summary>
        internal static string XA0104 {
            get {
                return ResourceManager.GetString("XA0104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is a Reference Assembly..
        /// </summary>
        internal static string XA0107 {
            get {
                return ResourceManager.GetString("XA0107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignoring Reference Assembly `{0}`..
        /// </summary>
        internal static string XA0107_Ignoring {
            get {
                return ResourceManager.GetString("XA0107_Ignoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get version from &apos;{0}&apos;. Defaulting to 1.0.
        /// </summary>
        internal static string XA0108 {
            get {
                return ResourceManager.GetString("XA0108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get the `aapt2` version. Disabling `aapt2` support. Please check it is installed correctly..
        /// </summary>
        internal static string XA0111 {
            get {
                return ResourceManager.GetString("XA0111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to `aapt2` is not installed. Disabling `aapt2` support. Please check it is installed correctly..
        /// </summary>
        internal static string XA0112 {
            get {
                return ResourceManager.GetString("XA0112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Play requires that new applications and updates must use a TargetFrameworkVersion of v8.0 (API level 26) or above. You are currently targeting {0} (API level {1})..
        /// </summary>
        internal static string XA0113 {
            get {
                return ResourceManager.GetString("XA0113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find `EmbeddedResource` named `{0}`..
        /// </summary>
        internal static string XA0116 {
            get {
                return ResourceManager.GetString("XA0116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The TargetFrameworkVersion {0} is deprecated. Please update it to be v4.4 or higher..
        /// </summary>
        internal static string XA0117 {
            get {
                return ResourceManager.GetString("XA0117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly &apos;{0}&apos; is using &apos;[assembly: {1}]&apos;, which is no longer supported. Use a newer version of this NuGet package or notify the library author..
        /// </summary>
        internal static string XA0121 {
            get {
                return ResourceManager.GetString("XA0121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly &apos;{0}&apos; is using a deprecated attribute &apos;[assembly: {1}]&apos;. Use a newer version of this NuGet package or notify the library author..
        /// </summary>
        internal static string XA0122 {
            get {
                return ResourceManager.GetString("XA0122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AndroidResgen: Warning while updating resource XML &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string XA1001 {
            get {
                return ResourceManager.GetString("XA1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The closest match found for &apos;{0}&apos; is &apos;{1}&apos;, but the capitalization does not match. Please correct the capitalization..
        /// </summary>
        internal static string XA1002 {
            get {
                return ResourceManager.GetString("XA1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting basic type name matching for element with ID &apos;{0}&apos; and type &apos;{1}&apos;.
        /// </summary>
        internal static string XA1005 {
            get {
                return ResourceManager.GetString("XA1005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If basic type name matching fails, please add a `xamarin:managedType` attribute to the element to specify the fully qualified managed type name of the element..
        /// </summary>
        internal static string XA1005_Instructions {
            get {
                return ResourceManager.GetString("XA1005_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The TargetFrameworkVersion (Android API level {0}) is higher than the targetSdkVersion ({1}). Please increase the `android:targetSdkVersion` in the `AndroidManifest.xml` so that the API levels match..
        /// </summary>
        internal static string XA1006 {
            get {
                return ResourceManager.GetString("XA1006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minSdkVersion ({0}) is greater than the targetSdkVersion. Please change the value such that the minSdkVersion is less than or equal to the targetSdkVersion ({1})..
        /// </summary>
        internal static string XA1007 {
            get {
                return ResourceManager.GetString("XA1007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The TargetFrameworkVersion (Android API level {0}) is lower than the targetSdkVersion ({1}). Please increase the `$(TargetFrameworkVersion)` or decrease the `android:targetSdkVersion` in the `AndroidManifest.xml` so that the API levels match..
        /// </summary>
        internal static string XA1008 {
            get {
                return ResourceManager.GetString("XA1008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source file &apos;{0}&apos; could not be found..
        /// </summary>
        internal static string XA2001 {
            get {
                return ResourceManager.GetString("XA2001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve reference to &apos;{0}&apos; (defined in assembly &apos;{1}&apos;) with scope &apos;{2}&apos;. When the scope is different from the defining assembly, it usually means that the type is forwarded..
        /// </summary>
        internal static string XA2006 {
            get {
                return ResourceManager.GetString("XA2006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not AOT the assembly: {0}.
        /// </summary>
        internal static string XA3001 {
            get {
                return ResourceManager.GetString("XA3001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid AOT mode: {0}.
        /// </summary>
        internal static string XA3002 {
            get {
                return ResourceManager.GetString("XA3002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not strip IL of assembly: {0}.
        /// </summary>
        internal static string XA3003 {
            get {
                return ResourceManager.GetString("XA3003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not compile native assembly file: {0}.
        /// </summary>
        internal static string XA3004 {
            get {
                return ResourceManager.GetString("XA3004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not link native shared library: {0}.
        /// </summary>
        internal static string XA3005 {
            get {
                return ResourceManager.GetString("XA3005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to generate Java type for class: {0} due to {1}.
        /// </summary>
        internal static string XA4209 {
            get {
                return ResourceManager.GetString("XA4209", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add a reference to Mono.Android.Export.dll when using ExportAttribute or ExportFieldAttribute..
        /// </summary>
        internal static string XA4210 {
            get {
                return ResourceManager.GetString("XA4210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AndroidManifest.xml //uses-sdk/@android:targetSdkVersion &apos;{0}&apos; is less than $(TargetFrameworkVersion) &apos;{1}&apos;. Using API-{2} for ACW compilation..
        /// </summary>
        internal static string XA4211 {
            get {
                return ResourceManager.GetString("XA4211", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The managed type `{0}` exists in multiple assemblies: {1}. Please refactor the managed type names in these assemblies so that they are not identical..
        /// </summary>
        internal static string XA4214 {
            get {
                return ResourceManager.GetString("XA4214", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to References to the type `{0}` will refer to `{0}, {1}`..
        /// </summary>
        internal static string XA4214_Result {
            get {
                return ResourceManager.GetString("XA4214_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Java type `{0}` is generated by more than one managed type. Please change the [Register] attribute so that the same Java type is not emitted..
        /// </summary>
        internal static string XA4215 {
            get {
                return ResourceManager.GetString("XA4215", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   `{0}` generated by: {1}.
        /// </summary>
        internal static string XA4215_Details {
            get {
                return ResourceManager.GetString("XA4215_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AndroidManifest.xml //uses-sdk/@android:minSdkVersion &apos;{0}&apos; is less than API-{1}, this configuration is not supported..
        /// </summary>
        internal static string XA4216_MinSdkVersion {
            get {
                return ResourceManager.GetString("XA4216_MinSdkVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AndroidManifest.xml //uses-sdk/@android:targetSdkVersion &apos;{0}&apos; is less than API-{1}, this configuration is not supported..
        /// </summary>
        internal static string XA4216_TargetSdkVersion {
            get {
                return ResourceManager.GetString("XA4216_TargetSdkVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find //manifest/application/uses-library at path: {0}.
        /// </summary>
        internal static string XA4218 {
            get {
                return ResourceManager.GetString("XA4218", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Native library &apos;{0}&apos; will not be bundled because it has an unsupported ABI..
        /// </summary>
        internal static string XA4300 {
            get {
                return ResourceManager.GetString("XA4300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APK already contains the item {0}; ignoring..
        /// </summary>
        internal static string XA4301 {
            get {
                return ResourceManager.GetString("XA4301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot determine ABI of native library {0}..
        /// </summary>
        internal static string XA4301_ABI {
            get {
                return ResourceManager.GetString("XA4301_ABI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not determine ABI of some native libraries. Ignoring those: {0}.
        /// </summary>
        internal static string XA4301_ABI_Ignoring {
            get {
                return ResourceManager.GetString("XA4301_ABI_Ignoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProGuard configuration file &apos;{0}&apos; was not found..
        /// </summary>
        internal static string XA4304 {
            get {
                return ResourceManager.GetString("XA4304", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multidex is enabled, but `$(_AndroidMainDexListFile)` is empty..
        /// </summary>
        internal static string XA4305 {
            get {
                return ResourceManager.GetString("XA4305", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multidex is enabled, but the `$(_AndroidMainDexListFile)` file &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string XA4305_File_Missing {
            get {
                return ResourceManager.GetString("XA4305_File_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R8 does not support `@(MultiDexMainDexList)` files when android:minSdkVersion &gt;= 21.
        /// </summary>
        internal static string XA4306 {
            get {
                return ResourceManager.GetString("XA4306", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ProGuard configuration file. {0}.
        /// </summary>
        internal static string XA4307 {
            get {
                return ResourceManager.GetString("XA4307", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to generate type maps.
        /// </summary>
        internal static string XA4308 {
            get {
                return ResourceManager.GetString("XA4308", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;MultiDexMainDexList&apos; file &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string XA4309 {
            get {
                return ResourceManager.GetString("XA4309", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Android NDK toolchains directory &apos;{0}&apos;. Please install the Android NDK..
        /// </summary>
        internal static string XA5101 {
            get {
                return ResourceManager.GetString("XA5101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C compiler for target {0} was not found. Tried paths: &quot;{1}&quot;.
        /// </summary>
        internal static string XA5101_C_Compiler {
            get {
                return ResourceManager.GetString("XA5101_C_Compiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolchain directory for target {0} was not found..
        /// </summary>
        internal static string XA5101_Toolchain {
            get {
                return ResourceManager.GetString("XA5101_Toolchain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion from assembly to native code failed. Exit code {0}.
        /// </summary>
        internal static string XA5102 {
            get {
                return ResourceManager.GetString("XA5102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NDK C compiler exited with an error. Exit code {0}.
        /// </summary>
        internal static string XA5103 {
            get {
                return ResourceManager.GetString("XA5103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not locate the Android NDK. Please make sure the Android NDK is installed in the Android SDK Manager, or if using a custom NDK path, please ensure the $(AndroidNdkDirectory) MSBuild property is set to the custom path..
        /// </summary>
        internal static string XA5104 {
            get {
                return ResourceManager.GetString("XA5104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolchain utility &apos;{0}&apos; for target {1} was not found. Tried in path: &quot;{2}&quot;.
        /// </summary>
        internal static string XA5105 {
            get {
                return ResourceManager.GetString("XA5105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NDK linker exited with an error. Exit code {0}.
        /// </summary>
        internal static string XA5201 {
            get {
                return ResourceManager.GetString("XA5201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find `{0}`. Please install the Android SDK Build-Tools package with the `{1}{2}tools{2}{3}` program..
        /// </summary>
        internal static string XA5205 {
            get {
                return ResourceManager.GetString("XA5205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find `{0}` in the Android SDK. Please set its path via /p:LintToolPath..
        /// </summary>
        internal static string XA5205_Lint {
            get {
                return ResourceManager.GetString("XA5205_Lint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to java.lang.OutOfMemoryError. Consider increasing the value of $(JavaMaximumHeapSize). Java ran out of memory while executing &apos;{0} {1}&apos;.
        /// </summary>
        internal static string XA5213 {
            get {
                return ResourceManager.GetString("XA5213", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Android platforms installed at &apos;{0}&apos;. Please install an SDK Platform with the `{1}{2}tools{2}{3}` program..
        /// </summary>
        internal static string XA5300_Android_Platforms {
            get {
                return ResourceManager.GetString("XA5300_Android_Platforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Android SDK directory could not be found. Please set via /p:AndroidSdkDirectory..
        /// </summary>
        internal static string XA5300_Android_SDK {
            get {
                return ResourceManager.GetString("XA5300_Android_SDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Java SDK directory could not be found. Please set via /p:JavaSdkDirectory..
        /// </summary>
        internal static string XA5300_Java_SDK {
            get {
                return ResourceManager.GetString("XA5300_Java_SDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to generate Java type for class: {0} due to MAX_PATH: {1}.
        /// </summary>
        internal static string XA5301 {
            get {
                return ResourceManager.GetString("XA5301", resourceCulture);
            }
        }
    }
}
