#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Foo.Foo.Resource", IsApplication=true)]

namespace Foo.Foo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Animator
		{
			
			// aapt resource value: 0x7F040002
			public const int slide_in_bottom = 2130968578;
			
			static Animator()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animator()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7F110002
			public const int widths_array = 2131820546;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F100002
			public const int main_text_item_size = 2131755010;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F050002
			public const int ic_menu_preferences = 2131034114;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Font
		{
			
			// aapt resource value: 0x7F060002
			public const int arial = 2131099650;
			
			static Font()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Font()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F070002
			public const int menu_settings = 2131165186;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7F080002
			public const int Options = 2131230722;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F090002
			public const int icon = 2131296258;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Plurals
		{
			
			// aapt resource value: 0x7F030002
			public const int num_locations_reported = 2130903042;
			
			static Plurals()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Plurals()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F020003
			public const int app_name = 2130837507;
			
			// aapt resource value: 0x7F020005
			public const int foo = 2130837509;
			
			// aapt resource value: 0x7F020002
			public const int hello = 2130837506;
			
			// aapt resource value: 0x7F020004
			public const int menu_settings = 2130837508;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Transition
		{
			
			// aapt resource value: 0x7F010002
			public const int transition = 2130771970;
			
			static Transition()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Transition()
			{
			}
		}
	}
}
#pragma warning restore 1591
