//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by 'manifest-attribute-codegen'.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using System;

namespace Android.App;

[Serializable]
[AttributeUsage (AttributeTargets.Assembly | AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
public sealed partial class ApplicationAttribute : Attribute, Java.Interop.IJniNameProviderAttribute {
	public ApplicationAttribute ()
	{
	}

	public bool AllowBackup { get; set; }

	public bool AllowClearUserData { get; set; }

	public bool AllowTaskReparenting { get; set; }

	public Type? BackupAgent { get; set; }

	public bool BackupInForeground { get; set; }

	public string? Banner { get; set; }

	public bool Debuggable { get; set; }

	public string? Description { get; set; }

	public bool DirectBootAware { get; set; }

	public bool Enabled { get; set; }

	public bool ExtractNativeLibs { get; set; }

	public bool FullBackupContent { get; set; }

	public bool FullBackupOnly { get; set; }

	public bool HardwareAccelerated { get; set; }

	public bool HasCode { get; set; }

	public string? Icon { get; set; }

	public bool KillAfterRestore { get; set; }

	public string? Label { get; set; }

	public bool LargeHeap { get; set; }

	public string? Logo { get; set; }

	public Type? ManageSpaceActivity { get; set; }

	public string? Name { get; set; }

	public string? NetworkSecurityConfig { get; set; }

	public string? Permission { get; set; }

	public bool Persistent { get; set; }

	public string? Process { get; set; }

	public string? RequiredAccountType { get; set; }

	public bool ResizeableActivity { get; set; }

	public bool RestoreAnyVersion { get; set; }

	public string? RestrictedAccountType { get; set; }

	public string? RoundIcon { get; set; }

	public bool SupportsRtl { get; set; }

	public string? TaskAffinity { get; set; }

	public string? Theme { get; set; }

	public Android.Content.PM.UiOptions UiOptions { get; set; }

	public bool UsesCleartextTraffic { get; set; }

	public bool VMSafeMode { get; set; }

}
