//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by 'manifest-attribute-codegen'.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using System;

namespace Android.App;

[Serializable]
[AttributeUsage (AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
public sealed partial class LayoutAttribute : Attribute {
	public LayoutAttribute ()
	{
	}

	public string? DefaultHeight { get; set; }

	public string? DefaultWidth { get; set; }

	public string? Gravity { get; set; }

	public string? MinHeight { get; set; }

	public string? MinWidth { get; set; }

}
