//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by 'manifest-attribute-codegen'.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using System;

namespace Android.App;

[Serializable]
[AttributeUsage (AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
public sealed partial class ServiceAttribute : Attribute, Java.Interop.IJniNameProviderAttribute {
	public ServiceAttribute ()
	{
	}

	public bool DirectBootAware { get; set; }

	public bool Enabled { get; set; }

	public bool Exported { get; set; }

	public Android.Content.PM.ForegroundService ForegroundServiceType { get; set; }

	public string? Icon { get; set; }

	public bool IsolatedProcess { get; set; }

	public string? Label { get; set; }

	public string? Name { get; set; }

	public string? Permission { get; set; }

	public string? Process { get; set; }

	public string? RoundIcon { get; set; }

#if XABT_MANIFEST_EXTENSIONS
	static Xamarin.Android.Manifest.ManifestDocumentElement<ServiceAttribute> mapping = new ("service");

	static ServiceAttribute ()
	{
		mapping.Add (
			member: "DirectBootAware",
			attributeName: "directBootAware",
			getter: self => self.DirectBootAware,
			setter: (self, value) => self.DirectBootAware = (bool) value
		);
		mapping.Add (
			member: "Enabled",
			attributeName: "enabled",
			getter: self => self.Enabled,
			setter: (self, value) => self.Enabled = (bool) value
		);
		mapping.Add (
			member: "Exported",
			attributeName: "exported",
			getter: self => self.Exported,
			setter: (self, value) => self.Exported = (bool) value
		);
		mapping.Add (
			member: "ForegroundServiceType",
			attributeName: "foregroundServiceType",
			getter: self => self.ForegroundServiceType,
			setter: (self, value) => self.ForegroundServiceType = (Android.Content.PM.ForegroundService) value
		);
		mapping.Add (
			member: "Icon",
			attributeName: "icon",
			getter: self => self.Icon,
			setter: (self, value) => self.Icon = (string?) value
		);
		mapping.Add (
			member: "IsolatedProcess",
			attributeName: "isolatedProcess",
			getter: self => self.IsolatedProcess,
			setter: (self, value) => self.IsolatedProcess = (bool) value
		);
		mapping.Add (
			member: "Label",
			attributeName: "label",
			getter: self => self.Label,
			setter: (self, value) => self.Label = (string?) value
		);
		mapping.Add (
			member: "Name",
			attributeName: "name",
			getter: self => self.Name,
			setter: (self, value) => self.Name = (string?) value
		);
		mapping.Add (
			member: "Permission",
			attributeName: "permission",
			getter: self => self.Permission,
			setter: (self, value) => self.Permission = (string?) value
		);
		mapping.Add (
			member: "Process",
			attributeName: "process",
			getter: self => self.Process,
			setter: (self, value) => self.Process = (string?) value
		);
		mapping.Add (
			member: "RoundIcon",
			attributeName: "roundIcon",
			getter: self => self.RoundIcon,
			setter: (self, value) => self.RoundIcon = (string?) value
		);

		AddManualMapping ();
	}

	static partial void AddManualMapping ();
#endif // XABT_MANIFEST_EXTENSIONS
}
