namespace Android.Views {

	partial class KeyCharacterMap {

		/// <summary>
		/// Gets the Unicode character generated by the specified key and meta key state combination.
		/// </summary>
		/// <param name="keyCode">The key code.</param>
		/// <param name="metaState">A combination of <see cref="MetaKeyStates"/> values, expressed as an integer.</param>
		/// <returns>The Unicode character (code point) produced by the key, or <c>0</c> if the key does not produce a character.</returns>
		/// <seealso href="https://developer.android.com/reference/android/view/KeyCharacterMap#get(int,%20int)">Android documentation for <c>android.view.KeyCharacterMap.get</c></seealso>
		public int Get (Keycode keyCode, int metaState)
		{
			return Get (keyCode, (MetaKeyStates) metaState);
		}

		/// <summary>
		/// Gets the first character in <paramref name="chars"/> that can be generated by the specified key code.
		/// If there are multiple choices, prefers the one that would be generated with the specified meta key modifier state.
		/// </summary>
		/// <param name="keyCode">The key code.</param>
		/// <param name="chars">The array of characters to match against.</param>
		/// <param name="metaState">A combination of <see cref="MetaKeyStates"/> values, expressed as an integer.</param>
		/// <returns>The matching character, or the null character (<c>'\0'</c>) if no match was found.</returns>
		/// <seealso href="https://developer.android.com/reference/android/view/KeyCharacterMap#getMatch(int,%20char[],%20int)">Android documentation for <c>android.view.KeyCharacterMap.getMatch</c></seealso>
		public char GetMatch (Keycode keyCode, char[] chars, int metaState)
		{
			return GetMatch (keyCode, chars, (MetaKeyStates) metaState);
		}
	}
}