// These are delegates that exist in AndroidX packages but not Mono.Android
using System;

delegate long _JniMarshal_PPB_J (IntPtr jnienv, IntPtr klazz, sbyte p0);
delegate sbyte _JniMarshal_PPBI_B (IntPtr jnienv, IntPtr klazz, sbyte p0, int p1);
delegate void _JniMarshal_PPBI_V (IntPtr jnienv, IntPtr klazz, sbyte p0, int p1);
delegate long _JniMarshal_PPBJ_J (IntPtr jnienv, IntPtr klazz, sbyte p0, long p1);
delegate long _JniMarshal_PPBJJ_J (IntPtr jnienv, IntPtr klazz, sbyte p0, long p1, long p2);
delegate bool _JniMarshal_PPCJ_Z (IntPtr jnienv, IntPtr klazz, char p0, long p1);
delegate void _JniMarshal_PPDD_V (IntPtr jnienv, IntPtr klazz, double p0, double p1);
delegate double _JniMarshal_PPDDD_D (IntPtr jnienv, IntPtr klazz, double p0, double p1, double p2);
delegate void _JniMarshal_PPDF_V (IntPtr jnienv, IntPtr klazz, double p0, float p1);
delegate double _JniMarshal_PPDI_D (IntPtr jnienv, IntPtr klazz, double p0, int p1);
delegate void _JniMarshal_PPDI_V (IntPtr jnienv, IntPtr klazz, double p0, int p1);
delegate IntPtr _JniMarshal_PPDL_L (IntPtr jnienv, IntPtr klazz, double p0, IntPtr p1);
delegate void _JniMarshal_PPDL_V (IntPtr jnienv, IntPtr klazz, double p0, IntPtr p1);
delegate void _JniMarshal_PPDLL_V (IntPtr jnienv, IntPtr klazz, double p0, IntPtr p1, IntPtr p2);
delegate void _JniMarshal_PPFFFFFFFI_V (IntPtr jnienv, IntPtr klazz, float p0, float p1, float p2, float p3, float p4, float p5, float p6, int p7);
delegate IntPtr _JniMarshal_PPFFFLILILILI_L (IntPtr jnienv, IntPtr klazz, float p0, float p1, float p2, IntPtr p3, int p4, IntPtr p5, int p6, IntPtr p7, int p8, IntPtr p9, int p10);
delegate IntPtr _JniMarshal_PPFFFLLLL_L (IntPtr jnienv, IntPtr klazz, float p0, float p1, float p2, IntPtr p3, IntPtr p4, IntPtr p5, IntPtr p6);
delegate void _JniMarshal_PPFFIIL_V (IntPtr jnienv, IntPtr klazz, float p0, float p1, int p2, int p3, IntPtr p4);
delegate void _JniMarshal_PPFFZ_V (IntPtr jnienv, IntPtr klazz, float p0, float p1, bool p2);
delegate float _JniMarshal_PPFI_F (IntPtr jnienv, IntPtr klazz, float p0, int p1);
delegate float _JniMarshal_PPFJLL_F (IntPtr jnienv, IntPtr klazz, float p0, long p1, IntPtr p2, IntPtr p3);
delegate int _JniMarshal_PPFL_I (IntPtr jnienv, IntPtr klazz, float p0, IntPtr p1);
delegate IntPtr _JniMarshal_PPFL_L (IntPtr jnienv, IntPtr klazz, float p0, IntPtr p1);
delegate void _JniMarshal_PPFLI_V (IntPtr jnienv, IntPtr klazz, float p0, IntPtr p1, int p2);
delegate void _JniMarshal_PPFZFF_V (IntPtr jnienv, IntPtr klazz, float p0, bool p1, float p2, float p3);
delegate void _JniMarshal_PPFZI_V (IntPtr jnienv, IntPtr klazz, float p0, bool p1, int p2);
delegate void _JniMarshal_PPIBI_V (IntPtr jnienv, IntPtr klazz, int p0, sbyte p1, int p2);
delegate void _JniMarshal_PPIDD_V (IntPtr jnienv, IntPtr klazz, int p0, double p1, double p2);
delegate void _JniMarshal_PPIFD_V (IntPtr jnienv, IntPtr klazz, int p0, float p1, double p2);
delegate void _JniMarshal_PPIFF_V (IntPtr jnienv, IntPtr klazz, int p0, float p1, float p2);
delegate bool _JniMarshal_PPIFF_Z (IntPtr jnienv, IntPtr klazz, int p0, float p1, float p2);
delegate void _JniMarshal_PPIFFIF_V (IntPtr jnienv, IntPtr klazz, int p0, float p1, float p2, int p3, float p4);
delegate IntPtr _JniMarshal_PPIFFL_L (IntPtr jnienv, IntPtr klazz, int p0, float p1, float p2, IntPtr p3);
delegate int _JniMarshal_PPIFL_I (IntPtr jnienv, IntPtr klazz, int p0, float p1, IntPtr p2);
delegate void _JniMarshal_PPIFZ_V (IntPtr jnienv, IntPtr klazz, int p0, float p1, bool p2);
delegate void _JniMarshal_PPIFZZ_V (IntPtr jnienv, IntPtr klazz, int p0, float p1, bool p2, bool p3);
delegate int _JniMarshal_PPIIFF_I (IntPtr jnienv, IntPtr klazz, int p0, int p1, float p2, float p3);
delegate void _JniMarshal_PPIIFJ_V (IntPtr jnienv, IntPtr klazz, int p0, int p1, float p2, long p3);
delegate void _JniMarshal_PPIIIF_V (IntPtr jnienv, IntPtr klazz, int p0, int p1, int p2, float p3);
delegate float _JniMarshal_PPIIII_F (IntPtr jnienv, IntPtr klazz, int p0, int p1, int p2, int p3);
delegate int _JniMarshal_PPIIIII_I (IntPtr jnienv, IntPtr klazz, int p0, int p1, int p2, int p3, int p4);
delegate bool _JniMarshal_PPIIIII_Z (IntPtr jnienv, IntPtr klazz, int p0, int p1, int p2, int p3, int p4);
delegate int _JniMarshal_PPIIIIIID_I (IntPtr jnienv, IntPtr klazz, int p0, int p1, int p2, int p3, int p4, int p5, double p6);
delegate IntPtr _JniMarshal_PPIIIIIIF_L (IntPtr jnienv, IntPtr klazz, int p0, int p1, int p2, int p3, int p4, int p5, float p6);
delegate void _JniMarshal_PPIIIIIIIF_V (IntPtr jnienv, IntPtr klazz, int p0, int p1, int p2, int p3, int p4, int p5, int p6, float p7);
delegate long _JniMarshal_PPIIIIIIIII_J (IntPtr jnienv, IntPtr klazz, int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8);
delegate void _JniMarshal_PPIIIIIL_V (IntPtr jnienv, IntPtr klazz, int p0, int p1, int p2, int p3, int p4, IntPtr p5);
delegate IntPtr _JniMarshal_PPIIIIJ_L (IntPtr jnienv, IntPtr klazz, int p0, int p1, int p2, int p3, long p4);
delegate bool _JniMarshal_PPIIIILI_Z (IntPtr jnienv, IntPtr klazz, int p0, int p1, int p2, int p3, IntPtr p4, int p5);
delegate void _JniMarshal_PPIIIILIL_V (IntPtr jnienv, IntPtr klazz, int p0, int p1, int p2, int p3, IntPtr p4, int p5, IntPtr p6);
delegate void _JniMarshal_PPIIIILLI_V (IntPtr jnienv, IntPtr klazz, int p0, int p1, int p2, int p3, IntPtr p4, IntPtr p5, int p6);
delegate void _JniMarshal_PPIIIIZZ_V (IntPtr jnienv, IntPtr klazz, int p0, int p1, int p2, int p3, bool p4, bool p5);
delegate void _JniMarshal_PPIIIJI_V (IntPtr jnienv, IntPtr klazz, int p0, int p1, int p2, long p3, int p4);
delegate IntPtr _JniMarshal_PPIIILL_L (IntPtr jnienv, IntPtr klazz, int p0, int p1, int p2, IntPtr p3, IntPtr p4);
delegate void _JniMarshal_PPIILIFFFF_V (IntPtr jnienv, IntPtr klazz, int p0, int p1, IntPtr p2, int p3, float p4, float p5, float p6, float p7);
delegate void _JniMarshal_PPIILIFFFFL_V (IntPtr jnienv, IntPtr klazz, int p0, int p1, IntPtr p2, int p3, float p4, float p5, float p6, float p7, IntPtr p8);
delegate void _JniMarshal_PPIILIL_V (IntPtr jnienv, IntPtr klazz, int p0, int p1, IntPtr p2, int p3, IntPtr p4);
delegate bool _JniMarshal_PPIILLFF_Z (IntPtr jnienv, IntPtr klazz, int p0, int p1, IntPtr p2, IntPtr p3, float p4, float p5);
delegate bool _JniMarshal_PPIILLI_Z (IntPtr jnienv, IntPtr klazz, int p0, int p1, IntPtr p2, IntPtr p3, int p4);
delegate void _JniMarshal_PPIILLLL_V (IntPtr jnienv, IntPtr klazz, int p0, int p1, IntPtr p2, IntPtr p3, IntPtr p4, IntPtr p5);
delegate int _JniMarshal_PPIJ_I (IntPtr jnienv, IntPtr klazz, int p0, long p1);
delegate IntPtr _JniMarshal_PPIJI_L (IntPtr jnienv, IntPtr klazz, int p0, long p1, int p2);
delegate void _JniMarshal_PPIJI_V (IntPtr jnienv, IntPtr klazz, int p0, long p1, int p2);
delegate void _JniMarshal_PPIJIZ_V (IntPtr jnienv, IntPtr klazz, int p0, long p1, int p2, bool p3);
delegate void _JniMarshal_PPIJJ_V (IntPtr jnienv, IntPtr klazz, int p0, long p1, long p2);
delegate void _JniMarshal_PPIJJI_V (IntPtr jnienv, IntPtr klazz, int p0, long p1, long p2, int p3);
delegate void _JniMarshal_PPIJJJ_V (IntPtr jnienv, IntPtr klazz, int p0, long p1, long p2, long p3);
delegate long _JniMarshal_PPIJJL_J (IntPtr jnienv, IntPtr klazz, int p0, long p1, long p2, IntPtr p3);
delegate IntPtr _JniMarshal_PPIJL_L (IntPtr jnienv, IntPtr klazz, int p0, long p1, IntPtr p2);
delegate void _JniMarshal_PPILFIF_V (IntPtr jnienv, IntPtr klazz, int p0, IntPtr p1, float p2, int p3, float p4);
delegate bool _JniMarshal_PPILII_Z (IntPtr jnienv, IntPtr klazz, int p0, IntPtr p1, int p2, int p3);
delegate void _JniMarshal_PPILIII_V (IntPtr jnienv, IntPtr klazz, int p0, IntPtr p1, int p2, int p3, int p4);
delegate void _JniMarshal_PPILIJJJ_V (IntPtr jnienv, IntPtr klazz, int p0, IntPtr p1, int p2, long p3, long p4, long p5);
delegate IntPtr _JniMarshal_PPILIL_L (IntPtr jnienv, IntPtr klazz, int p0, IntPtr p1, int p2, IntPtr p3);
delegate void _JniMarshal_PPILIL_V (IntPtr jnienv, IntPtr klazz, int p0, IntPtr p1, int p2, IntPtr p3);
delegate void _JniMarshal_PPILILJ_V (IntPtr jnienv, IntPtr klazz, int p0, IntPtr p1, int p2, IntPtr p3, long p4);
delegate IntPtr _JniMarshal_PPILJ_L (IntPtr jnienv, IntPtr klazz, int p0, IntPtr p1, long p2);
delegate void _JniMarshal_PPILJI_V (IntPtr jnienv, IntPtr klazz, int p0, IntPtr p1, long p2, int p3);
delegate void _JniMarshal_PPILLF_V (IntPtr jnienv, IntPtr klazz, int p0, IntPtr p1, IntPtr p2, float p3);
delegate void _JniMarshal_PPILLIII_V (IntPtr jnienv, IntPtr klazz, int p0, IntPtr p1, IntPtr p2, int p3, int p4, int p5);
delegate int _JniMarshal_PPILLL_I (IntPtr jnienv, IntPtr klazz, int p0, IntPtr p1, IntPtr p2, IntPtr p3);
delegate void _JniMarshal_PPILLLIJ_V (IntPtr jnienv, IntPtr klazz, int p0, IntPtr p1, IntPtr p2, IntPtr p3, int p4, long p5);
delegate int _JniMarshal_PPILLLILI_I (IntPtr jnienv, IntPtr klazz, int p0, IntPtr p1, IntPtr p2, IntPtr p3, int p4, IntPtr p5, int p6);
delegate void _JniMarshal_PPILLLJ_V (IntPtr jnienv, IntPtr klazz, int p0, IntPtr p1, IntPtr p2, IntPtr p3, long p4);
delegate IntPtr _JniMarshal_PPILLLL_L (IntPtr jnienv, IntPtr klazz, int p0, IntPtr p1, IntPtr p2, IntPtr p3, IntPtr p4);
delegate IntPtr _JniMarshal_PPILLLLLZ_L (IntPtr jnienv, IntPtr klazz, int p0, IntPtr p1, IntPtr p2, IntPtr p3, IntPtr p4, IntPtr p5, bool p6);
delegate void _JniMarshal_PPILLLLZ_V (IntPtr jnienv, IntPtr klazz, int p0, IntPtr p1, IntPtr p2, IntPtr p3, IntPtr p4, bool p5);
delegate int _JniMarshal_PPILLLZ_I (IntPtr jnienv, IntPtr klazz, int p0, IntPtr p1, IntPtr p2, IntPtr p3, bool p4);
delegate void _JniMarshal_PPILLLZ_V (IntPtr jnienv, IntPtr klazz, int p0, IntPtr p1, IntPtr p2, IntPtr p3, bool p4);
delegate IntPtr _JniMarshal_PPILLZ_L (IntPtr jnienv, IntPtr klazz, int p0, IntPtr p1, IntPtr p2, bool p3);
delegate void _JniMarshal_PPILZL_V (IntPtr jnienv, IntPtr klazz, int p0, IntPtr p1, bool p2, IntPtr p3);
delegate IntPtr _JniMarshal_PPILZLLL_L (IntPtr jnienv, IntPtr klazz, int p0, IntPtr p1, bool p2, IntPtr p3, IntPtr p4, IntPtr p5);
delegate void _JniMarshal_PPISI_V (IntPtr jnienv, IntPtr klazz, int p0, short p1, int p2);
delegate void _JniMarshal_PPIZF_V (IntPtr jnienv, IntPtr klazz, int p0, bool p1, float p2);
delegate sbyte _JniMarshal_PPJ_B (IntPtr jnienv, IntPtr klazz, long p0);
delegate char _JniMarshal_PPJ_C (IntPtr jnienv, IntPtr klazz, long p0);
delegate float _JniMarshal_PPJ_F (IntPtr jnienv, IntPtr klazz, long p0);
delegate short _JniMarshal_PPJ_S (IntPtr jnienv, IntPtr klazz, long p0);
delegate void _JniMarshal_PPJB_V (IntPtr jnienv, IntPtr klazz, long p0, sbyte p1);
delegate void _JniMarshal_PPJC_V (IntPtr jnienv, IntPtr klazz, long p0, char p1);
delegate void _JniMarshal_PPJD_V (IntPtr jnienv, IntPtr klazz, long p0, double p1);
delegate void _JniMarshal_PPJF_V (IntPtr jnienv, IntPtr klazz, long p0, float p1);
delegate bool _JniMarshal_PPJF_Z (IntPtr jnienv, IntPtr klazz, long p0, float p1);
delegate bool _JniMarshal_PPJFZJ_Z (IntPtr jnienv, IntPtr klazz, long p0, float p1, bool p2, long p3);
delegate long _JniMarshal_PPJI_J (IntPtr jnienv, IntPtr klazz, long p0, int p1);
delegate void _JniMarshal_PPJIIIL_V (IntPtr jnienv, IntPtr klazz, long p0, int p1, int p2, int p3, IntPtr p4);
delegate IntPtr _JniMarshal_PPJIIL_L (IntPtr jnienv, IntPtr klazz, long p0, int p1, int p2, IntPtr p3);
delegate void _JniMarshal_PPJIL_V (IntPtr jnienv, IntPtr klazz, long p0, int p1, IntPtr p2);
delegate IntPtr _JniMarshal_PPJILLLL_L (IntPtr jnienv, IntPtr klazz, long p0, int p1, IntPtr p2, IntPtr p3, IntPtr p4, IntPtr p5);
delegate float _JniMarshal_PPJJ_F (IntPtr jnienv, IntPtr klazz, long p0, long p1);
delegate bool _JniMarshal_PPJJ_Z (IntPtr jnienv, IntPtr klazz, long p0, long p1);
delegate void _JniMarshal_PPJJF_V (IntPtr jnienv, IntPtr klazz, long p0, long p1, float p2);
delegate bool _JniMarshal_PPJJF_Z (IntPtr jnienv, IntPtr klazz, long p0, long p1, float p2);
delegate void _JniMarshal_PPJJJ_V (IntPtr jnienv, IntPtr klazz, long p0, long p1, long p2);
delegate void _JniMarshal_PPJJJLL_V (IntPtr jnienv, IntPtr klazz, long p0, long p1, long p2, IntPtr p3, IntPtr p4);
delegate IntPtr _JniMarshal_PPJJJZJJJJLLLLL_L (IntPtr jnienv, IntPtr klazz, long p0, long p1, long p2, bool p3, long p4, long p5, long p6, long p7, IntPtr p8, IntPtr p9, IntPtr p10, IntPtr p11, IntPtr p12);
delegate bool _JniMarshal_PPJJJZZ_Z (IntPtr jnienv, IntPtr klazz, long p0, long p1, long p2, bool p3, bool p4);
delegate IntPtr _JniMarshal_PPJJL_L (IntPtr jnienv, IntPtr klazz, long p0, long p1, IntPtr p2);
delegate void _JniMarshal_PPJJLL_V (IntPtr jnienv, IntPtr klazz, long p0, long p1, IntPtr p2, IntPtr p3);
delegate bool _JniMarshal_PPJJZ_Z (IntPtr jnienv, IntPtr klazz, long p0, long p1, bool p2);
delegate IntPtr _JniMarshal_PPJLFFLIZ_L (IntPtr jnienv, IntPtr klazz, long p0, IntPtr p1, float p2, float p3, IntPtr p4, int p5, bool p6);
delegate void _JniMarshal_PPJLII_V (IntPtr jnienv, IntPtr klazz, long p0, IntPtr p1, int p2, int p3);
delegate bool _JniMarshal_PPJLII_Z (IntPtr jnienv, IntPtr klazz, long p0, IntPtr p1, int p2, int p3);
delegate void _JniMarshal_PPJLJ_V (IntPtr jnienv, IntPtr klazz, long p0, IntPtr p1, long p2);
delegate bool _JniMarshal_PPJLL_Z (IntPtr jnienv, IntPtr klazz, long p0, IntPtr p1, IntPtr p2);
delegate int _JniMarshal_PPJLLL_I (IntPtr jnienv, IntPtr klazz, long p0, IntPtr p1, IntPtr p2, IntPtr p3);
delegate void _JniMarshal_PPJLZZL_V (IntPtr jnienv, IntPtr klazz, long p0, IntPtr p1, bool p2, bool p3, IntPtr p4);
delegate void _JniMarshal_PPJS_V (IntPtr jnienv, IntPtr klazz, long p0, short p1);
delegate long _JniMarshal_PPJZ_J (IntPtr jnienv, IntPtr klazz, long p0, bool p1);
delegate IntPtr _JniMarshal_PPJZ_L (IntPtr jnienv, IntPtr klazz, long p0, bool p1);
delegate IntPtr _JniMarshal_PPJZL_L (IntPtr jnienv, IntPtr klazz, long p0, bool p1, IntPtr p2);
delegate IntPtr _JniMarshal_PPJZZL_L (IntPtr jnienv, IntPtr klazz, long p0, bool p1, bool p2, IntPtr p3);
delegate void _JniMarshal_PPLBB_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, sbyte p1, sbyte p2);
delegate void _JniMarshal_PPLBC_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, sbyte p1, char p2);
delegate void _JniMarshal_PPLBD_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, sbyte p1, double p2);
delegate void _JniMarshal_PPLBF_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, sbyte p1, float p2);
delegate void _JniMarshal_PPLBI_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, sbyte p1, int p2);
delegate void _JniMarshal_PPLBJ_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, sbyte p1, long p2);
delegate void _JniMarshal_PPLBS_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, sbyte p1, short p2);
delegate void _JniMarshal_PPLBZ_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, sbyte p1, bool p2);
delegate void _JniMarshal_PPLCB_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, char p1, sbyte p2);
delegate void _JniMarshal_PPLCC_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, char p1, char p2);
delegate void _JniMarshal_PPLCD_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, char p1, double p2);
delegate void _JniMarshal_PPLCF_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, char p1, float p2);
delegate void _JniMarshal_PPLCI_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, char p1, int p2);
delegate void _JniMarshal_PPLCJ_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, char p1, long p2);
delegate void _JniMarshal_PPLCL_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, char p1, IntPtr p2);
delegate void _JniMarshal_PPLCS_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, char p1, short p2);
delegate void _JniMarshal_PPLCZ_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, char p1, bool p2);
delegate bool _JniMarshal_PPLD_Z (IntPtr jnienv, IntPtr klazz, IntPtr p0, double p1);
delegate void _JniMarshal_PPLDB_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, double p1, sbyte p2);
delegate void _JniMarshal_PPLDC_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, double p1, char p2);
delegate void _JniMarshal_PPLDD_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, double p1, double p2);
delegate void _JniMarshal_PPLDF_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, double p1, float p2);
delegate void _JniMarshal_PPLDI_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, double p1, int p2);
delegate void _JniMarshal_PPLDJ_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, double p1, long p2);
delegate IntPtr _JniMarshal_PPLDL_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, double p1, IntPtr p2);
delegate void _JniMarshal_PPLDL_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, double p1, IntPtr p2);
delegate void _JniMarshal_PPLDS_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, double p1, short p2);
delegate void _JniMarshal_PPLDZ_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, double p1, bool p2);
delegate void _JniMarshal_PPLFB_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, float p1, sbyte p2);
delegate void _JniMarshal_PPLFC_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, float p1, char p2);
delegate void _JniMarshal_PPLFD_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, float p1, double p2);
delegate void _JniMarshal_PPLFDD_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, float p1, double p2, double p3);
delegate void _JniMarshal_PPLFFLI_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, float p1, float p2, IntPtr p3, int p4);
delegate void _JniMarshal_PPLFFLL_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, float p1, float p2, IntPtr p3, IntPtr p4);
delegate void _JniMarshal_PPLFI_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, float p1, int p2);
delegate void _JniMarshal_PPLFJ_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, float p1, long p2);
delegate bool _JniMarshal_PPLFJL_Z (IntPtr jnienv, IntPtr klazz, IntPtr p0, float p1, long p2, IntPtr p3);
delegate void _JniMarshal_PPLFL_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, float p1, IntPtr p2);
delegate void _JniMarshal_PPLFLL_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, float p1, IntPtr p2, IntPtr p3);
delegate void _JniMarshal_PPLFLLL_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, float p1, IntPtr p2, IntPtr p3, IntPtr p4);
delegate void _JniMarshal_PPLFS_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, float p1, short p2);
delegate sbyte _JniMarshal_PPLI_B (IntPtr jnienv, IntPtr klazz, IntPtr p0, int p1);
delegate double _JniMarshal_PPLI_D (IntPtr jnienv, IntPtr klazz, IntPtr p0, int p1);
delegate float _JniMarshal_PPLI_F (IntPtr jnienv, IntPtr klazz, IntPtr p0, int p1);
delegate long _JniMarshal_PPLI_J (IntPtr jnienv, IntPtr klazz, IntPtr p0, int p1);
delegate short _JniMarshal_PPLI_S (IntPtr jnienv, IntPtr klazz, IntPtr p0, int p1);
delegate void _JniMarshal_PPLIB_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, int p1, sbyte p2);
delegate void _JniMarshal_PPLIC_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, int p1, char p2);
delegate void _JniMarshal_PPLID_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, int p1, double p2);
delegate void _JniMarshal_PPLIF_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, int p1, float p2);
delegate float _JniMarshal_PPLIFF_F (IntPtr jnienv, IntPtr klazz, IntPtr p0, int p1, float p2, float p3);
delegate long _JniMarshal_PPLIFF_J (IntPtr jnienv, IntPtr klazz, IntPtr p0, int p1, float p2, float p3);
delegate void _JniMarshal_PPLIIF_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, int p1, int p2, float p3);
delegate void _JniMarshal_PPLIIFF_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, int p1, int p2, float p3, float p4);
delegate bool _JniMarshal_PPLIIFF_Z (IntPtr jnienv, IntPtr klazz, IntPtr p0, int p1, int p2, float p3, float p4);
delegate IntPtr _JniMarshal_PPLIIFFFFFFFFFFFFFFFF_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, int p1, int p2, float p3, float p4, float p5, float p6, float p7, float p8, float p9, float p10, float p11, float p12, float p13, float p14, float p15, float p16, float p17, float p18);
delegate bool _JniMarshal_PPLIII_Z (IntPtr jnienv, IntPtr klazz, IntPtr p0, int p1, int p2, int p3);
delegate void _JniMarshal_PPLIIIF_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, int p1, int p2, int p3, float p4);
delegate bool _JniMarshal_PPLIIII_Z (IntPtr jnienv, IntPtr klazz, IntPtr p0, int p1, int p2, int p3, int p4);
delegate void _JniMarshal_PPLIIIII_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, int p1, int p2, int p3, int p4, int p5);
delegate long _JniMarshal_PPLIIIIIIIII_J (IntPtr jnienv, IntPtr klazz, IntPtr p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8, int p9);
delegate void _JniMarshal_PPLIIIIIL_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, int p1, int p2, int p3, int p4, int p5, IntPtr p6);
delegate int _JniMarshal_PPLIIIJ_I (IntPtr jnienv, IntPtr klazz, IntPtr p0, int p1, int p2, int p3, long p4);
delegate int _JniMarshal_PPLIIIZ_I (IntPtr jnienv, IntPtr klazz, IntPtr p0, int p1, int p2, int p3, bool p4);
delegate IntPtr _JniMarshal_PPLIIIZ_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, int p1, int p2, int p3, bool p4);
delegate IntPtr _JniMarshal_PPLIIIZZ_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, int p1, int p2, int p3, bool p4, bool p5);
delegate IntPtr _JniMarshal_PPLIIIZZL_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, int p1, int p2, int p3, bool p4, bool p5, IntPtr p6);
delegate IntPtr _JniMarshal_PPLIIJL_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, int p1, int p2, long p3, IntPtr p4);
delegate bool _JniMarshal_PPLIIL_Z (IntPtr jnienv, IntPtr klazz, IntPtr p0, int p1, int p2, IntPtr p3);
delegate void _JniMarshal_PPLIILI_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, int p1, int p2, IntPtr p3, int p4);
delegate IntPtr _JniMarshal_PPLIILIL_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, int p1, int p2, IntPtr p3, int p4, IntPtr p5);
delegate void _JniMarshal_PPLIILILJJ_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, int p1, int p2, IntPtr p3, int p4, IntPtr p5, long p6, long p7);
delegate void _JniMarshal_PPLIILILJJLZ_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, int p1, int p2, IntPtr p3, int p4, IntPtr p5, long p6, long p7, IntPtr p8, bool p9);
delegate IntPtr _JniMarshal_PPLIILL_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, int p1, int p2, IntPtr p3, IntPtr p4);
delegate void _JniMarshal_PPLIILLL_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, int p1, int p2, IntPtr p3, IntPtr p4, IntPtr p5);
delegate bool _JniMarshal_PPLIIZ_Z (IntPtr jnienv, IntPtr klazz, IntPtr p0, int p1, int p2, bool p3);
delegate bool _JniMarshal_PPLIIZZ_Z (IntPtr jnienv, IntPtr klazz, IntPtr p0, int p1, int p2, bool p3, bool p4);
delegate int _JniMarshal_PPLIJ_I (IntPtr jnienv, IntPtr klazz, IntPtr p0, int p1, long p2);
delegate IntPtr _JniMarshal_PPLIJ_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, int p1, long p2);
delegate void _JniMarshal_PPLIJJ_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, int p1, long p2, long p3);
delegate IntPtr _JniMarshal_PPLIJL_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, int p1, long p2, IntPtr p3);
delegate long _JniMarshal_PPLIL_J (IntPtr jnienv, IntPtr klazz, IntPtr p0, int p1, IntPtr p2);
delegate bool _JniMarshal_PPLILI_Z (IntPtr jnienv, IntPtr klazz, IntPtr p0, int p1, IntPtr p2, int p3);
delegate int _JniMarshal_PPLILIII_I (IntPtr jnienv, IntPtr klazz, IntPtr p0, int p1, IntPtr p2, int p3, int p4, int p5);
delegate void _JniMarshal_PPLILIJ_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, int p1, IntPtr p2, int p3, long p4);
delegate IntPtr _JniMarshal_PPLILIZL_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, int p1, IntPtr p2, int p3, bool p4, IntPtr p5);
delegate void _JniMarshal_PPLILZLLJL_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, int p1, IntPtr p2, bool p3, IntPtr p4, IntPtr p5, long p6, IntPtr p7);
delegate void _JniMarshal_PPLILZLLLL_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, int p1, IntPtr p2, bool p3, IntPtr p4, IntPtr p5, IntPtr p6, IntPtr p7);
delegate void _JniMarshal_PPLIS_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, int p1, short p2);
delegate void _JniMarshal_PPLIZF_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, int p1, bool p2, float p3);
delegate int _JniMarshal_PPLIZI_I (IntPtr jnienv, IntPtr klazz, IntPtr p0, int p1, bool p2, int p3);
delegate void _JniMarshal_PPLIZI_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, int p1, bool p2, int p3);
delegate void _JniMarshal_PPLIZL_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, int p1, bool p2, IntPtr p3);
delegate void _JniMarshal_PPLJB_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, long p1, sbyte p2);
delegate void _JniMarshal_PPLJC_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, long p1, char p2);
delegate void _JniMarshal_PPLJD_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, long p1, double p2);
delegate void _JniMarshal_PPLJF_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, long p1, float p2);
delegate long _JniMarshal_PPLJI_J (IntPtr jnienv, IntPtr klazz, IntPtr p0, long p1, int p2);
delegate IntPtr _JniMarshal_PPLJI_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, long p1, int p2);
delegate void _JniMarshal_PPLJI_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, long p1, int p2);
delegate bool _JniMarshal_PPLJI_Z (IntPtr jnienv, IntPtr klazz, IntPtr p0, long p1, int p2);
delegate long _JniMarshal_PPLJIIII_J (IntPtr jnienv, IntPtr klazz, IntPtr p0, long p1, int p2, int p3, int p4, int p5);
delegate IntPtr _JniMarshal_PPLJIL_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, long p1, int p2, IntPtr p3);
delegate void _JniMarshal_PPLJIL_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, long p1, int p2, IntPtr p3);
delegate void _JniMarshal_PPLJIZ_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, long p1, int p2, bool p3);
delegate IntPtr _JniMarshal_PPLJJJJ_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, long p1, long p2, long p3, long p4);
delegate IntPtr _JniMarshal_PPLJJJJJLJLLJJ_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, long p1, long p2, long p3, long p4, long p5, IntPtr p6, long p7, IntPtr p8, IntPtr p9, long p10, long p11);
delegate IntPtr _JniMarshal_PPLJJJJLJLJJ_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, long p1, long p2, long p3, long p4, IntPtr p5, long p6, IntPtr p7, long p8, long p9);
delegate IntPtr _JniMarshal_PPLJJLI_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, long p1, long p2, IntPtr p3, int p4);
delegate void _JniMarshal_PPLJJZ_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, long p1, long p2, bool p3);
delegate long _JniMarshal_PPLJL_J (IntPtr jnienv, IntPtr klazz, IntPtr p0, long p1, IntPtr p2);
delegate IntPtr _JniMarshal_PPLJLL_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, long p1, IntPtr p2, IntPtr p3);
delegate IntPtr _JniMarshal_PPLJLLL_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, long p1, IntPtr p2, IntPtr p3, IntPtr p4);
delegate void _JniMarshal_PPLJLLLL_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, long p1, IntPtr p2, IntPtr p3, IntPtr p4, IntPtr p5);
delegate void _JniMarshal_PPLJS_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, long p1, short p2);
delegate long _JniMarshal_PPLJZ_J (IntPtr jnienv, IntPtr klazz, IntPtr p0, long p1, bool p2);
delegate void _JniMarshal_PPLJZ_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, long p1, bool p2);
delegate float _JniMarshal_PPLL_F (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1);
delegate void _JniMarshal_PPLLB_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, sbyte p2);
delegate void _JniMarshal_PPLLC_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, char p2);
delegate void _JniMarshal_PPLLD_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, double p2);
delegate IntPtr _JniMarshal_PPLLFFLL_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, float p2, float p3, IntPtr p4, IntPtr p5);
delegate void _JniMarshal_PPLLFI_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, float p2, int p3);
delegate bool _JniMarshal_PPLLFJDD_Z (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, float p2, long p3, double p4, double p5);
delegate float _JniMarshal_PPLLI_F (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, int p2);
delegate void _JniMarshal_PPLLIF_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, int p2, float p3);
delegate void _JniMarshal_PPLLIFLLII_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, int p2, float p3, IntPtr p4, IntPtr p5, int p6, int p7);
delegate IntPtr _JniMarshal_PPLLIIFIIILLLLLL_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, int p2, int p3, float p4, int p5, int p6, int p7, IntPtr p8, IntPtr p9, IntPtr p10, IntPtr p11, IntPtr p12, IntPtr p13);
delegate IntPtr _JniMarshal_PPLLIII_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, int p2, int p3, int p4);
delegate bool _JniMarshal_PPLLIIII_Z (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, int p2, int p3, int p4, int p5);
delegate void _JniMarshal_PPLLIIIILLII_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, int p2, int p3, int p4, int p5, IntPtr p6, IntPtr p7, int p8, int p9);
delegate IntPtr _JniMarshal_PPLLIIIZ_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, int p2, int p3, int p4, bool p5);
delegate IntPtr _JniMarshal_PPLLIIJL_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, int p2, int p3, long p4, IntPtr p5);
delegate bool _JniMarshal_PPLLIIZ_Z (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, int p2, int p3, bool p4);
delegate IntPtr _JniMarshal_PPLLIJL_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, int p2, long p3, IntPtr p4);
delegate void _JniMarshal_PPLLILI_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, int p2, IntPtr p3, int p4);
delegate void _JniMarshal_PPLLILIL_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, int p2, IntPtr p3, int p4, IntPtr p5);
delegate IntPtr _JniMarshal_PPLLILILJIJJL_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, int p2, IntPtr p3, int p4, IntPtr p5, long p6, int p7, long p8, long p9, IntPtr p10);
delegate void _JniMarshal_PPLLILLLIL_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, int p2, IntPtr p3, IntPtr p4, IntPtr p5, int p6, IntPtr p7);
delegate void _JniMarshal_PPLLILLLILJ_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, int p2, IntPtr p3, IntPtr p4, IntPtr p5, int p6, IntPtr p7, long p8);
delegate void _JniMarshal_PPLLIZ_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, int p2, bool p3);
delegate IntPtr _JniMarshal_PPLLJ_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, long p2);
delegate bool _JniMarshal_PPLLJFZJ_Z (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, long p2, float p3, bool p4, long p5);
delegate IntPtr _JniMarshal_PPLLJI_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, long p2, int p3);
delegate IntPtr _JniMarshal_PPLLJJ_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, long p2, long p3);
delegate IntPtr _JniMarshal_PPLLJJJJJ_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, long p2, long p3, long p4, long p5, long p6);
delegate IntPtr _JniMarshal_PPLLJJJJZ_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, long p2, long p3, long p4, long p5, bool p6);
delegate IntPtr _JniMarshal_PPLLJJL_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, long p2, long p3, IntPtr p4);
delegate void _JniMarshal_PPLLJJL_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, long p2, long p3, IntPtr p4);
delegate void _JniMarshal_PPLLJL_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, long p2, IntPtr p3);
delegate bool _JniMarshal_PPLLJL_Z (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, long p2, IntPtr p3);
delegate IntPtr _JniMarshal_PPLLJLJ_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, long p2, IntPtr p3, long p4);
delegate bool _JniMarshal_PPLLLFF_Z (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, float p3, float p4);
delegate void _JniMarshal_PPLLLFFIZ_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, float p3, float p4, int p5, bool p6);
delegate void _JniMarshal_PPLLLFFLL_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, float p3, float p4, IntPtr p5, IntPtr p6);
delegate bool _JniMarshal_PPLLLFFZ_Z (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, float p3, float p4, bool p5);
delegate void _JniMarshal_PPLLLIFF_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, int p3, float p4, float p5);
delegate void _JniMarshal_PPLLLIFFL_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, int p3, float p4, float p5, IntPtr p6);
delegate IntPtr _JniMarshal_PPLLLII_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, int p3, int p4);
delegate void _JniMarshal_PPLLLIIII_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, int p3, int p4, int p5, int p6);
delegate void _JniMarshal_PPLLLIIIII_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, int p3, int p4, int p5, int p6, int p7);
delegate void _JniMarshal_PPLLLIIIIIL_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, int p3, int p4, int p5, int p6, int p7, IntPtr p8);
delegate IntPtr _JniMarshal_PPLLLIIL_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, int p3, int p4, IntPtr p5);
delegate void _JniMarshal_PPLLLIIL_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, int p3, int p4, IntPtr p5);
delegate void _JniMarshal_PPLLLIILI_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, int p3, int p4, IntPtr p5, int p6);
delegate IntPtr _JniMarshal_PPLLLIILLLLLZZLZZZZLL_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, int p3, int p4, IntPtr p5, IntPtr p6, IntPtr p7, IntPtr p8, IntPtr p9, bool p10, bool p11, IntPtr p12, bool p13, bool p14, bool p15, bool p16, IntPtr p17, IntPtr p18);
delegate IntPtr _JniMarshal_PPLLLIJ_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, int p3, long p4);
delegate void _JniMarshal_PPLLLIL_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, int p3, IntPtr p4);
delegate IntPtr _JniMarshal_PPLLLILZZZZIZILIJ_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, int p3, IntPtr p4, bool p5, bool p6, bool p7, bool p8, int p9, bool p10, int p11, IntPtr p12, int p13, long p14);
delegate void _JniMarshal_PPLLLIZ_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, int p3, bool p4);
delegate IntPtr _JniMarshal_PPLLLJ_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, long p3);
delegate IntPtr _JniMarshal_PPLLLJIIZ_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, long p3, int p4, int p5, bool p6);
delegate IntPtr _JniMarshal_PPLLLJJJJJ_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, long p3, long p4, long p5, long p6, long p7);
delegate IntPtr _JniMarshal_PPLLLJJJJJZ_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, long p3, long p4, long p5, long p6, long p7, bool p8);
delegate IntPtr _JniMarshal_PPLLLJJL_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, long p3, long p4, IntPtr p5);
delegate void _JniMarshal_PPLLLJJL_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, long p3, long p4, IntPtr p5);
delegate IntPtr _JniMarshal_PPLLLJL_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, long p3, IntPtr p4);
delegate void _JniMarshal_PPLLLJLL_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, long p3, IntPtr p4, IntPtr p5);
delegate IntPtr _JniMarshal_PPLLLJZ_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, long p3, bool p4);
delegate IntPtr _JniMarshal_PPLLLJZZ_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, long p3, bool p4, bool p5);
delegate void _JniMarshal_PPLLLJZZJJL_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, long p3, bool p4, bool p5, long p6, long p7, IntPtr p8);
delegate IntPtr _JniMarshal_PPLLLLF_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, IntPtr p3, float p4);
delegate void _JniMarshal_PPLLLLFI_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, IntPtr p3, float p4, int p5);
delegate void _JniMarshal_PPLLLLI_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, IntPtr p3, int p4);
delegate void _JniMarshal_PPLLLLII_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, IntPtr p3, int p4, int p5);
delegate bool _JniMarshal_PPLLLLII_Z (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, IntPtr p3, int p4, int p5);
delegate IntPtr _JniMarshal_PPLLLLIIFIILLLLLLJJJJJZ_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, IntPtr p3, int p4, int p5, float p6, int p7, int p8, IntPtr p9, IntPtr p10, IntPtr p11, IntPtr p12, IntPtr p13, IntPtr p14, long p15, long p16, long p17, long p18, long p19, bool p20);
delegate void _JniMarshal_PPLLLLILZJ_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, IntPtr p3, int p4, IntPtr p5, bool p6, long p7);
delegate long _JniMarshal_PPLLLLJ_J (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, IntPtr p3, long p4);
delegate void _JniMarshal_PPLLLLLIL_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, IntPtr p3, IntPtr p4, int p5, IntPtr p6);
delegate IntPtr _JniMarshal_PPLLLLLIZLZIZIJ_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, IntPtr p3, IntPtr p4, int p5, bool p6, IntPtr p7, bool p8, int p9, bool p10, int p11, long p12);
delegate bool _JniMarshal_PPLLLLLL_Z (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, IntPtr p3, IntPtr p4, IntPtr p5);
delegate IntPtr _JniMarshal_PPLLLLLLI_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, IntPtr p3, IntPtr p4, IntPtr p5, int p6);
delegate void _JniMarshal_PPLLLLLLL_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, IntPtr p3, IntPtr p4, IntPtr p5, IntPtr p6);
delegate IntPtr _JniMarshal_PPLLLLLLLJ_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, IntPtr p3, IntPtr p4, IntPtr p5, IntPtr p6, long p7);
delegate void _JniMarshal_PPLLLLLLLL_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, IntPtr p3, IntPtr p4, IntPtr p5, IntPtr p6, IntPtr p7);
delegate void _JniMarshal_PPLLLLLLLLL_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, IntPtr p3, IntPtr p4, IntPtr p5, IntPtr p6, IntPtr p7, IntPtr p8);
delegate void _JniMarshal_PPLLLLLLLLLL_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, IntPtr p3, IntPtr p4, IntPtr p5, IntPtr p6, IntPtr p7, IntPtr p8, IntPtr p9);
delegate IntPtr _JniMarshal_PPLLLLLLLLLLL_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, IntPtr p3, IntPtr p4, IntPtr p5, IntPtr p6, IntPtr p7, IntPtr p8, IntPtr p9, IntPtr p10);
delegate void _JniMarshal_PPLLLLLLLLLLL_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, IntPtr p3, IntPtr p4, IntPtr p5, IntPtr p6, IntPtr p7, IntPtr p8, IntPtr p9, IntPtr p10);
delegate IntPtr _JniMarshal_PPLLLLLLLLLLLL_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, IntPtr p3, IntPtr p4, IntPtr p5, IntPtr p6, IntPtr p7, IntPtr p8, IntPtr p9, IntPtr p10, IntPtr p11);
delegate void _JniMarshal_PPLLLLLLLLLLLL_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, IntPtr p3, IntPtr p4, IntPtr p5, IntPtr p6, IntPtr p7, IntPtr p8, IntPtr p9, IntPtr p10, IntPtr p11);
delegate IntPtr _JniMarshal_PPLLLLLLLLLLLLL_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, IntPtr p3, IntPtr p4, IntPtr p5, IntPtr p6, IntPtr p7, IntPtr p8, IntPtr p9, IntPtr p10, IntPtr p11, IntPtr p12);
delegate IntPtr _JniMarshal_PPLLLLLLLLLLLLLL_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, IntPtr p3, IntPtr p4, IntPtr p5, IntPtr p6, IntPtr p7, IntPtr p8, IntPtr p9, IntPtr p10, IntPtr p11, IntPtr p12, IntPtr p13);
delegate IntPtr _JniMarshal_PPLLLLLLLLLLLLLLL_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, IntPtr p3, IntPtr p4, IntPtr p5, IntPtr p6, IntPtr p7, IntPtr p8, IntPtr p9, IntPtr p10, IntPtr p11, IntPtr p12, IntPtr p13, IntPtr p14);
delegate IntPtr _JniMarshal_PPLLLLLLLLLLLLLLLL_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, IntPtr p3, IntPtr p4, IntPtr p5, IntPtr p6, IntPtr p7, IntPtr p8, IntPtr p9, IntPtr p10, IntPtr p11, IntPtr p12, IntPtr p13, IntPtr p14, IntPtr p15);
delegate IntPtr _JniMarshal_PPLLLLLLLLLLLLLLLLL_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, IntPtr p3, IntPtr p4, IntPtr p5, IntPtr p6, IntPtr p7, IntPtr p8, IntPtr p9, IntPtr p10, IntPtr p11, IntPtr p12, IntPtr p13, IntPtr p14, IntPtr p15, IntPtr p16);
delegate IntPtr _JniMarshal_PPLLLLLLLLLLLLLLLLLL_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, IntPtr p3, IntPtr p4, IntPtr p5, IntPtr p6, IntPtr p7, IntPtr p8, IntPtr p9, IntPtr p10, IntPtr p11, IntPtr p12, IntPtr p13, IntPtr p14, IntPtr p15, IntPtr p16, IntPtr p17);
delegate IntPtr _JniMarshal_PPLLLLLLLLLLLLLLLLLLL_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, IntPtr p3, IntPtr p4, IntPtr p5, IntPtr p6, IntPtr p7, IntPtr p8, IntPtr p9, IntPtr p10, IntPtr p11, IntPtr p12, IntPtr p13, IntPtr p14, IntPtr p15, IntPtr p16, IntPtr p17, IntPtr p18);
delegate IntPtr _JniMarshal_PPLLLLLLLLLLLLLLLLLLLL_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, IntPtr p3, IntPtr p4, IntPtr p5, IntPtr p6, IntPtr p7, IntPtr p8, IntPtr p9, IntPtr p10, IntPtr p11, IntPtr p12, IntPtr p13, IntPtr p14, IntPtr p15, IntPtr p16, IntPtr p17, IntPtr p18, IntPtr p19);
delegate IntPtr _JniMarshal_PPLLLLLLLLLLLLLLLLLLLLL_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, IntPtr p3, IntPtr p4, IntPtr p5, IntPtr p6, IntPtr p7, IntPtr p8, IntPtr p9, IntPtr p10, IntPtr p11, IntPtr p12, IntPtr p13, IntPtr p14, IntPtr p15, IntPtr p16, IntPtr p17, IntPtr p18, IntPtr p19, IntPtr p20);
delegate IntPtr _JniMarshal_PPLLLLLLLLLLLLLLLLLLLLLL_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, IntPtr p3, IntPtr p4, IntPtr p5, IntPtr p6, IntPtr p7, IntPtr p8, IntPtr p9, IntPtr p10, IntPtr p11, IntPtr p12, IntPtr p13, IntPtr p14, IntPtr p15, IntPtr p16, IntPtr p17, IntPtr p18, IntPtr p19, IntPtr p20, IntPtr p21);
delegate void _JniMarshal_PPLLLLLZ_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, IntPtr p3, IntPtr p4, bool p5);
delegate void _JniMarshal_PPLLLLZ_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, IntPtr p3, bool p4);
delegate int _JniMarshal_PPLLLZ_I (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, bool p3);
delegate IntPtr _JniMarshal_PPLLLZ_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, bool p3);
delegate IntPtr _JniMarshal_PPLLLZL_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, bool p3, IntPtr p4);
delegate void _JniMarshal_PPLLLZL_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, bool p3, IntPtr p4);
delegate bool _JniMarshal_PPLLLZZ_Z (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2, bool p3, bool p4);
delegate void _JniMarshal_PPLLS_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, short p2);
delegate IntPtr _JniMarshal_PPLLZI_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, bool p2, int p3);
delegate IntPtr _JniMarshal_PPLLZJ_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, bool p2, long p3);
delegate IntPtr _JniMarshal_PPLLZJL_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, bool p2, long p3, IntPtr p4);
delegate IntPtr _JniMarshal_PPLLZJLL_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, bool p2, long p3, IntPtr p4, IntPtr p5);
delegate IntPtr _JniMarshal_PPLLZZ_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, bool p2, bool p3);
delegate IntPtr _JniMarshal_PPLLZZI_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, bool p2, bool p3, int p4);
delegate void _JniMarshal_PPLSB_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, short p1, sbyte p2);
delegate void _JniMarshal_PPLSC_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, short p1, char p2);
delegate void _JniMarshal_PPLSD_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, short p1, double p2);
delegate void _JniMarshal_PPLSF_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, short p1, float p2);
delegate void _JniMarshal_PPLSI_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, short p1, int p2);
delegate void _JniMarshal_PPLSJ_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, short p1, long p2);
delegate void _JniMarshal_PPLSL_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, short p1, IntPtr p2);
delegate void _JniMarshal_PPLSS_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, short p1, short p2);
delegate void _JniMarshal_PPLSZ_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, short p1, bool p2);
delegate float _JniMarshal_PPLZ_F (IntPtr jnienv, IntPtr klazz, IntPtr p0, bool p1);
delegate void _JniMarshal_PPLZB_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, bool p1, sbyte p2);
delegate void _JniMarshal_PPLZC_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, bool p1, char p2);
delegate void _JniMarshal_PPLZD_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, bool p1, double p2);
delegate void _JniMarshal_PPLZF_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, bool p1, float p2);
delegate void _JniMarshal_PPLZFF_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, bool p1, float p2, float p3);
delegate IntPtr _JniMarshal_PPLZI_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, bool p1, int p2);
delegate bool _JniMarshal_PPLZIII_Z (IntPtr jnienv, IntPtr klazz, IntPtr p0, bool p1, int p2, int p3, int p4);
delegate bool _JniMarshal_PPLZIIII_Z (IntPtr jnienv, IntPtr klazz, IntPtr p0, bool p1, int p2, int p3, int p4, int p5);
delegate void _JniMarshal_PPLZIIL_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, bool p1, int p2, int p3, IntPtr p4);
delegate IntPtr _JniMarshal_PPLZJ_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, bool p1, long p2);
delegate void _JniMarshal_PPLZJ_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, bool p1, long p2);
delegate IntPtr _JniMarshal_PPLZJL_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, bool p1, long p2, IntPtr p3);
delegate IntPtr _JniMarshal_PPLZJLL_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, bool p1, long p2, IntPtr p3, IntPtr p4);
delegate bool _JniMarshal_PPLZLL_Z (IntPtr jnienv, IntPtr klazz, IntPtr p0, bool p1, IntPtr p2, IntPtr p3);
delegate void _JniMarshal_PPLZLLL_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, bool p1, IntPtr p2, IntPtr p3, IntPtr p4);
delegate void _JniMarshal_PPLZS_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, bool p1, short p2);
delegate bool _JniMarshal_PPLZZ_Z (IntPtr jnienv, IntPtr klazz, IntPtr p0, bool p1, bool p2);
delegate IntPtr _JniMarshal_PPLZZI_L (IntPtr jnienv, IntPtr klazz, IntPtr p0, bool p1, bool p2, int p3);
delegate void _JniMarshal_PPLZZZ_V (IntPtr jnienv, IntPtr klazz, IntPtr p0, bool p1, bool p2, bool p3);
delegate void _JniMarshal_PPZC_V (IntPtr jnienv, IntPtr klazz, bool p0, char p1);
delegate double _JniMarshal_PPZDZD_D (IntPtr jnienv, IntPtr klazz, bool p0, double p1, bool p2, double p3);
delegate float _JniMarshal_PPZFZF_F (IntPtr jnienv, IntPtr klazz, bool p0, float p1, bool p2, float p3);
delegate IntPtr _JniMarshal_PPZI_L (IntPtr jnienv, IntPtr klazz, bool p0, int p1);
delegate void _JniMarshal_PPZII_V (IntPtr jnienv, IntPtr klazz, bool p0, int p1, int p2);
delegate void _JniMarshal_PPZILI_V (IntPtr jnienv, IntPtr klazz, bool p0, int p1, IntPtr p2, int p3);
delegate void _JniMarshal_PPZILII_V (IntPtr jnienv, IntPtr klazz, bool p0, int p1, IntPtr p2, int p3, int p4);
delegate IntPtr _JniMarshal_PPZIZ_L (IntPtr jnienv, IntPtr klazz, bool p0, int p1, bool p2);
delegate int _JniMarshal_PPZIZI_I (IntPtr jnienv, IntPtr klazz, bool p0, int p1, bool p2, int p3);
delegate void _JniMarshal_PPZJ_V (IntPtr jnienv, IntPtr klazz, bool p0, long p1);
delegate long _JniMarshal_PPZJZJ_J (IntPtr jnienv, IntPtr klazz, bool p0, long p1, bool p2, long p3);
delegate bool _JniMarshal_PPZLL_Z (IntPtr jnienv, IntPtr klazz, bool p0, IntPtr p1, IntPtr p2);
delegate void _JniMarshal_PPZLLLL_V (IntPtr jnienv, IntPtr klazz, bool p0, IntPtr p1, IntPtr p2, IntPtr p3, IntPtr p4);
delegate IntPtr _JniMarshal_PPZLZL_L (IntPtr jnienv, IntPtr klazz, bool p0, IntPtr p1, bool p2, IntPtr p3);
delegate void _JniMarshal_PPZZIIL_V (IntPtr jnienv, IntPtr klazz, bool p0, bool p1, int p2, int p3, IntPtr p4);
delegate void _JniMarshal_PPZZIILL_V (IntPtr jnienv, IntPtr klazz, bool p0, bool p1, int p2, int p3, IntPtr p4, IntPtr p5);
delegate IntPtr _JniMarshal_PPZZL_L (IntPtr jnienv, IntPtr klazz, bool p0, bool p1, IntPtr p2);
delegate void _JniMarshal_PPZZL_V (IntPtr jnienv, IntPtr klazz, bool p0, bool p1, IntPtr p2);
delegate void _JniMarshal_PPZZZ_V (IntPtr jnienv, IntPtr klazz, bool p0, bool p1, bool p2);
delegate bool _JniMarshal_PPZZZZ_Z (IntPtr jnienv, IntPtr klazz, bool p0, bool p1, bool p2, bool p3);
