//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xamarin.Installer.Build.Tasks.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xamarin.Installer.Build.Tasks.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to locate Android SDK at path `{0}`..
        /// </summary>
        internal static string AndroidSdk_Not_Found {
            get {
                return ResourceManager.GetString("AndroidSdk_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to the Android SDK has not been set. Either provide the &apos;-p:AndroidSdkDirectory&apos; MSbuild property with a valid path or set the &apos;ANDROID_HOME&apos; or &apos;ANDROID_SDK_ROOT&apos; environment variables and try again..
        /// </summary>
        internal static string AndroidSdk_Not_Set {
            get {
                return ResourceManager.GetString("AndroidSdk_Not_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to install the Java SDK into `{0}`. Please set `$(JavaSdkDirectory)` to a valid non-administrator path..
        /// </summary>
        internal static string Invalid_JavaSdkDirectory {
            get {
                return ResourceManager.GetString("Invalid_JavaSdkDirectory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Detected an out of date Java SDK with version `{1}` at `{0}`, but we are unable to install the recommended Java SDK (version `{2}`) to this location.
        ///Please update your Java SDK to version `{2}`, or set `$(JavaSdkDirectory)` to a valid non-administrator path to install the recommended Java SDK version to a new location.
        /// </summary>
        internal static string Invalid_JavaSdkDirectory_ExistingInstall {
            get {
                return ResourceManager.GetString("Invalid_JavaSdkDirectory_ExistingInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find a Java SDK with version `{0}`. Please set `$(JavaSdkVersion)` to a valid version..
        /// </summary>
        internal static string Invalid_JavaSdkVersion {
            get {
                return ResourceManager.GetString("Invalid_JavaSdkVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Android SDK license agreements were not accepted, please set `$(AcceptAndroidSDKLicenses)` to accept..
        /// </summary>
        internal static string License_Not_Accepted {
            get {
                return ResourceManager.GetString("License_Not_Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to an error occurred trying to accept the Android SDK licenses. {0}.
        /// </summary>
        internal static string Licenses_Acceptance_Failed {
            get {
                return ResourceManager.GetString("Licenses_Acceptance_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error: expected to install {0} components, but no downloads were available..
        /// </summary>
        internal static string Required_Downloadable_Mismatch {
            get {
                return ResourceManager.GetString("Required_Downloadable_Mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependency `{0}` should have been installed but could not be resolved. You can attempt to install it with: `{1} --install &quot;{0}&quot;`.
        /// </summary>
        internal static string Required_Not_Installed {
            get {
                return ResourceManager.GetString("Required_Not_Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to install required Android SDK components timed out or was cancelled. Consider setting `$(AndroidDependencyInstallationTimeout)` to a value larger than `{0}` minutes..
        /// </summary>
        internal static string Task_Cancelled {
            get {
                return ResourceManager.GetString("Task_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to install required Android SDK components..
        /// </summary>
        internal static string Task_Failed {
            get {
                return ResourceManager.GetString("Task_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to `$(AndroidManifestType)` value of `{0}` is not supported. Defaulting to `Xamarin`..
        /// </summary>
        internal static string Unsupported_Manifest_Type {
            get {
                return ResourceManager.GetString("Unsupported_Manifest_Type", resourceCulture);
            }
        }
    }
}
