<Project>

  <Target Name="BuildNativeLibs"
      BeforeTargets="CoreBuild"
      DependsOnTargets="AndroidPrepareForBuild"
      Inputs="$(MSBuildThisFileDirectory)jni\reuse-threads.c;$(MSBuildThisFileDirectory)jni\Android.mk"
      Outputs="@(AndroidNativeLibrary)">
    <Error Text="Could not locate Android NDK." Condition="!Exists ('$(NdkBuildPath)')" />
    <Exec Command="&quot;$(NdkBuildPath)&quot;" WorkingDirectory="$(MSBuildThisFileDirectory)"/>
  </Target>

</Project>
