#!/bin/sh

INSTALLATION_ROOT=/Library/Frameworks/Xamarin.Android.framework/Versions
PREVIOUS_VERSION=$(readlink "$INSTALLATION_ROOT/Current")
PREVIOUS_VERSION_PATH="$INSTALLATION_ROOT/$PREVIOUS_VERSION"

# Ensure previously installed version is removed.
if [ -d "$PREVIOUS_VERSION_PATH" ]; then
	rm -rf "$PREVIOUS_VERSION_PATH"
fi

