<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\..\..\Configuration.props" />

  <PropertyGroup>
    <TargetFramework>$(DotNetTargetFramework)</TargetFramework>
    <OutputPath>..\..\..\..\bin\Test$(Configuration)</OutputPath>
    <IsPackable>false</IsPackable>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>..\..\..\..\product.snk</AssemblyOriginatorKeyFile>
    <Nullable>annotations</Nullable>
  </PropertyGroup>

  <Import Project="..\..\..\..\build-tools\scripts\NUnitReferences.projitems" />

  <ItemGroup>
    <Compile Include="..\..\..\Xamarin.Android.Build.Tasks\Tests\Xamarin.Android.Build.Tests\Utilities\MockBuildEngine.cs" Link="MockBuildEngine.cs" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.IO.Hashing" HintPath="$(NuGetPackageRoot)system.io.hashing\$(SystemIOHashingPackageVersion)\lib\netstandard2.0\System.IO.Hashing.dll" Private="true" />
    <ProjectReference Include="..\..\Microsoft.Android.Build.Tasks.csproj" />
  </ItemGroup>

</Project>
