<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\..\..\Configuration.props" />

  <PropertyGroup>
    <TargetFramework>$(DotNetTargetFramework)</TargetFramework>
    <OutputPath>..\..\..\..\bin\Test$(Configuration)</OutputPath>
    <IsPackable>false</IsPackable>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>..\..\..\..\product.snk</AssemblyOriginatorKeyFile>
    <Nullable>annotations</Nullable>
  </PropertyGroup>

  <Import Project="..\..\..\..\build-tools\scripts\NUnitReferences.projitems" />

  <ItemGroup>
    <Compile Include="..\..\..\Xamarin.Android.Build.Tasks\Tests\Xamarin.Android.Build.Tests\Utilities\MockBuildEngine.cs" Link="MockBuildEngine.cs" />
    <None Update="Resources\NativeAotBootstrap\**" CopyToOutputDirectory="PreserveNewest" />
    <AssemblyMetadata Include="ILLinkPath" Value="$([MSBuild]::NormalizePath('$(PkgMicrosoft_NET_ILLink_Tasks)', 'tools', 'net', 'illink.dll'))" />
    <AssemblyMetadata Include="NativeAotLlvmReadObjPath" Value="$(_NativeAotLlvmReadObjPath)" />
    <AssemblyMetadata Include="AndroidNdkDirectory" Value="$(AndroidNdkDirectory)" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Mono.Cecil" Version="$(MonoCecilVersion)" />
    <PackageReference Include="Microsoft.NET.ILLink.Tasks" Version="$(MicrosoftNETILLinkPackageVersion)" PrivateAssets="all" GeneratePathProperty="true" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Microsoft.Android.Build.Tasks.csproj" />
    <ProjectReference Include="..\..\..\Microsoft.Android.Sdk.TrimmableTypeMap\Microsoft.Android.Sdk.TrimmableTypeMap.csproj" />
  </ItemGroup>

</Project>
