//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by 'manifest-attribute-codegen'.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using System;

namespace Android.App;

[Serializable]
[AttributeUsage (AttributeTargets.Assembly, AllowMultiple = true, Inherited = false)]
public sealed partial class PermissionAttribute : Attribute {
	public PermissionAttribute ()
	{
	}

	public string? Description { get; set; }

	public string? Icon { get; set; }

	public string? Label { get; set; }

	public string? Name { get; set; }

	public string? PermissionGroup { get; set; }

	public Android.Content.PM.Protection ProtectionLevel { get; set; }

	public string? RoundIcon { get; set; }

}
