//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by 'manifest-attribute-codegen'.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using System;

namespace Android.App;

[Serializable]
[AttributeUsage (AttributeTargets.Assembly, AllowMultiple = true, Inherited = false)]
public sealed partial class UsesFeatureAttribute : Attribute {
	public UsesFeatureAttribute ()
	{
	}

	public int GLESVersion { get; set; }

	public string? Name { get; private set; }

	public bool Required { get; set; }

	public int Version { get; private set; }

}
