//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by 'manifest-attribute-codegen'.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using System;

namespace Android.App;

[Serializable]
[AttributeUsage (AttributeTargets.Assembly, AllowMultiple = true, Inherited = false)]
public sealed partial class UsesFeatureAttribute : Attribute {
	public UsesFeatureAttribute ()
	{
	}

	public int GLESVersion { get; set; }

	public string? Name { get; private set; }

	public bool Required { get; set; }

	public int Version { get; private set; }

#if XABT_MANIFEST_EXTENSIONS
	static Xamarin.Android.Manifest.ManifestDocumentElement<UsesFeatureAttribute> mapping = new ("uses-feature");

	static UsesFeatureAttribute ()
	{
		mapping.Add (
			member: "Name",
			attributeName: "name",
			getter: self => self.Name,
			setter: null
		);
		mapping.Add (
			member: "Required",
			attributeName: "required",
			getter: self => self.Required,
			setter: (self, value) => self.Required = (bool) value
		);
		mapping.Add (
			member: "Version",
			attributeName: "version",
			getter: self => self.Version,
			setter: null
		);

		AddManualMapping ();
	}

	static partial void AddManualMapping ();
#endif // XABT_MANIFEST_EXTENSIONS
}
