//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by 'manifest-attribute-codegen'.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using System;

namespace Android.App;

[Serializable]
[AttributeUsage (AttributeTargets.Assembly, AllowMultiple = true, Inherited = false)]
public sealed partial class UsesPermissionAttribute : Attribute {
	public UsesPermissionAttribute ()
	{
	}

	public int MaxSdkVersion { get; set; }

	public string? Name { get; set; }

#if XABT_MANIFEST_EXTENSIONS
	static Xamarin.Android.Manifest.ManifestDocumentElement<UsesPermissionAttribute> mapping = new ("uses-permission");

	static UsesPermissionAttribute ()
	{
		mapping.Add (
			member: "MaxSdkVersion",
			attributeName: "maxSdkVersion",
			getter: self => self.MaxSdkVersion,
			setter: (self, value) => self.MaxSdkVersion = (int) value
		);
		mapping.Add (
			member: "Name",
			attributeName: "name",
			getter: self => self.Name,
			setter: (self, value) => self.Name = (string?) value
		);

		AddManualMapping ();
	}

	static partial void AddManualMapping ();
#endif
}
