//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by 'manifest-attribute-codegen'.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using System;

namespace Android.Content;

[Serializable]
[AttributeUsage (AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
public partial class GrantUriPermissionAttribute : Attribute {
	public GrantUriPermissionAttribute ()
	{
	}

	public string? Path { get; set; }

	public string? PathPattern { get; set; }

	public string? PathPrefix { get; set; }

}
