# .NET for Android Release Definition Trigger

name: $(Build.SourceBranchName)-$(Build.SourceVersion)-$(Rev:r)

trigger: none
pr: none

resources:
  pipelines:
  - pipeline: xamarin-android
    source: Xamarin.Android
    trigger:
      stages:
      - post_build
      branches:
        exclude:
        - main
        - release/*

jobs:
- job: release_trigger
  displayName: Upload Info from Triggering Build
  timeoutInMinutes: 30
  pool: VSEngSS-MicroBuild2022-1ES
  workspace:
    clean: all
  steps:
  - checkout: none

  - powershell: 'gci env: | format-table -autosize -wrap'
    displayName: print environment variables

  - powershell: |
      $triggeringBuild = @{
          "triggeringBuild" = @{
              "id" = "$(resources.pipeline.xamarin-android.runID)"
              "pipeline" = "$(resources.pipeline.xamarin-android.pipelineID)"
              "branch" = "$(resources.pipeline.xamarin-android.sourceBranch)"
              "commit" = "$(resources.pipeline.xamarin-android.sourceCommit)"
          }
      }
      $json = $triggeringBuild | ConvertTo-Json
      New-Item -Path $(Build.StagingDirectory) -Name triggering-build.json -ItemType file -Value $json -Force
      $jsonContent = Get-Content "$(Build.StagingDirectory)\triggering-build.json" | ConvertFrom-Json
      Write-Host Triggering Pipeline and Run IDs: $jsonContent.triggeringBuild.pipeline - $jsonContent.triggeringBuild.id
    displayName: write triggering-build.json

  - task: PublishPipelineArtifact@1
    displayName: upload triggering-build-info
    inputs:
      artifactName: triggering-build-info
      targetPath: $(Build.StagingDirectory)\triggering-build.json
