# Xamarin.Android Pipeline

trigger:
  - master
  - d16*

# Global variables
variables:
  BundleArtifactName: bundle
  AutoProvisionArgs: /p:AutoProvision=True /p:AutoProvisionUsesSudo=True /p:IgnoreMaxMonoVersion=False
  MSBuildAbiArgs: >
    /p:AndroidSupportedTargetJitAbis=armeabi-v7a:arm64-v8a:x86:x86_64
    /p:AndroidSupportedHostJitAbis=Darwin:mxe-Win32:mxe-Win64
    /p:AndroidSupportedTargetAotAbis=armeabi-v7a:arm64:x86:x86_64:win-armeabi-v7a:win-arm64:win-x86:win-x86_64

stages:
- stage: prepare
  displayName: Prepare
  variables:
    Configuration: Release
  jobs:
  - job: create_bundle
    displayName: Create Bundle
    pool: Hosted Mac Internal
    timeoutInMinutes: 60
    cancelTimeoutInMinutes: 5
    steps:
    - script: make prepare-deps V=1 CONFIGURATION=$(Configuration) MSBUILD_ARGS="$(AutoProvisionArgs) $(MSBuildAbiArgs)"
      displayName: make prepare-deps

    - task: MSBuild@1
      displayName: create bundle
      inputs:
        solution: build-tools/create-bundle/create-bundle.csproj
        configuration: $(Configuration)
        msbuildArguments: $(MSBuildAbiArgs)

    - task: CopyFiles@2
      displayName: copy bundle
      inputs:
        sourceFolder: bin/$(Configuration)
        contents: bundle-*.zip
        targetFolder: $(Build.ArtifactStagingDirectory)

    - task: PublishPipelineArtifact@0
      displayName: upload bundle
      inputs:
        artifactName: $(BundleArtifactName)
        targetPath: $(Build.ArtifactStagingDirectory)

- stage: mac_build
  displayName: Mac
  dependsOn: prepare
  jobs:
  - job: mac_build
    displayName: Build
    pool: Hosted Mac Internal
    timeoutInMinutes: 240
    cancelTimeoutInMinutes: 5
    variables:
      Configuration: Release
      JavaSdkDirectory: /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/
      JAVA_HOME: $(JavaSdkDirectory)
    steps:
    - task: DownloadPipelineArtifact@1
      inputs:
        artifactName: $(BundleArtifactName)
        downloadPath: $(System.DefaultWorkingDirectory)

    - script: make prepare-external-git-dependencies CONFIGURATION=$(Configuration)
      displayName: make prepare-commercial
      condition: eq(variables['XA.Commercial.Build'], 'true')
      env:
        GH_AUTH_SECRET: $(Github.Token)

    - task: provisionator@2
      condition: and(succeeded(), eq(variables['XA.Commercial.Build'], 'true'))
      inputs:
        provisionator_uri: $(provisionator-uri)
        github_token: $(GitHub.Token)
        provisioning_script: $(System.DefaultWorkingDirectory)/external/monodroid/build-tools/provisionator/profile.csx
        provisioning_extra_args: -vv

    - script: make prepare-deps V=1 CONFIGURATION=$(Configuration) MSBUILD_ARGS="$(AutoProvisionArgs)"
      displayName: make prepare-deps

    - script: make prepare jenkins V=1 CONFIGURATION=$(Configuration) MSBUILD_ARGS="$(AutoProvisionArgs) /p:BundleRootPath=$(System.DefaultWorkingDirectory)/$(BundleArtifactName)"
      displayName: make prepare jenkins

    - script: make create-installers V=1 CONFIGURATION=$(Configuration)
      displayName: make create-installers

    - script: |
        mkdir -p $(System.DefaultWorkingDirectory)/unsigned-installers
        cp bin/Build$(Configuration)/*.vsix $(System.DefaultWorkingDirectory)/unsigned-installers
        cp bin/Build$(Configuration)/*.pkg $(System.DefaultWorkingDirectory)/unsigned-installers
      displayName: copy build artifacts

    - task: PublishPipelineArtifact@0
      displayName: upload unsigned installers
      inputs:
        artifactName: unsigned
        targetPath: $(System.DefaultWorkingDirectory)/unsigned-installers

    - script: cp bin/*/*.binlog $(Build.ArtifactStagingDirectory)
      displayName: copy binlogs
      condition: always()

    - task: PublishPipelineArtifact@0
      displayName: upload artifacts
      inputs:
        artifactName: mac-build-results
        targetPath: $(Build.ArtifactStagingDirectory)
      condition: always()

- stage: win_build_test
  displayName: Win
  dependsOn: prepare
  variables:
    Configuration: Release
  jobs:
  - job: build_test
    displayName: Build and Test
    pool: Hosted VS2017
    timeoutInMinutes: 240
    cancelTimeoutInMinutes: 5
    variables:
      _AndroidDesignTimeResDirIntermediate: .
      CleanAllFiles: False
      CleanOnNuGetPackagesChange: False
      NuGet.Show.Stack: true
      NUnit.Extra: --trace=Verbose
    steps:
    - task: DownloadPipelineArtifact@1
      inputs:
        artifactName: $(BundleArtifactName)
        downloadPath: $(System.DefaultWorkingDirectory)

    - task: MSBuild@1
      displayName: msbuild Xamarin.Android /t:Prepare
      inputs:
        solution: Xamarin.Android.sln
        msbuildVersion: 15.0
        msbuildArguments: /t:Prepare /bl:$(Build.ArtifactStagingDirectory)\prepare.binlog /p:BundleRootPath=$(System.DefaultWorkingDirectory)\$(BundleArtifactName)

    - task: MSBuild@1
      displayName: msbuild Xamarin.Android /t:Build
      inputs:
        solution: Xamarin.Android.sln
        msbuildVersion: 15.0
        msbuildArguments: /t:Build /bl:$(Build.ArtifactStagingDirectory)\build.binlog

    - task: MSBuild@1
      displayName: msbuild create-vsix
      inputs:
        solution: build-tools\create-vsix\create-vsix.csproj
        msbuildArguments: /p:Configurations=$(Configuration) /p:CreateVsixContainer=True /p:ZipPackageCompressionLevel=Normal /bl:$(Build.ArtifactStagingDirectory)\create-vsix.binlog

    - task: CmdLine@1
      displayName: xabuild Xamarin.Android-Tests
      inputs:
        filename: bin\$(Configuration)\bin\xabuild.exe
        arguments: Xamarin.Android-Tests.sln /p:XAIntegratedTests=False /bl:$(Build.ArtifactStagingDirectory)\build-tests.binlog

    - task: MSBuild@1
      displayName: nunit Xamarin.Android.Build.Tests
      inputs:
        solution: Xamarin.Android.sln
        msbuildArguments: /t:RunNUnitTests /bl:$(Build.ArtifactStagingDirectory)\run-nunit-tests.binlog
      condition: succeededOrFailed()
      timeoutInMinutes: 120

    - task: MSBuild@1
      displayName: nunit Java.Interop Tests
      inputs:
        solution: Xamarin.Android.sln
        msbuildArguments: >
          /t:RunJavaInteropTests
          /p:TestAssembly="bin\Test$(Configuration)\generator-Tests.dll;bin\Test$(Configuration)\Java.Interop.Tools.JavaCallableWrappers-Tests.dll;bin\Test$(Configuration)\LogcatParse-Tests.dll;bin\Test$(Configuration)\Xamarin.Android.Tools.ApiXmlAdjuster-Tests.dll;bin\Test$(Configuration)\Xamarin.Android.Tools.Bytecode-Tests.dll"
          /bl:$(Build.ArtifactStagingDirectory)\run-ji-tests.binlog
      condition: succeededOrFailed()

    - task: PublishTestResults@2
      displayName: publish test results
      inputs:
        testResultsFormat: NUnit
        testResultsFiles: TestResult-*.xml
        testRunTitle: xamarin-android
        failTaskOnFailedTests: true
      condition: succeededOrFailed()

    - task: CopyFiles@2
      displayName: copy test artifacts
      inputs:
        contents: |
          TestResult-*
          *.log
          bin\Test$(Configuration)\TestOutput*.txt
          bin\Test$(Configuration)\temp\**\*.binlog
          bin\Test$(Configuration)\temp\**\*.log
        targetFolder: $(Build.ArtifactStagingDirectory)\Test$(Configuration)
        condition: always()

    - task: CopyFiles@2
      displayName: copy temp files
      inputs:
        sourceFolder: $(temp)
        contents: llc.exe-*
        targetFolder: $(Build.ArtifactStagingDirectory)
      condition: always()

    - task: PublishBuildArtifacts@1
      displayName: publish build and test artifacts
      inputs:
        artifactName: win-build-results
      condition: always()
