# Xamarin.Android Pipeline

trigger:
  - master
  - d16*

stages:
- stage: Build
  jobs:
  - job: Mac
    pool: Hosted Mac Internal
    variables:
      configuration: Release
      msbuildArgs: /p:AutoProvision=True /p:AutoProvisionUsesSudo=True /p:IgnoreMaxMonoVersion=False
    steps:
    - script: make prepare-external-git-dependencies CONFIGURATION=$(configuration)
      displayName: make prepare-commercial
      condition: eq(variables['XA.Commercial.Build'], 'true')
      env:
        GH_AUTH_SECRET: $(Github.Token)
    - task: provisionator@2
      condition: and(succeeded(), eq(variables['XA.Commercial.Build'], 'true'))
      inputs:
        provisionator_uri: $(provisionator-uri)
        github_token: $(GitHub.Token)
        provisioning_script: $(System.DefaultWorkingDirectory)/external/monodroid/build-tools/provisionator/profile.csx
        provisioning_extra_args: -vv
    - script: make prepare-deps V=1 CONFIGURATION=$(configuration) MSBUILD_ARGS="$(msbuildArgs)"
      displayName: make prepare-deps
    - script: make prepare jenkins V=1 CONFIGURATION=$(configuration) MSBUILD_ARGS="$(msbuildArgs)"
      displayName: make prepare jenkins
    - script: make create-installers V=1 CONFIGURATION=$(configuration)
      displayName: make create-installers
    - script: |
       mkdir -p $(System.DefaultWorkingDirectory)/unsigned-installers
       cp bin/Build$(configuration)/*.vsix $(System.DefaultWorkingDirectory)/unsigned-installers
       cp bin/Build$(configuration)/*.pkg $(System.DefaultWorkingDirectory)/unsigned-installers
       cp *.zip $(Build.ArtifactStagingDirectory)
      displayName: copy build artifacts
    - task: PublishPipelineArtifact@0
      displayName: upload unsigned installers
      inputs:
        artifactName: unsigned
        targetPath: $(System.DefaultWorkingDirectory)/unsigned-installers
    - script: cp bin/*/*.binlog $(Build.ArtifactStagingDirectory)
      displayName: copy binlogs
      condition: always()
    - task: PublishPipelineArtifact@0
      displayName: upload artifacts
      inputs:
        artifactName: artifacts
        targetPath: $(Build.ArtifactStagingDirectory)
      condition: always()
