<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\..\Configuration.props" />

  <PropertyGroup>
    <TargetFramework>$(DotNetTargetFramework)</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <NoWarn>$(NoWarn);CS0436</NoWarn>
    <OutputType>Library</OutputType>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>..\..\..\product.snk</AssemblyOriginatorKeyFile>
    <OutputPath>..\..\..\bin\Test$(Configuration)\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Mono.Android\Mono.Android.csproj"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>

  <Target Name="_AddMonoAndroidReference" BeforeTargets="ResolveAssemblyReferences">
    <ItemGroup>
      <_MonoAndroidRefCandidate
          Condition=" '%(AndroidBuildApiLevel.Unstable)' == 'false' "
          Include="$(MSBuildThisFileDirectory)..\..\..\bin\$(Configuration)\lib\packs\Microsoft.Android.Ref.%(AndroidBuildApiLevel.Identity)\*\ref\net*\Mono.Android.dll"
      />
      <_JavaInteropRefCandidate
          Condition=" '%(AndroidBuildApiLevel.Unstable)' == 'false' "
          Include="$(MSBuildThisFileDirectory)..\..\..\bin\$(Configuration)\lib\packs\Microsoft.Android.Ref.%(AndroidBuildApiLevel.Identity)\*\ref\net*\Java.Interop.dll"
      />
    </ItemGroup>
    <PropertyGroup>
      <_MonoAndroidRefAssembly>@(_MonoAndroidRefCandidate, ';')</_MonoAndroidRefAssembly>
      <_MonoAndroidRefAssembly>$(_MonoAndroidRefAssembly.Split(';')[0])</_MonoAndroidRefAssembly>
      <_JavaInteropRefAssembly>@(_JavaInteropRefCandidate, ';')</_JavaInteropRefAssembly>
      <_JavaInteropRefAssembly>$(_JavaInteropRefAssembly.Split(';')[0])</_JavaInteropRefAssembly>
    </PropertyGroup>
    <ItemGroup Condition=" '$(_MonoAndroidRefAssembly)' != '' ">
      <Reference Include="Mono.Android">
        <HintPath>$(_MonoAndroidRefAssembly)</HintPath>
      </Reference>
    </ItemGroup>
    <ItemGroup Condition=" '$(_JavaInteropRefAssembly)' != '' ">
      <Reference Include="Java.Interop">
        <HintPath>$(_JavaInteropRefAssembly)</HintPath>
      </Reference>
    </ItemGroup>
  </Target>
</Project>
